/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StoreActivateRouteImport } from './routes/store-activate'
import { Route as ProfileRouteRouteImport } from './routes/profile/route'
import { Route as MyStoreRouteRouteImport } from './routes/my-store/route'
import { Route as BaseLayoutRouteRouteImport } from './routes/_base-layout/route'
import { Route as TermsOfUseIndexRouteImport } from './routes/terms-of-use/index'
import { Route as ProfileIndexRouteImport } from './routes/profile/index'
import { Route as PrivacyPolicyIndexRouteImport } from './routes/privacy-policy/index'
import { Route as MyStoreIndexRouteImport } from './routes/my-store/index'
import { Route as ContactUsIndexRouteImport } from './routes/contact-us/index'
import { Route as CheckoutIndexRouteImport } from './routes/checkout/index'
import { Route as AboutUsIndexRouteImport } from './routes/about-us/index'
import { Route as BaseLayoutIndexRouteImport } from './routes/_base-layout/index'
import { Route as ProfileTermsOfUseRouteImport } from './routes/profile/terms-of-use'
import { Route as ProfileReturnsRouteImport } from './routes/profile/returns'
import { Route as ProfilePrivacyPolicyRouteImport } from './routes/profile/privacy-policy'
import { Route as ProfileNotificationsRouteImport } from './routes/profile/notifications'
import { Route as ProfileLogoutRouteImport } from './routes/profile/logout'
import { Route as ProfileFavoritesRouteImport } from './routes/profile/favorites'
import { Route as ProfileEditRouteImport } from './routes/profile/edit'
import { Route as ProfileCartRouteImport } from './routes/profile/cart'
import { Route as ProfileAnalyticsRouteImport } from './routes/profile/analytics'
import { Route as ProfileAddressesRouteImport } from './routes/profile/addresses'
import { Route as MyStoreStoreIdRouteRouteImport } from './routes/my-store/$storeId/route'
import { Route as MyStoreStoreIdIndexRouteImport } from './routes/my-store/$storeId/index'
import { Route as BaseLayoutStoresIndexRouteImport } from './routes/_base-layout/stores/index'
import { Route as BaseLayoutSearchIndexRouteImport } from './routes/_base-layout/search/index'
import { Route as BaseLayoutBrandsIndexRouteImport } from './routes/_base-layout/brands/index'
import { Route as BaseLayoutProductIdIndexRouteImport } from './routes/_base-layout/$productId/index'
import { Route as MyStoreStoreIdWarehouseRouteImport } from './routes/my-store/$storeId/warehouse'
import { Route as MyStoreStoreIdTermsOfUseRouteImport } from './routes/my-store/$storeId/terms-of-use'
import { Route as MyStoreStoreIdStoreInformationRouteImport } from './routes/my-store/$storeId/store-information'
import { Route as MyStoreStoreIdStockRouteImport } from './routes/my-store/$storeId/stock'
import { Route as MyStoreStoreIdReturnsRouteImport } from './routes/my-store/$storeId/returns'
import { Route as MyStoreStoreIdReceiptsRouteImport } from './routes/my-store/$storeId/receipts'
import { Route as MyStoreStoreIdProductsRouteImport } from './routes/my-store/$storeId/products'
import { Route as MyStoreStoreIdPrivacyPolicyRouteImport } from './routes/my-store/$storeId/privacy-policy'
import { Route as MyStoreStoreIdOrdersRouteImport } from './routes/my-store/$storeId/orders'
import { Route as MyStoreStoreIdIntakeRouteImport } from './routes/my-store/$storeId/intake'
import { Route as MyStoreStoreIdCloseRouteImport } from './routes/my-store/$storeId/close'
import { Route as MyStoreStoreIdProductsIndexRouteImport } from './routes/my-store/$storeId/products.index'
import { Route as BaseLayoutStoresStoreIdIndexRouteImport } from './routes/_base-layout/stores/$storeId/index'
import { Route as BaseLayoutCollectionsCollectionIdIndexRouteImport } from './routes/_base-layout/collections/$collectionId/index'
import { Route as BaseLayoutCategoriesCategoryIdIndexRouteImport } from './routes/_base-layout/categories/$categoryId/index'
import { Route as BaseLayoutBrandsBrandIdIndexRouteImport } from './routes/_base-layout/brands/$brandId/index'
import { Route as MyStoreStoreIdProductsAddRouteImport } from './routes/my-store/$storeId/products.add'
import { Route as BaseLayoutStoresStoreIdProductIdIndexRouteImport } from './routes/_base-layout/stores/$storeId/$productId/index'
import { Route as BaseLayoutCategoriesCategoryIdProductIdIndexRouteImport } from './routes/_base-layout/categories/$categoryId/$productId/index'
import { Route as BaseLayoutBrandsBrandIdProductIdIndexRouteImport } from './routes/_base-layout/brands/$brandId/$productId/index'
import { Route as MyStoreStoreIdProductsEditProductIdRouteImport } from './routes/my-store/$storeId/products.edit.$productId'

const StoreActivateRoute = StoreActivateRouteImport.update({
  id: '/store-activate',
  path: '/store-activate',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRouteRoute = ProfileRouteRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MyStoreRouteRoute = MyStoreRouteRouteImport.update({
  id: '/my-store',
  path: '/my-store',
  getParentRoute: () => rootRouteImport,
} as any)
const BaseLayoutRouteRoute = BaseLayoutRouteRouteImport.update({
  id: '/_base-layout',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsOfUseIndexRoute = TermsOfUseIndexRouteImport.update({
  id: '/terms-of-use/',
  path: '/terms-of-use/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProfileRouteRoute,
} as any)
const PrivacyPolicyIndexRoute = PrivacyPolicyIndexRouteImport.update({
  id: '/privacy-policy/',
  path: '/privacy-policy/',
  getParentRoute: () => rootRouteImport,
} as any)
const MyStoreIndexRoute = MyStoreIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MyStoreRouteRoute,
} as any)
const ContactUsIndexRoute = ContactUsIndexRouteImport.update({
  id: '/contact-us/',
  path: '/contact-us/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutIndexRoute = CheckoutIndexRouteImport.update({
  id: '/checkout/',
  path: '/checkout/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutUsIndexRoute = AboutUsIndexRouteImport.update({
  id: '/about-us/',
  path: '/about-us/',
  getParentRoute: () => rootRouteImport,
} as any)
const BaseLayoutIndexRoute = BaseLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BaseLayoutRouteRoute,
} as any)
const ProfileTermsOfUseRoute = ProfileTermsOfUseRouteImport.update({
  id: '/terms-of-use',
  path: '/terms-of-use',
  getParentRoute: () => ProfileRouteRoute,
} as any)
const ProfileReturnsRoute = ProfileReturnsRouteImport.update({
  id: '/returns',
  path: '/returns',
  getParentRoute: () => ProfileRouteRoute,
} as any)
const ProfilePrivacyPolicyRoute = ProfilePrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => ProfileRouteRoute,
} as any)
const ProfileNotificationsRoute = ProfileNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => ProfileRouteRoute,
} as any)
const ProfileLogoutRoute = ProfileLogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => ProfileRouteRoute,
} as any)
const ProfileFavoritesRoute = ProfileFavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => ProfileRouteRoute,
} as any)
const ProfileEditRoute = ProfileEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => ProfileRouteRoute,
} as any)
const ProfileCartRoute = ProfileCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => ProfileRouteRoute,
} as any)
const ProfileAnalyticsRoute = ProfileAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => ProfileRouteRoute,
} as any)
const ProfileAddressesRoute = ProfileAddressesRouteImport.update({
  id: '/addresses',
  path: '/addresses',
  getParentRoute: () => ProfileRouteRoute,
} as any)
const MyStoreStoreIdRouteRoute = MyStoreStoreIdRouteRouteImport.update({
  id: '/$storeId',
  path: '/$storeId',
  getParentRoute: () => MyStoreRouteRoute,
} as any)
const MyStoreStoreIdIndexRoute = MyStoreStoreIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MyStoreStoreIdRouteRoute,
} as any)
const BaseLayoutStoresIndexRoute = BaseLayoutStoresIndexRouteImport.update({
  id: '/stores/',
  path: '/stores/',
  getParentRoute: () => BaseLayoutRouteRoute,
} as any)
const BaseLayoutSearchIndexRoute = BaseLayoutSearchIndexRouteImport.update({
  id: '/search/',
  path: '/search/',
  getParentRoute: () => BaseLayoutRouteRoute,
} as any)
const BaseLayoutBrandsIndexRoute = BaseLayoutBrandsIndexRouteImport.update({
  id: '/brands/',
  path: '/brands/',
  getParentRoute: () => BaseLayoutRouteRoute,
} as any)
const BaseLayoutProductIdIndexRoute =
  BaseLayoutProductIdIndexRouteImport.update({
    id: '/$productId/',
    path: '/$productId/',
    getParentRoute: () => BaseLayoutRouteRoute,
  } as any)
const MyStoreStoreIdWarehouseRoute = MyStoreStoreIdWarehouseRouteImport.update({
  id: '/warehouse',
  path: '/warehouse',
  getParentRoute: () => MyStoreStoreIdRouteRoute,
} as any)
const MyStoreStoreIdTermsOfUseRoute =
  MyStoreStoreIdTermsOfUseRouteImport.update({
    id: '/terms-of-use',
    path: '/terms-of-use',
    getParentRoute: () => MyStoreStoreIdRouteRoute,
  } as any)
const MyStoreStoreIdStoreInformationRoute =
  MyStoreStoreIdStoreInformationRouteImport.update({
    id: '/store-information',
    path: '/store-information',
    getParentRoute: () => MyStoreStoreIdRouteRoute,
  } as any)
const MyStoreStoreIdStockRoute = MyStoreStoreIdStockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => MyStoreStoreIdRouteRoute,
} as any)
const MyStoreStoreIdReturnsRoute = MyStoreStoreIdReturnsRouteImport.update({
  id: '/returns',
  path: '/returns',
  getParentRoute: () => MyStoreStoreIdRouteRoute,
} as any)
const MyStoreStoreIdReceiptsRoute = MyStoreStoreIdReceiptsRouteImport.update({
  id: '/receipts',
  path: '/receipts',
  getParentRoute: () => MyStoreStoreIdRouteRoute,
} as any)
const MyStoreStoreIdProductsRoute = MyStoreStoreIdProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => MyStoreStoreIdRouteRoute,
} as any)
const MyStoreStoreIdPrivacyPolicyRoute =
  MyStoreStoreIdPrivacyPolicyRouteImport.update({
    id: '/privacy-policy',
    path: '/privacy-policy',
    getParentRoute: () => MyStoreStoreIdRouteRoute,
  } as any)
const MyStoreStoreIdOrdersRoute = MyStoreStoreIdOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => MyStoreStoreIdRouteRoute,
} as any)
const MyStoreStoreIdIntakeRoute = MyStoreStoreIdIntakeRouteImport.update({
  id: '/intake',
  path: '/intake',
  getParentRoute: () => MyStoreStoreIdRouteRoute,
} as any)
const MyStoreStoreIdCloseRoute = MyStoreStoreIdCloseRouteImport.update({
  id: '/close',
  path: '/close',
  getParentRoute: () => MyStoreStoreIdRouteRoute,
} as any)
const MyStoreStoreIdProductsIndexRoute =
  MyStoreStoreIdProductsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => MyStoreStoreIdProductsRoute,
  } as any)
const BaseLayoutStoresStoreIdIndexRoute =
  BaseLayoutStoresStoreIdIndexRouteImport.update({
    id: '/stores/$storeId/',
    path: '/stores/$storeId/',
    getParentRoute: () => BaseLayoutRouteRoute,
  } as any)
const BaseLayoutCollectionsCollectionIdIndexRoute =
  BaseLayoutCollectionsCollectionIdIndexRouteImport.update({
    id: '/collections/$collectionId/',
    path: '/collections/$collectionId/',
    getParentRoute: () => BaseLayoutRouteRoute,
  } as any)
const BaseLayoutCategoriesCategoryIdIndexRoute =
  BaseLayoutCategoriesCategoryIdIndexRouteImport.update({
    id: '/categories/$categoryId/',
    path: '/categories/$categoryId/',
    getParentRoute: () => BaseLayoutRouteRoute,
  } as any)
const BaseLayoutBrandsBrandIdIndexRoute =
  BaseLayoutBrandsBrandIdIndexRouteImport.update({
    id: '/brands/$brandId/',
    path: '/brands/$brandId/',
    getParentRoute: () => BaseLayoutRouteRoute,
  } as any)
const MyStoreStoreIdProductsAddRoute =
  MyStoreStoreIdProductsAddRouteImport.update({
    id: '/add',
    path: '/add',
    getParentRoute: () => MyStoreStoreIdProductsRoute,
  } as any)
const BaseLayoutStoresStoreIdProductIdIndexRoute =
  BaseLayoutStoresStoreIdProductIdIndexRouteImport.update({
    id: '/stores/$storeId/$productId/',
    path: '/stores/$storeId/$productId/',
    getParentRoute: () => BaseLayoutRouteRoute,
  } as any)
const BaseLayoutCategoriesCategoryIdProductIdIndexRoute =
  BaseLayoutCategoriesCategoryIdProductIdIndexRouteImport.update({
    id: '/categories/$categoryId/$productId/',
    path: '/categories/$categoryId/$productId/',
    getParentRoute: () => BaseLayoutRouteRoute,
  } as any)
const BaseLayoutBrandsBrandIdProductIdIndexRoute =
  BaseLayoutBrandsBrandIdProductIdIndexRouteImport.update({
    id: '/brands/$brandId/$productId/',
    path: '/brands/$brandId/$productId/',
    getParentRoute: () => BaseLayoutRouteRoute,
  } as any)
const MyStoreStoreIdProductsEditProductIdRoute =
  MyStoreStoreIdProductsEditProductIdRouteImport.update({
    id: '/edit/$productId',
    path: '/edit/$productId',
    getParentRoute: () => MyStoreStoreIdProductsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof BaseLayoutIndexRoute
  '/my-store': typeof MyStoreRouteRouteWithChildren
  '/profile': typeof ProfileRouteRouteWithChildren
  '/store-activate': typeof StoreActivateRoute
  '/my-store/$storeId': typeof MyStoreStoreIdRouteRouteWithChildren
  '/profile/addresses': typeof ProfileAddressesRoute
  '/profile/analytics': typeof ProfileAnalyticsRoute
  '/profile/cart': typeof ProfileCartRoute
  '/profile/edit': typeof ProfileEditRoute
  '/profile/favorites': typeof ProfileFavoritesRoute
  '/profile/logout': typeof ProfileLogoutRoute
  '/profile/notifications': typeof ProfileNotificationsRoute
  '/profile/privacy-policy': typeof ProfilePrivacyPolicyRoute
  '/profile/returns': typeof ProfileReturnsRoute
  '/profile/terms-of-use': typeof ProfileTermsOfUseRoute
  '/about-us/': typeof AboutUsIndexRoute
  '/checkout/': typeof CheckoutIndexRoute
  '/contact-us/': typeof ContactUsIndexRoute
  '/my-store/': typeof MyStoreIndexRoute
  '/privacy-policy/': typeof PrivacyPolicyIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/terms-of-use/': typeof TermsOfUseIndexRoute
  '/my-store/$storeId/close': typeof MyStoreStoreIdCloseRoute
  '/my-store/$storeId/intake': typeof MyStoreStoreIdIntakeRoute
  '/my-store/$storeId/orders': typeof MyStoreStoreIdOrdersRoute
  '/my-store/$storeId/privacy-policy': typeof MyStoreStoreIdPrivacyPolicyRoute
  '/my-store/$storeId/products': typeof MyStoreStoreIdProductsRouteWithChildren
  '/my-store/$storeId/receipts': typeof MyStoreStoreIdReceiptsRoute
  '/my-store/$storeId/returns': typeof MyStoreStoreIdReturnsRoute
  '/my-store/$storeId/stock': typeof MyStoreStoreIdStockRoute
  '/my-store/$storeId/store-information': typeof MyStoreStoreIdStoreInformationRoute
  '/my-store/$storeId/terms-of-use': typeof MyStoreStoreIdTermsOfUseRoute
  '/my-store/$storeId/warehouse': typeof MyStoreStoreIdWarehouseRoute
  '/$productId/': typeof BaseLayoutProductIdIndexRoute
  '/brands/': typeof BaseLayoutBrandsIndexRoute
  '/search/': typeof BaseLayoutSearchIndexRoute
  '/stores/': typeof BaseLayoutStoresIndexRoute
  '/my-store/$storeId/': typeof MyStoreStoreIdIndexRoute
  '/my-store/$storeId/products/add': typeof MyStoreStoreIdProductsAddRoute
  '/brands/$brandId/': typeof BaseLayoutBrandsBrandIdIndexRoute
  '/categories/$categoryId/': typeof BaseLayoutCategoriesCategoryIdIndexRoute
  '/collections/$collectionId/': typeof BaseLayoutCollectionsCollectionIdIndexRoute
  '/stores/$storeId/': typeof BaseLayoutStoresStoreIdIndexRoute
  '/my-store/$storeId/products/': typeof MyStoreStoreIdProductsIndexRoute
  '/my-store/$storeId/products/edit/$productId': typeof MyStoreStoreIdProductsEditProductIdRoute
  '/brands/$brandId/$productId/': typeof BaseLayoutBrandsBrandIdProductIdIndexRoute
  '/categories/$categoryId/$productId/': typeof BaseLayoutCategoriesCategoryIdProductIdIndexRoute
  '/stores/$storeId/$productId/': typeof BaseLayoutStoresStoreIdProductIdIndexRoute
}
export interface FileRoutesByTo {
  '/store-activate': typeof StoreActivateRoute
  '/profile/addresses': typeof ProfileAddressesRoute
  '/profile/analytics': typeof ProfileAnalyticsRoute
  '/profile/cart': typeof ProfileCartRoute
  '/profile/edit': typeof ProfileEditRoute
  '/profile/favorites': typeof ProfileFavoritesRoute
  '/profile/logout': typeof ProfileLogoutRoute
  '/profile/notifications': typeof ProfileNotificationsRoute
  '/profile/privacy-policy': typeof ProfilePrivacyPolicyRoute
  '/profile/returns': typeof ProfileReturnsRoute
  '/profile/terms-of-use': typeof ProfileTermsOfUseRoute
  '/': typeof BaseLayoutIndexRoute
  '/about-us': typeof AboutUsIndexRoute
  '/checkout': typeof CheckoutIndexRoute
  '/contact-us': typeof ContactUsIndexRoute
  '/my-store': typeof MyStoreIndexRoute
  '/privacy-policy': typeof PrivacyPolicyIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/terms-of-use': typeof TermsOfUseIndexRoute
  '/my-store/$storeId/close': typeof MyStoreStoreIdCloseRoute
  '/my-store/$storeId/intake': typeof MyStoreStoreIdIntakeRoute
  '/my-store/$storeId/orders': typeof MyStoreStoreIdOrdersRoute
  '/my-store/$storeId/privacy-policy': typeof MyStoreStoreIdPrivacyPolicyRoute
  '/my-store/$storeId/receipts': typeof MyStoreStoreIdReceiptsRoute
  '/my-store/$storeId/returns': typeof MyStoreStoreIdReturnsRoute
  '/my-store/$storeId/stock': typeof MyStoreStoreIdStockRoute
  '/my-store/$storeId/store-information': typeof MyStoreStoreIdStoreInformationRoute
  '/my-store/$storeId/terms-of-use': typeof MyStoreStoreIdTermsOfUseRoute
  '/my-store/$storeId/warehouse': typeof MyStoreStoreIdWarehouseRoute
  '/$productId': typeof BaseLayoutProductIdIndexRoute
  '/brands': typeof BaseLayoutBrandsIndexRoute
  '/search': typeof BaseLayoutSearchIndexRoute
  '/stores': typeof BaseLayoutStoresIndexRoute
  '/my-store/$storeId': typeof MyStoreStoreIdIndexRoute
  '/my-store/$storeId/products/add': typeof MyStoreStoreIdProductsAddRoute
  '/brands/$brandId': typeof BaseLayoutBrandsBrandIdIndexRoute
  '/categories/$categoryId': typeof BaseLayoutCategoriesCategoryIdIndexRoute
  '/collections/$collectionId': typeof BaseLayoutCollectionsCollectionIdIndexRoute
  '/stores/$storeId': typeof BaseLayoutStoresStoreIdIndexRoute
  '/my-store/$storeId/products': typeof MyStoreStoreIdProductsIndexRoute
  '/my-store/$storeId/products/edit/$productId': typeof MyStoreStoreIdProductsEditProductIdRoute
  '/brands/$brandId/$productId': typeof BaseLayoutBrandsBrandIdProductIdIndexRoute
  '/categories/$categoryId/$productId': typeof BaseLayoutCategoriesCategoryIdProductIdIndexRoute
  '/stores/$storeId/$productId': typeof BaseLayoutStoresStoreIdProductIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_base-layout': typeof BaseLayoutRouteRouteWithChildren
  '/my-store': typeof MyStoreRouteRouteWithChildren
  '/profile': typeof ProfileRouteRouteWithChildren
  '/store-activate': typeof StoreActivateRoute
  '/my-store/$storeId': typeof MyStoreStoreIdRouteRouteWithChildren
  '/profile/addresses': typeof ProfileAddressesRoute
  '/profile/analytics': typeof ProfileAnalyticsRoute
  '/profile/cart': typeof ProfileCartRoute
  '/profile/edit': typeof ProfileEditRoute
  '/profile/favorites': typeof ProfileFavoritesRoute
  '/profile/logout': typeof ProfileLogoutRoute
  '/profile/notifications': typeof ProfileNotificationsRoute
  '/profile/privacy-policy': typeof ProfilePrivacyPolicyRoute
  '/profile/returns': typeof ProfileReturnsRoute
  '/profile/terms-of-use': typeof ProfileTermsOfUseRoute
  '/_base-layout/': typeof BaseLayoutIndexRoute
  '/about-us/': typeof AboutUsIndexRoute
  '/checkout/': typeof CheckoutIndexRoute
  '/contact-us/': typeof ContactUsIndexRoute
  '/my-store/': typeof MyStoreIndexRoute
  '/privacy-policy/': typeof PrivacyPolicyIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/terms-of-use/': typeof TermsOfUseIndexRoute
  '/my-store/$storeId/close': typeof MyStoreStoreIdCloseRoute
  '/my-store/$storeId/intake': typeof MyStoreStoreIdIntakeRoute
  '/my-store/$storeId/orders': typeof MyStoreStoreIdOrdersRoute
  '/my-store/$storeId/privacy-policy': typeof MyStoreStoreIdPrivacyPolicyRoute
  '/my-store/$storeId/products': typeof MyStoreStoreIdProductsRouteWithChildren
  '/my-store/$storeId/receipts': typeof MyStoreStoreIdReceiptsRoute
  '/my-store/$storeId/returns': typeof MyStoreStoreIdReturnsRoute
  '/my-store/$storeId/stock': typeof MyStoreStoreIdStockRoute
  '/my-store/$storeId/store-information': typeof MyStoreStoreIdStoreInformationRoute
  '/my-store/$storeId/terms-of-use': typeof MyStoreStoreIdTermsOfUseRoute
  '/my-store/$storeId/warehouse': typeof MyStoreStoreIdWarehouseRoute
  '/_base-layout/$productId/': typeof BaseLayoutProductIdIndexRoute
  '/_base-layout/brands/': typeof BaseLayoutBrandsIndexRoute
  '/_base-layout/search/': typeof BaseLayoutSearchIndexRoute
  '/_base-layout/stores/': typeof BaseLayoutStoresIndexRoute
  '/my-store/$storeId/': typeof MyStoreStoreIdIndexRoute
  '/my-store/$storeId/products/add': typeof MyStoreStoreIdProductsAddRoute
  '/_base-layout/brands/$brandId/': typeof BaseLayoutBrandsBrandIdIndexRoute
  '/_base-layout/categories/$categoryId/': typeof BaseLayoutCategoriesCategoryIdIndexRoute
  '/_base-layout/collections/$collectionId/': typeof BaseLayoutCollectionsCollectionIdIndexRoute
  '/_base-layout/stores/$storeId/': typeof BaseLayoutStoresStoreIdIndexRoute
  '/my-store/$storeId/products/': typeof MyStoreStoreIdProductsIndexRoute
  '/my-store/$storeId/products/edit/$productId': typeof MyStoreStoreIdProductsEditProductIdRoute
  '/_base-layout/brands/$brandId/$productId/': typeof BaseLayoutBrandsBrandIdProductIdIndexRoute
  '/_base-layout/categories/$categoryId/$productId/': typeof BaseLayoutCategoriesCategoryIdProductIdIndexRoute
  '/_base-layout/stores/$storeId/$productId/': typeof BaseLayoutStoresStoreIdProductIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/my-store'
    | '/profile'
    | '/store-activate'
    | '/my-store/$storeId'
    | '/profile/addresses'
    | '/profile/analytics'
    | '/profile/cart'
    | '/profile/edit'
    | '/profile/favorites'
    | '/profile/logout'
    | '/profile/notifications'
    | '/profile/privacy-policy'
    | '/profile/returns'
    | '/profile/terms-of-use'
    | '/about-us/'
    | '/checkout/'
    | '/contact-us/'
    | '/my-store/'
    | '/privacy-policy/'
    | '/profile/'
    | '/terms-of-use/'
    | '/my-store/$storeId/close'
    | '/my-store/$storeId/intake'
    | '/my-store/$storeId/orders'
    | '/my-store/$storeId/privacy-policy'
    | '/my-store/$storeId/products'
    | '/my-store/$storeId/receipts'
    | '/my-store/$storeId/returns'
    | '/my-store/$storeId/stock'
    | '/my-store/$storeId/store-information'
    | '/my-store/$storeId/terms-of-use'
    | '/my-store/$storeId/warehouse'
    | '/$productId/'
    | '/brands/'
    | '/search/'
    | '/stores/'
    | '/my-store/$storeId/'
    | '/my-store/$storeId/products/add'
    | '/brands/$brandId/'
    | '/categories/$categoryId/'
    | '/collections/$collectionId/'
    | '/stores/$storeId/'
    | '/my-store/$storeId/products/'
    | '/my-store/$storeId/products/edit/$productId'
    | '/brands/$brandId/$productId/'
    | '/categories/$categoryId/$productId/'
    | '/stores/$storeId/$productId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/store-activate'
    | '/profile/addresses'
    | '/profile/analytics'
    | '/profile/cart'
    | '/profile/edit'
    | '/profile/favorites'
    | '/profile/logout'
    | '/profile/notifications'
    | '/profile/privacy-policy'
    | '/profile/returns'
    | '/profile/terms-of-use'
    | '/'
    | '/about-us'
    | '/checkout'
    | '/contact-us'
    | '/my-store'
    | '/privacy-policy'
    | '/profile'
    | '/terms-of-use'
    | '/my-store/$storeId/close'
    | '/my-store/$storeId/intake'
    | '/my-store/$storeId/orders'
    | '/my-store/$storeId/privacy-policy'
    | '/my-store/$storeId/receipts'
    | '/my-store/$storeId/returns'
    | '/my-store/$storeId/stock'
    | '/my-store/$storeId/store-information'
    | '/my-store/$storeId/terms-of-use'
    | '/my-store/$storeId/warehouse'
    | '/$productId'
    | '/brands'
    | '/search'
    | '/stores'
    | '/my-store/$storeId'
    | '/my-store/$storeId/products/add'
    | '/brands/$brandId'
    | '/categories/$categoryId'
    | '/collections/$collectionId'
    | '/stores/$storeId'
    | '/my-store/$storeId/products'
    | '/my-store/$storeId/products/edit/$productId'
    | '/brands/$brandId/$productId'
    | '/categories/$categoryId/$productId'
    | '/stores/$storeId/$productId'
  id:
    | '__root__'
    | '/_base-layout'
    | '/my-store'
    | '/profile'
    | '/store-activate'
    | '/my-store/$storeId'
    | '/profile/addresses'
    | '/profile/analytics'
    | '/profile/cart'
    | '/profile/edit'
    | '/profile/favorites'
    | '/profile/logout'
    | '/profile/notifications'
    | '/profile/privacy-policy'
    | '/profile/returns'
    | '/profile/terms-of-use'
    | '/_base-layout/'
    | '/about-us/'
    | '/checkout/'
    | '/contact-us/'
    | '/my-store/'
    | '/privacy-policy/'
    | '/profile/'
    | '/terms-of-use/'
    | '/my-store/$storeId/close'
    | '/my-store/$storeId/intake'
    | '/my-store/$storeId/orders'
    | '/my-store/$storeId/privacy-policy'
    | '/my-store/$storeId/products'
    | '/my-store/$storeId/receipts'
    | '/my-store/$storeId/returns'
    | '/my-store/$storeId/stock'
    | '/my-store/$storeId/store-information'
    | '/my-store/$storeId/terms-of-use'
    | '/my-store/$storeId/warehouse'
    | '/_base-layout/$productId/'
    | '/_base-layout/brands/'
    | '/_base-layout/search/'
    | '/_base-layout/stores/'
    | '/my-store/$storeId/'
    | '/my-store/$storeId/products/add'
    | '/_base-layout/brands/$brandId/'
    | '/_base-layout/categories/$categoryId/'
    | '/_base-layout/collections/$collectionId/'
    | '/_base-layout/stores/$storeId/'
    | '/my-store/$storeId/products/'
    | '/my-store/$storeId/products/edit/$productId'
    | '/_base-layout/brands/$brandId/$productId/'
    | '/_base-layout/categories/$categoryId/$productId/'
    | '/_base-layout/stores/$storeId/$productId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  BaseLayoutRouteRoute: typeof BaseLayoutRouteRouteWithChildren
  MyStoreRouteRoute: typeof MyStoreRouteRouteWithChildren
  ProfileRouteRoute: typeof ProfileRouteRouteWithChildren
  StoreActivateRoute: typeof StoreActivateRoute
  AboutUsIndexRoute: typeof AboutUsIndexRoute
  CheckoutIndexRoute: typeof CheckoutIndexRoute
  ContactUsIndexRoute: typeof ContactUsIndexRoute
  PrivacyPolicyIndexRoute: typeof PrivacyPolicyIndexRoute
  TermsOfUseIndexRoute: typeof TermsOfUseIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/store-activate': {
      id: '/store-activate'
      path: '/store-activate'
      fullPath: '/store-activate'
      preLoaderRoute: typeof StoreActivateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-store': {
      id: '/my-store'
      path: '/my-store'
      fullPath: '/my-store'
      preLoaderRoute: typeof MyStoreRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_base-layout': {
      id: '/_base-layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof BaseLayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-of-use/': {
      id: '/terms-of-use/'
      path: '/terms-of-use'
      fullPath: '/terms-of-use/'
      preLoaderRoute: typeof TermsOfUseIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof ProfileRouteRoute
    }
    '/privacy-policy/': {
      id: '/privacy-policy/'
      path: '/privacy-policy'
      fullPath: '/privacy-policy/'
      preLoaderRoute: typeof PrivacyPolicyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-store/': {
      id: '/my-store/'
      path: '/'
      fullPath: '/my-store/'
      preLoaderRoute: typeof MyStoreIndexRouteImport
      parentRoute: typeof MyStoreRouteRoute
    }
    '/contact-us/': {
      id: '/contact-us/'
      path: '/contact-us'
      fullPath: '/contact-us/'
      preLoaderRoute: typeof ContactUsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/': {
      id: '/checkout/'
      path: '/checkout'
      fullPath: '/checkout/'
      preLoaderRoute: typeof CheckoutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-us/': {
      id: '/about-us/'
      path: '/about-us'
      fullPath: '/about-us/'
      preLoaderRoute: typeof AboutUsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_base-layout/': {
      id: '/_base-layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof BaseLayoutIndexRouteImport
      parentRoute: typeof BaseLayoutRouteRoute
    }
    '/profile/terms-of-use': {
      id: '/profile/terms-of-use'
      path: '/terms-of-use'
      fullPath: '/profile/terms-of-use'
      preLoaderRoute: typeof ProfileTermsOfUseRouteImport
      parentRoute: typeof ProfileRouteRoute
    }
    '/profile/returns': {
      id: '/profile/returns'
      path: '/returns'
      fullPath: '/profile/returns'
      preLoaderRoute: typeof ProfileReturnsRouteImport
      parentRoute: typeof ProfileRouteRoute
    }
    '/profile/privacy-policy': {
      id: '/profile/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/profile/privacy-policy'
      preLoaderRoute: typeof ProfilePrivacyPolicyRouteImport
      parentRoute: typeof ProfileRouteRoute
    }
    '/profile/notifications': {
      id: '/profile/notifications'
      path: '/notifications'
      fullPath: '/profile/notifications'
      preLoaderRoute: typeof ProfileNotificationsRouteImport
      parentRoute: typeof ProfileRouteRoute
    }
    '/profile/logout': {
      id: '/profile/logout'
      path: '/logout'
      fullPath: '/profile/logout'
      preLoaderRoute: typeof ProfileLogoutRouteImport
      parentRoute: typeof ProfileRouteRoute
    }
    '/profile/favorites': {
      id: '/profile/favorites'
      path: '/favorites'
      fullPath: '/profile/favorites'
      preLoaderRoute: typeof ProfileFavoritesRouteImport
      parentRoute: typeof ProfileRouteRoute
    }
    '/profile/edit': {
      id: '/profile/edit'
      path: '/edit'
      fullPath: '/profile/edit'
      preLoaderRoute: typeof ProfileEditRouteImport
      parentRoute: typeof ProfileRouteRoute
    }
    '/profile/cart': {
      id: '/profile/cart'
      path: '/cart'
      fullPath: '/profile/cart'
      preLoaderRoute: typeof ProfileCartRouteImport
      parentRoute: typeof ProfileRouteRoute
    }
    '/profile/analytics': {
      id: '/profile/analytics'
      path: '/analytics'
      fullPath: '/profile/analytics'
      preLoaderRoute: typeof ProfileAnalyticsRouteImport
      parentRoute: typeof ProfileRouteRoute
    }
    '/profile/addresses': {
      id: '/profile/addresses'
      path: '/addresses'
      fullPath: '/profile/addresses'
      preLoaderRoute: typeof ProfileAddressesRouteImport
      parentRoute: typeof ProfileRouteRoute
    }
    '/my-store/$storeId': {
      id: '/my-store/$storeId'
      path: '/$storeId'
      fullPath: '/my-store/$storeId'
      preLoaderRoute: typeof MyStoreStoreIdRouteRouteImport
      parentRoute: typeof MyStoreRouteRoute
    }
    '/my-store/$storeId/': {
      id: '/my-store/$storeId/'
      path: '/'
      fullPath: '/my-store/$storeId/'
      preLoaderRoute: typeof MyStoreStoreIdIndexRouteImport
      parentRoute: typeof MyStoreStoreIdRouteRoute
    }
    '/_base-layout/stores/': {
      id: '/_base-layout/stores/'
      path: '/stores'
      fullPath: '/stores/'
      preLoaderRoute: typeof BaseLayoutStoresIndexRouteImport
      parentRoute: typeof BaseLayoutRouteRoute
    }
    '/_base-layout/search/': {
      id: '/_base-layout/search/'
      path: '/search'
      fullPath: '/search/'
      preLoaderRoute: typeof BaseLayoutSearchIndexRouteImport
      parentRoute: typeof BaseLayoutRouteRoute
    }
    '/_base-layout/brands/': {
      id: '/_base-layout/brands/'
      path: '/brands'
      fullPath: '/brands/'
      preLoaderRoute: typeof BaseLayoutBrandsIndexRouteImport
      parentRoute: typeof BaseLayoutRouteRoute
    }
    '/_base-layout/$productId/': {
      id: '/_base-layout/$productId/'
      path: '/$productId'
      fullPath: '/$productId/'
      preLoaderRoute: typeof BaseLayoutProductIdIndexRouteImport
      parentRoute: typeof BaseLayoutRouteRoute
    }
    '/my-store/$storeId/warehouse': {
      id: '/my-store/$storeId/warehouse'
      path: '/warehouse'
      fullPath: '/my-store/$storeId/warehouse'
      preLoaderRoute: typeof MyStoreStoreIdWarehouseRouteImport
      parentRoute: typeof MyStoreStoreIdRouteRoute
    }
    '/my-store/$storeId/terms-of-use': {
      id: '/my-store/$storeId/terms-of-use'
      path: '/terms-of-use'
      fullPath: '/my-store/$storeId/terms-of-use'
      preLoaderRoute: typeof MyStoreStoreIdTermsOfUseRouteImport
      parentRoute: typeof MyStoreStoreIdRouteRoute
    }
    '/my-store/$storeId/store-information': {
      id: '/my-store/$storeId/store-information'
      path: '/store-information'
      fullPath: '/my-store/$storeId/store-information'
      preLoaderRoute: typeof MyStoreStoreIdStoreInformationRouteImport
      parentRoute: typeof MyStoreStoreIdRouteRoute
    }
    '/my-store/$storeId/stock': {
      id: '/my-store/$storeId/stock'
      path: '/stock'
      fullPath: '/my-store/$storeId/stock'
      preLoaderRoute: typeof MyStoreStoreIdStockRouteImport
      parentRoute: typeof MyStoreStoreIdRouteRoute
    }
    '/my-store/$storeId/returns': {
      id: '/my-store/$storeId/returns'
      path: '/returns'
      fullPath: '/my-store/$storeId/returns'
      preLoaderRoute: typeof MyStoreStoreIdReturnsRouteImport
      parentRoute: typeof MyStoreStoreIdRouteRoute
    }
    '/my-store/$storeId/receipts': {
      id: '/my-store/$storeId/receipts'
      path: '/receipts'
      fullPath: '/my-store/$storeId/receipts'
      preLoaderRoute: typeof MyStoreStoreIdReceiptsRouteImport
      parentRoute: typeof MyStoreStoreIdRouteRoute
    }
    '/my-store/$storeId/products': {
      id: '/my-store/$storeId/products'
      path: '/products'
      fullPath: '/my-store/$storeId/products'
      preLoaderRoute: typeof MyStoreStoreIdProductsRouteImport
      parentRoute: typeof MyStoreStoreIdRouteRoute
    }
    '/my-store/$storeId/privacy-policy': {
      id: '/my-store/$storeId/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/my-store/$storeId/privacy-policy'
      preLoaderRoute: typeof MyStoreStoreIdPrivacyPolicyRouteImport
      parentRoute: typeof MyStoreStoreIdRouteRoute
    }
    '/my-store/$storeId/orders': {
      id: '/my-store/$storeId/orders'
      path: '/orders'
      fullPath: '/my-store/$storeId/orders'
      preLoaderRoute: typeof MyStoreStoreIdOrdersRouteImport
      parentRoute: typeof MyStoreStoreIdRouteRoute
    }
    '/my-store/$storeId/intake': {
      id: '/my-store/$storeId/intake'
      path: '/intake'
      fullPath: '/my-store/$storeId/intake'
      preLoaderRoute: typeof MyStoreStoreIdIntakeRouteImport
      parentRoute: typeof MyStoreStoreIdRouteRoute
    }
    '/my-store/$storeId/close': {
      id: '/my-store/$storeId/close'
      path: '/close'
      fullPath: '/my-store/$storeId/close'
      preLoaderRoute: typeof MyStoreStoreIdCloseRouteImport
      parentRoute: typeof MyStoreStoreIdRouteRoute
    }
    '/my-store/$storeId/products/': {
      id: '/my-store/$storeId/products/'
      path: '/'
      fullPath: '/my-store/$storeId/products/'
      preLoaderRoute: typeof MyStoreStoreIdProductsIndexRouteImport
      parentRoute: typeof MyStoreStoreIdProductsRoute
    }
    '/_base-layout/stores/$storeId/': {
      id: '/_base-layout/stores/$storeId/'
      path: '/stores/$storeId'
      fullPath: '/stores/$storeId/'
      preLoaderRoute: typeof BaseLayoutStoresStoreIdIndexRouteImport
      parentRoute: typeof BaseLayoutRouteRoute
    }
    '/_base-layout/collections/$collectionId/': {
      id: '/_base-layout/collections/$collectionId/'
      path: '/collections/$collectionId'
      fullPath: '/collections/$collectionId/'
      preLoaderRoute: typeof BaseLayoutCollectionsCollectionIdIndexRouteImport
      parentRoute: typeof BaseLayoutRouteRoute
    }
    '/_base-layout/categories/$categoryId/': {
      id: '/_base-layout/categories/$categoryId/'
      path: '/categories/$categoryId'
      fullPath: '/categories/$categoryId/'
      preLoaderRoute: typeof BaseLayoutCategoriesCategoryIdIndexRouteImport
      parentRoute: typeof BaseLayoutRouteRoute
    }
    '/_base-layout/brands/$brandId/': {
      id: '/_base-layout/brands/$brandId/'
      path: '/brands/$brandId'
      fullPath: '/brands/$brandId/'
      preLoaderRoute: typeof BaseLayoutBrandsBrandIdIndexRouteImport
      parentRoute: typeof BaseLayoutRouteRoute
    }
    '/my-store/$storeId/products/add': {
      id: '/my-store/$storeId/products/add'
      path: '/add'
      fullPath: '/my-store/$storeId/products/add'
      preLoaderRoute: typeof MyStoreStoreIdProductsAddRouteImport
      parentRoute: typeof MyStoreStoreIdProductsRoute
    }
    '/_base-layout/stores/$storeId/$productId/': {
      id: '/_base-layout/stores/$storeId/$productId/'
      path: '/stores/$storeId/$productId'
      fullPath: '/stores/$storeId/$productId/'
      preLoaderRoute: typeof BaseLayoutStoresStoreIdProductIdIndexRouteImport
      parentRoute: typeof BaseLayoutRouteRoute
    }
    '/_base-layout/categories/$categoryId/$productId/': {
      id: '/_base-layout/categories/$categoryId/$productId/'
      path: '/categories/$categoryId/$productId'
      fullPath: '/categories/$categoryId/$productId/'
      preLoaderRoute: typeof BaseLayoutCategoriesCategoryIdProductIdIndexRouteImport
      parentRoute: typeof BaseLayoutRouteRoute
    }
    '/_base-layout/brands/$brandId/$productId/': {
      id: '/_base-layout/brands/$brandId/$productId/'
      path: '/brands/$brandId/$productId'
      fullPath: '/brands/$brandId/$productId/'
      preLoaderRoute: typeof BaseLayoutBrandsBrandIdProductIdIndexRouteImport
      parentRoute: typeof BaseLayoutRouteRoute
    }
    '/my-store/$storeId/products/edit/$productId': {
      id: '/my-store/$storeId/products/edit/$productId'
      path: '/edit/$productId'
      fullPath: '/my-store/$storeId/products/edit/$productId'
      preLoaderRoute: typeof MyStoreStoreIdProductsEditProductIdRouteImport
      parentRoute: typeof MyStoreStoreIdProductsRoute
    }
  }
}

interface BaseLayoutRouteRouteChildren {
  BaseLayoutIndexRoute: typeof BaseLayoutIndexRoute
  BaseLayoutProductIdIndexRoute: typeof BaseLayoutProductIdIndexRoute
  BaseLayoutBrandsIndexRoute: typeof BaseLayoutBrandsIndexRoute
  BaseLayoutSearchIndexRoute: typeof BaseLayoutSearchIndexRoute
  BaseLayoutStoresIndexRoute: typeof BaseLayoutStoresIndexRoute
  BaseLayoutBrandsBrandIdIndexRoute: typeof BaseLayoutBrandsBrandIdIndexRoute
  BaseLayoutCategoriesCategoryIdIndexRoute: typeof BaseLayoutCategoriesCategoryIdIndexRoute
  BaseLayoutCollectionsCollectionIdIndexRoute: typeof BaseLayoutCollectionsCollectionIdIndexRoute
  BaseLayoutStoresStoreIdIndexRoute: typeof BaseLayoutStoresStoreIdIndexRoute
  BaseLayoutBrandsBrandIdProductIdIndexRoute: typeof BaseLayoutBrandsBrandIdProductIdIndexRoute
  BaseLayoutCategoriesCategoryIdProductIdIndexRoute: typeof BaseLayoutCategoriesCategoryIdProductIdIndexRoute
  BaseLayoutStoresStoreIdProductIdIndexRoute: typeof BaseLayoutStoresStoreIdProductIdIndexRoute
}

const BaseLayoutRouteRouteChildren: BaseLayoutRouteRouteChildren = {
  BaseLayoutIndexRoute: BaseLayoutIndexRoute,
  BaseLayoutProductIdIndexRoute: BaseLayoutProductIdIndexRoute,
  BaseLayoutBrandsIndexRoute: BaseLayoutBrandsIndexRoute,
  BaseLayoutSearchIndexRoute: BaseLayoutSearchIndexRoute,
  BaseLayoutStoresIndexRoute: BaseLayoutStoresIndexRoute,
  BaseLayoutBrandsBrandIdIndexRoute: BaseLayoutBrandsBrandIdIndexRoute,
  BaseLayoutCategoriesCategoryIdIndexRoute:
    BaseLayoutCategoriesCategoryIdIndexRoute,
  BaseLayoutCollectionsCollectionIdIndexRoute:
    BaseLayoutCollectionsCollectionIdIndexRoute,
  BaseLayoutStoresStoreIdIndexRoute: BaseLayoutStoresStoreIdIndexRoute,
  BaseLayoutBrandsBrandIdProductIdIndexRoute:
    BaseLayoutBrandsBrandIdProductIdIndexRoute,
  BaseLayoutCategoriesCategoryIdProductIdIndexRoute:
    BaseLayoutCategoriesCategoryIdProductIdIndexRoute,
  BaseLayoutStoresStoreIdProductIdIndexRoute:
    BaseLayoutStoresStoreIdProductIdIndexRoute,
}

const BaseLayoutRouteRouteWithChildren = BaseLayoutRouteRoute._addFileChildren(
  BaseLayoutRouteRouteChildren,
)

interface MyStoreStoreIdProductsRouteChildren {
  MyStoreStoreIdProductsAddRoute: typeof MyStoreStoreIdProductsAddRoute
  MyStoreStoreIdProductsIndexRoute: typeof MyStoreStoreIdProductsIndexRoute
  MyStoreStoreIdProductsEditProductIdRoute: typeof MyStoreStoreIdProductsEditProductIdRoute
}

const MyStoreStoreIdProductsRouteChildren: MyStoreStoreIdProductsRouteChildren =
  {
    MyStoreStoreIdProductsAddRoute: MyStoreStoreIdProductsAddRoute,
    MyStoreStoreIdProductsIndexRoute: MyStoreStoreIdProductsIndexRoute,
    MyStoreStoreIdProductsEditProductIdRoute:
      MyStoreStoreIdProductsEditProductIdRoute,
  }

const MyStoreStoreIdProductsRouteWithChildren =
  MyStoreStoreIdProductsRoute._addFileChildren(
    MyStoreStoreIdProductsRouteChildren,
  )

interface MyStoreStoreIdRouteRouteChildren {
  MyStoreStoreIdCloseRoute: typeof MyStoreStoreIdCloseRoute
  MyStoreStoreIdIntakeRoute: typeof MyStoreStoreIdIntakeRoute
  MyStoreStoreIdOrdersRoute: typeof MyStoreStoreIdOrdersRoute
  MyStoreStoreIdPrivacyPolicyRoute: typeof MyStoreStoreIdPrivacyPolicyRoute
  MyStoreStoreIdProductsRoute: typeof MyStoreStoreIdProductsRouteWithChildren
  MyStoreStoreIdReceiptsRoute: typeof MyStoreStoreIdReceiptsRoute
  MyStoreStoreIdReturnsRoute: typeof MyStoreStoreIdReturnsRoute
  MyStoreStoreIdStockRoute: typeof MyStoreStoreIdStockRoute
  MyStoreStoreIdStoreInformationRoute: typeof MyStoreStoreIdStoreInformationRoute
  MyStoreStoreIdTermsOfUseRoute: typeof MyStoreStoreIdTermsOfUseRoute
  MyStoreStoreIdWarehouseRoute: typeof MyStoreStoreIdWarehouseRoute
  MyStoreStoreIdIndexRoute: typeof MyStoreStoreIdIndexRoute
}

const MyStoreStoreIdRouteRouteChildren: MyStoreStoreIdRouteRouteChildren = {
  MyStoreStoreIdCloseRoute: MyStoreStoreIdCloseRoute,
  MyStoreStoreIdIntakeRoute: MyStoreStoreIdIntakeRoute,
  MyStoreStoreIdOrdersRoute: MyStoreStoreIdOrdersRoute,
  MyStoreStoreIdPrivacyPolicyRoute: MyStoreStoreIdPrivacyPolicyRoute,
  MyStoreStoreIdProductsRoute: MyStoreStoreIdProductsRouteWithChildren,
  MyStoreStoreIdReceiptsRoute: MyStoreStoreIdReceiptsRoute,
  MyStoreStoreIdReturnsRoute: MyStoreStoreIdReturnsRoute,
  MyStoreStoreIdStockRoute: MyStoreStoreIdStockRoute,
  MyStoreStoreIdStoreInformationRoute: MyStoreStoreIdStoreInformationRoute,
  MyStoreStoreIdTermsOfUseRoute: MyStoreStoreIdTermsOfUseRoute,
  MyStoreStoreIdWarehouseRoute: MyStoreStoreIdWarehouseRoute,
  MyStoreStoreIdIndexRoute: MyStoreStoreIdIndexRoute,
}

const MyStoreStoreIdRouteRouteWithChildren =
  MyStoreStoreIdRouteRoute._addFileChildren(MyStoreStoreIdRouteRouteChildren)

interface MyStoreRouteRouteChildren {
  MyStoreStoreIdRouteRoute: typeof MyStoreStoreIdRouteRouteWithChildren
  MyStoreIndexRoute: typeof MyStoreIndexRoute
}

const MyStoreRouteRouteChildren: MyStoreRouteRouteChildren = {
  MyStoreStoreIdRouteRoute: MyStoreStoreIdRouteRouteWithChildren,
  MyStoreIndexRoute: MyStoreIndexRoute,
}

const MyStoreRouteRouteWithChildren = MyStoreRouteRoute._addFileChildren(
  MyStoreRouteRouteChildren,
)

interface ProfileRouteRouteChildren {
  ProfileAddressesRoute: typeof ProfileAddressesRoute
  ProfileAnalyticsRoute: typeof ProfileAnalyticsRoute
  ProfileCartRoute: typeof ProfileCartRoute
  ProfileEditRoute: typeof ProfileEditRoute
  ProfileFavoritesRoute: typeof ProfileFavoritesRoute
  ProfileLogoutRoute: typeof ProfileLogoutRoute
  ProfileNotificationsRoute: typeof ProfileNotificationsRoute
  ProfilePrivacyPolicyRoute: typeof ProfilePrivacyPolicyRoute
  ProfileReturnsRoute: typeof ProfileReturnsRoute
  ProfileTermsOfUseRoute: typeof ProfileTermsOfUseRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
}

const ProfileRouteRouteChildren: ProfileRouteRouteChildren = {
  ProfileAddressesRoute: ProfileAddressesRoute,
  ProfileAnalyticsRoute: ProfileAnalyticsRoute,
  ProfileCartRoute: ProfileCartRoute,
  ProfileEditRoute: ProfileEditRoute,
  ProfileFavoritesRoute: ProfileFavoritesRoute,
  ProfileLogoutRoute: ProfileLogoutRoute,
  ProfileNotificationsRoute: ProfileNotificationsRoute,
  ProfilePrivacyPolicyRoute: ProfilePrivacyPolicyRoute,
  ProfileReturnsRoute: ProfileReturnsRoute,
  ProfileTermsOfUseRoute: ProfileTermsOfUseRoute,
  ProfileIndexRoute: ProfileIndexRoute,
}

const ProfileRouteRouteWithChildren = ProfileRouteRoute._addFileChildren(
  ProfileRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  BaseLayoutRouteRoute: BaseLayoutRouteRouteWithChildren,
  MyStoreRouteRoute: MyStoreRouteRouteWithChildren,
  ProfileRouteRoute: ProfileRouteRouteWithChildren,
  StoreActivateRoute: StoreActivateRoute,
  AboutUsIndexRoute: AboutUsIndexRoute,
  CheckoutIndexRoute: CheckoutIndexRoute,
  ContactUsIndexRoute: ContactUsIndexRoute,
  PrivacyPolicyIndexRoute: PrivacyPolicyIndexRoute,
  TermsOfUseIndexRoute: TermsOfUseIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
