export const en = {
  meta: {
    title: 'Postshop - Best Products at Low Prices',
  },
  notFound: {
    title: 'Page not found',
    backHome: 'Back to home',
  },
  login: {
    openButton: 'Sign in',
    title: {
      phone: 'Enter your phone number to sign in',
      profile: 'Enter the following details',
      otp: 'Enter the code from the SMS',
    },
    otpSentTo: 'Code sent to {{phone}}',
    codePlaceholder: 'SMS code',
    next: 'Next',
    save: 'Save',
    resend: 'Resend code',
    resendIn: 'Resend code in {{seconds}}s',
    firstName: 'First name',
    lastName: 'Last name',
    disclaimer: 'By continuing you accept the <terms>Terms of Use</terms>',
    errors: {
      general: 'Something went wrong. Please try again.',
      invalidOtp: 'The code is incorrect. Please try again.',
    },
    success: {
      title: 'You are signed in',
      description: 'Your cart, favorites and orders are now available.',
      close: 'Continue',
    },
  },
  services: {
    tiles: {
      stores: 'Stores',
      brands: 'Brands',
      favorites: 'Favorites',
      becomeStore: 'Become a seller',
    },
    adds: {
      title: 'PostShop seller',
      heading: 'Start your business on the Postshop platform',
      freeMonth: 'First month — FREE!',
      description:
        'We provide efficient logistics and comprehensive promotion of your products, helping you quickly enter the market and grow your sales',
      cta: 'Open seller platform',
    },
    phone: {
      title: 'Enter your phone number to sign in',
      termsPrefix: 'By continuing to fill in the data, I accept the',
      termsLink: 'Terms of Use',
      termsSuffix: '',
    },
    tradeType: {
      title: 'Select your trade type',
      individual: 'For individual entrepreneurs',
      legalEntity: 'For legal entities',
    },
    upload: {
      title:
        'Please upload electronic versions of the documents required to access the seller platform',
      individualDocs: [
        'Individual entrepreneur registration certificate',
        'Patent (valid)',
        'Registration certificate',
        'Passport copy',
      ],
      legalEntityDocs: [
        'Company charter (all pages sealed)',
        'Extract from the State Register of Legal Entities',
        'Registration certificate',
        'Statistics certificate (with OKED codes)',
        'Power of attorney or order appointing a director',
      ],
    },
    success: {
      title: 'Successfully submitted!',
      description: 'Your request has been received. We will contact you shortly.',
      close: 'Close',
    },
    loginRequired: {
      login: 'Log in',
      title: 'Sign in required',
      description: 'You need to sign in before applying to become a seller.',
      favoritesDescription: 'To view your favorite products, please sign in first.',
      cartDescription: 'To place an order, please sign in first.',
      close: 'Close',
    },
    next: 'Next',
  },
  dashboard: {
    insights: {
      title: 'Worth fixing',
      subtitle: 'Lists you can act on right now.',
      noRating: 'No ratings yet',
      newReviews_one: '{{count}} new review this month',
      newReviews_other: '{{count}} new reviews this month',
      unsold: 'No sales this month',
      unsoldHint:
        'Most-viewed first: when people look and do not buy, it is usually the price or the photo.',
      returned: 'Returned',
      returnedHint: 'One return is chance, three on one product is a reason to check the batch.',
      returnsCount_one: '{{count}} return',
      returnsCount_other: '{{count}} returns',
    },
    summary: {
      subtitle: 'Totals for the period and the change from the previous one.',
      noBase: 'nothing to compare with',
      revenue: 'Revenue',
      orders: 'Orders',
      averageCheck: 'Average order',
      rejected: 'Rejected',
      period: {
        week: 'Week',
        month: 'Month',
        quarter: '3 months',
      },
    },

    revenue: {
      title: 'Revenue report',
      subtitle: 'Weekly revenue overview',
      currency: 'TMT',
      weekdays: ['Mo', 'Tu', 'We', 'Th', 'Fr', 'Sa', 'Su'],
      orders: 'orders',
      empty: 'No revenue yet this week',
    },
    topProducts: {
      title: 'Best-selling products',
      empty: 'No sales yet',
    },
    notifications: {},
  },
  myStore: {
    notYours: 'This store is not yours',
    notice: {
      closed:
        'The store is closed: customers do not see its products. You can reopen it in the «Close the store» section.',
      pending: 'The store is under review. Products will appear in the catalog once approved.',
      rejected: 'The registration request was rejected. Products are not shown to customers.',
      suspended: 'Registration is suspended. Products are not shown to customers.',
    },
  },
  storeClose: {
    hasOpenWork:
      "The shop can't be closed while it has open orders or unfinished returns. Finish them and try again.",
    closedByStaff:
      'The shop was closed by the platform. Only the platform can reopen it — contact support.',
    title: 'Close the store',
    subtitle:
      'A closed store disappears from the catalog: customers cannot see its products or place orders. Orders already placed must be completed. You can reopen the store here at any time.',
    close: 'Close the store',
    closed: 'The store is closed',
    reopenTitle: 'Reopen the store',
    reopenSubtitle:
      'The store is closed and customers cannot see its products. Once reopened, the products appear in the catalog again.',
    reopen: 'Reopen the store',
    reopened: 'The store is open',
    failed: 'Could not change the store state',
    confirmTitle: 'Close the store?',
    confirmText: 'Products will stop being shown to customers. This can be undone.',
    confirm: 'Close',
    cancel: 'Cancel',
    deleteTitle: 'Delete the store',
    deleteText:
      'A store cannot be deleted on your own: orders and documents remain attached to it. Contact support and we will delete it after a review.',
    deleteLink: 'Contact support',
  },
  upload: {
    processing: 'Preparing photos…',
    notImage: 'This is not an image — choose a JPG, PNG or WebP photo',
    unreadable: 'The image could not be processed — choose another file (JPG, PNG or WebP)',
  },

  productBarcode: {
    vendorLabel: 'Manufacturer barcode',
    vendorPlaceholder: 'For example, 4600000000000',
    vendorHint: 'Optional. 8, 12, 13 or 14 digits from the package',
    invalid: 'A manufacturer barcode has 8, 12, 13 or 14 digits',
    duplicate: 'Your shop already has a product with this manufacturer barcode',
    platformLabel: 'Postshop barcode',
    platformHint: 'Assigned automatically and cannot be changed',
  },

  errors: {
    uploadInterrupted: 'The upload was interrupted — the connection is too weak. Please try again',
    network: 'No connection to the server. Check your network and try again',
    server: 'Server error. Please try again later',
    badRequest: 'Could not complete the action',
    unauthorized: 'Please sign in again',
    forbidden: 'Not enough permissions',
    notFound: 'Not found',
    conflict: 'Already exists',
    tooLarge: 'The file is too large',
    validation: 'Check the fields you filled in',
    tooManyRequests: 'Too many attempts. Please wait a moment',
    unknown: 'Something went wrong',
  },
  common: {
    cancel: 'Cancel',
  },
  cartClear: {
    title: 'Clear the cart?',
    text: 'All products will be removed from the cart. This cannot be undone.',
    confirm: 'Clear',
  },
  contacts: {
    phoneNote: 'Main',
    office: 'Turkmenpost head office',
    city: 'Ashgabat, Turkmenistan',
  },
  withdrawal: {
    action: 'Take back',
    title: 'Take goods back from the warehouse',
    free: 'Free at the warehouse: {{count}}',
    quantity: 'How much to take',
    comment: 'Comment for the warehouse',
    commentPlaceholder: 'E.g. when and who will pick it up',
    notice:
      'Postshop warehouse will review the request. Goods held by open orders cannot be taken.',
    send: 'Send request',
    sent: 'Withdrawal request sent',
    quantityInvalid: 'Enter a quantity from 1 to {{count}}',
    hint: 'Requests to take your goods back from the Postshop warehouse. To send one, press “Take back” next to a product in “Stock at the warehouse”.',
    empty: 'No withdrawal requests',
    number: 'Request #{{id}}',
    cancel: 'Withdraw',
    cancelled: 'Request withdrawn',
    status: {
      pending: 'Under review',
      completed: 'Goods handed over',
      rejected: 'Rejected',
      cancelled: 'Withdrawn',
    },
  },
  stockHistory: {
    open: 'History',
    title: 'Stock history',
    empty: 'No movements yet',
    op: {
      income: 'Income',
      sold: 'Sale',
      return_from_customer: 'Customer return',
      return_to_supplier: 'Return to supplier',
      return_to_shop: 'Returned to you from the warehouse',
      write_off: 'Write-off (defect, loss)',
      correction: 'Recount',
    },
  },
  stock: {
    title: 'Stock',
    subtitle: 'How much is available for sale. What open orders already hold is subtracted.',
    notTracked:
      'The platform warehouse is turned off: an FBO store’s stock does not limit purchases right now. To keep stock yourself, ask an administrator to switch the store to FBS.',
    fboTitle: 'Warehouse stock',
    fboSubtitle:
      'Your goods are stored in Postshop warehouses. Stock grows when the platform accepts an intake document and decreases with every completed order.',
    available: 'Available: {{count}}',
    addOperation: 'In stock: {{count}}',
    operationTitle: 'Change the stock',
    operations: {
      income: 'Incoming',
      return_to_supplier: 'Return to supplier',
      set: 'Set the stock',
    },
    breakdown: 'On shelf: {{shelf}} · in orders: {{reserved}} · available: {{available}}',
    operationsHint: {
      income: 'Goods arrived at the warehouse and are available for sale',
      return_to_supplier: 'Goods leave the warehouse back to the supplier',
      set: 'Counted the shelf — enter how much is on it. Do not count packed orders. We record the difference.',
    },
    quantityPlaceholder: 'Quantity',
    quantityRequired: 'Enter a quantity greater than zero',
    save: 'Record',
    saved: 'Movement recorded',
    setSaved: 'Stock updated',
    amountPlaceholder: 'How many are available now',
    amountRequired: 'Enter a number: zero or more',
    edit: 'Change',
    fbsOnly:
      'This section is for FBS shops: they store goods themselves. FBO shop stock is under “Warehouse”.',
  },
  intake: {
    title: 'Goods intake',
    subtitle:
      'Goods arrived — record how many. Stock grows by that amount and the product can be bought right away.',
    fbsOnly:
      'This section is for FBS shops: they receive goods themselves. An FBO shop ships goods to the Postshop warehouse — see “Warehouse”.',
    accept: 'Receive',
    modalTitle: 'Goods intake',
    saved: 'Goods received',
  },
  warehouse: {
    title: 'Warehouse',
    subtitle: 'Your goods at the Postshop warehouse: how much is there and your shipments to it.',
    fboOnly:
      'This section is for FBO shops: their goods are stored at the Postshop warehouse. An FBS shop keeps its own records in “Stock” and “Goods intake”.',
    tabStock: 'Stock at warehouse',
    tabShipments: 'Shipments to warehouse',
    tabWithdrawals: 'Withdrawals',
  },
  receipts: {
    title: 'Shipments to warehouse',
    subtitle:
      'Sending goods to a Postshop warehouse. The platform confirms intake — after that the goods appear in stock.',
    notTracked:
      'Warehouse intake is only for FBO stores: the platform stores their goods. An FBS store keeps its own stock on the “Stock” page.',
    create: 'New document',
    created: 'Document created',
    empty: 'No intake documents yet',
    number: 'Document #{{id}}',
    status: {
      draft: 'Draft',
      confirmed: 'Accepted',
      cancelled: 'Cancelled',
    },
    addItem: 'Add product',
    itemAdded: 'Product added',
    selectWarehouse: 'Select a warehouse',
    selectProduct: 'Select a product',
    productRequired: 'Select a product',
    addItemsFirst: 'Add products — the platform will not accept an empty document',
    awaitingConfirmation: 'Awaiting platform confirmation',
    cancel: 'Cancel',
    cancelled: 'Document cancelled',
    cancelTitle: 'Cancel the document?',
    cancelText: 'The document leaves the workflow. Its goods will not arrive at the warehouse.',
  },
  storeSidebar: {
    closeStore: 'Close the store',
    analytics: 'Analytics',
    dashboard: 'Statistics',
    orders: 'My orders',
    products: 'My products',
    storeInformation: 'Store information',
    agreement: 'Terms of use',
    privacyPolicy: 'Privacy policy',
    favorites: 'Favorites',
    cart: 'My cart',
    becomeSeller: 'Become a seller',
    logout: 'Log out',
  },
  logoutPage: {
    title: 'Log out',
    subtitle: 'Are you sure you want to log out?',
    confirm: 'Log out',
    cancel: 'Cancel',
  },
  orders: {
    orderNumber: 'Order #{{id}}',
    storeRejected: 'The shop declined',
    partiallyRejected: 'Part of the order was rejected by the store',
    months: {
      1: 'January',
      2: 'February',
      3: 'March',
      4: 'April',
      5: 'May',
      6: 'June',
      7: 'July',
      8: 'August',
      9: 'September',
      10: 'October',
      11: 'November',
      12: 'December',
    },
    status: {
      done: 'Completed',
      cancelled: 'Cancelled',
      pending: 'Pending',
      in_progress: 'In progress',
      attention: 'Attention',
    },
    detail: {
      cancelOrder: 'Cancel the order',
      unnamedStore: 'Unnamed store',
      cancelSuccessTitle: 'Order cancelled',
      cancelSuccessDescription: 'The administrator has been notified.',
      cancelConfirmSubtitle: 'Are you sure you want to cancel this order?',
      cancelConfirmButton: 'Yes, cancel',
      productPrice: 'Product price',
      total: 'Total:',
      discount: 'Discount:',
      deliveryPrice: 'Delivery price',
      rejectedStores: 'Declined by shops',
      deliveryPending: 'The operator sets the price on confirmation',
      cancelReason: 'Reason for cancelling',
      cancelReasonPlaceholder: 'Optional — helps the shop understand what happened',
      grandTotal: 'Grand total:',
      pieces: 'pieces',
    },
    empty: 'You have no orders yet',
  },
  orderStatus: {
    pending: 'Awaiting confirmation',
    approved: 'Accepted',
    ready_to_take: 'Packed',
    ready_to_deliver: 'Ready to receive',
    completed: 'Completed',
    rejected: 'Cancelled',
    pickup: {
      ready_to_deliver: 'Waiting at the pickup point',
      completed: 'Picked up',
    },
    delivery: {
      ready_to_deliver: 'Out for delivery',
      completed: 'Delivered',
    },
  },
  storeWarehouse: {
    title: 'Warehouse type: {{type}}',
    fbs: {
      meaning: 'The goods are stored with you.',
      intake: 'Goods arrived — record them in <link>"Goods intake"</link>',
      stock: 'Recounted a shelf — correct it in <link>"Stock"</link>',
      orders:
        '<link>New order</link> — accept it and mark it "Packed", the operator will pick it up',
      returns: 'Return — once the item is back, mark it in <link>"Returns"</link>',
    },
    fbo: {
      meaning: 'The goods are stored at the Postshop warehouse.',
      shipments: 'Send goods to the warehouse: <link>"Warehouse" → "Shipments to warehouse"</link>',
      stock: 'Stock at the warehouse — <link>"Warehouse" → "Stock at warehouse"</link>',
      orders:
        '<link>Orders</link> are packed and handed over by the Postshop warehouse — nothing is required from you',
      returns: '<link>Returns</link> are received by the Postshop warehouse',
    },
    changeNote: 'Only Postshop can change the warehouse type — write to <link>support</link>.',
  },
  storeOrders: {
    empty: 'No orders yet',
    customer: 'Customer',
    noPhone: 'No phone provided',
    noName: 'No name provided',
    comment: 'Comment',
    approve: 'Approve',
    reject: 'Reject',
    fboNote: 'The Postshop warehouse is fulfilling this order — nothing is required from you.',
    notApproved: 'Order actions will be available once an operator accepts the order.',
    markPacked: 'Packed',
    rejectConfirmTitle: 'Reject order',
    rejectReason: 'Reason',
    rejectReasonPlaceholder: 'The customer will see it — e.g. “out of stock”',
    rejectConfirmSubtitle: 'Are you sure you want to reject this order?',
    rejectConfirmButton: 'Yes, reject',
    status: {
      pending: 'New — accept the order',
      approved: 'Accepted — pack it',
      ready_to_take: 'Packed — hand it to the operator',
      rejected: 'You rejected it',
    },
  },
  header: {
    storeClosed: 'closed',
    searchPlaceholder: 'Search for products, sections or stores',
    login: 'Login',
    selectCity: 'Select city',
    selectLanguage: 'Select language',
    myStore: 'My Store',
    selectStore: 'Select store',
    fastSearch: 'Fast search',
    foundProducts: 'Found products',
    foundBrands: 'Found brands',
    foundStores: 'Found stores',
    viewAll: 'View all',
    searching: 'Searching...',
  },

  breadcrumbs: {
    home: 'Home',
    stores: 'Stores',
    brands: 'Brands',
  },

  search: {
    title: 'Search',
    resultsFor: 'Search results for "{{query}}"',
    noResults: 'No results found',
    categories: 'Categories',
    brands: 'Brands',
    stores: 'Stores',
  },

  store: {
    sort: 'Sort',
    filter: 'Filter',
    about: 'About store',
    phone: 'Phone number',
    address: 'Address',
    description: 'Store description',
  },

  doc: {
    individual: {
      registration: 'Individual entrepreneur registration certificate',
      patent: 'Patent (valid)',
      certificate: 'Registration certificate',
      passport: 'Passport copy',
    },
    legal: {
      charter: 'Company charter (all pages certified with seal)',
      extract: 'Extract from state register',
      certificate: 'Registration certificate',
      statistics: 'Statistics certificate (with OKED codes)',
      powerOfAttorney: 'Power of attorney or director appointment order',
    },
  },

  nav: {
    next: 'Next',
  },

  storeInformation: {
    title: 'Store information',
    subtitle: 'View and edit your store details.',
  },
  storeActivate: {
    goToStore: 'Go to the store cabinet',
    underReview:
      'The store registration request has already been submitted and is awaiting review. Products will appear in the catalog once approved.',
    title: 'Activate your store',
    subtitle:
      'Complete all the steps below to fully open your store. Your account will not be active without filling in the required fields.',
    completedSteps: 'Completed steps',
    todos: {
      warehouseType: 'Warehouse type',
      warehouseTypeDesc: 'Select a warehouse type for storing your products',
      warehouseTypeLocked: '{{type}} · changed by an administrator',
      name: 'Store name and desctiption',
      nameDesc: 'Enter the store name that customers will see',
      addresses: 'Addresses',
      addressesDesc: 'Enter your store addresses',
      phoneNumbers: 'Phone numbers',
      phoneNumbersDesc: 'Enter phone numbers for customers to contact you',
      color: 'Color',
      colorDesc: 'Choose the primary color of your store',
      city: 'City',
      cityDesc: 'Select the city where your store is located',
      logo: 'Logo',
      logoDesc: 'Upload your store logo (will be converted to .webp)',
    },
    cityModal: {
      title: 'Select your city',
      save: 'Save',
      saving: 'Saving...',
    },
    nameModal: {
      title: 'Store name and description',
      nameLabel: 'Store name',
      descriptionLabel: 'Description',
      save: 'Save',
      saving: 'Saving...',
      nameError: 'Enter store name',
      descriptionError: 'Enter description',
    },
    addressesModal: {
      title: 'Store addresses',
      label: 'Address',
      placeholder: 'Enter address',
      add: 'Add address',
      save: 'Save',
      saving: 'Saving...',
      error: 'Enter at least one address',
    },
    phoneNumbersModal: {
      title: 'Phone numbers',
      label: 'Phone number',
      placeholder: 'Enter phone number',
      add: 'Add phone number',
      save: 'Save',
      saving: 'Saving...',
      error: 'Enter at least one phone number',
    },
    logoModal: {
      title: 'Store logo',
      upload: 'Click to upload logo',
      save: 'Save',
      saving: 'Saving...',
      error: 'Select a logo image',
    },
    warehouseTypeModal: {
      title: 'Select your warehouse type',
      save: 'Save',
      saving: 'Saving...',
      fbs: {
        name: 'FBS (Fulfilment by Seller)',
        description: "Products are stored and shipped from the seller's warehouse",
      },
      fbo: {
        name: 'FBO (Fulfilment by Operator)',
        description: 'Products are stored and shipped from the marketplace warehouse',
      },
    },
    colorModal: {
      title: 'Store color',
      selected: 'Selected color',
      bgColor: 'Background color',
      textColor: 'Text color',
      customLabel: 'Custom color',
      save: 'Save',
      saving: 'Saving...',
      contrastUnreadable: 'This text is invisible on this background. Pick another colour to save.',
    },
  },

  filter: {
    title: 'Filters',
    category: 'Category',
    brand: 'Brand',
    brandSearch: 'Search brand',
    store: 'Store',
    storeSearch: 'Search store',
    sort: 'Sort',
    priceRange: 'Price range',
    priceFrom: 'from',
    priceTo: 'to',
    showAll: 'Show all',
    showLess: 'Show less',
    clearAll: 'Clear filters',
  },

  sort: {
    expensiveToCheap: 'Expensive to cheap',
    cheapToExpensive: 'Cheap to expensive',
    newProducts: 'New products',
    discount: 'Discounts',
    bestSelling: 'Best selling',
  },

  category: {
    all: 'All',
    male: 'Men',
    female: 'Women',
  },

  footer: {
    aboutUs: 'About us',
    contact: 'Contact',
    termsOfUse: 'Terms of use',
    privacyPolicy: 'Privacy policy',
    profile: 'Profile',
    myOrders: 'My orders',
    favorites: 'Favorites',
    brands: 'Brands',
    stores: 'Stores',
    becomeSeller: 'Become a seller',
    scrollToTop: 'Top',
    followUs: 'Follow us on social media:',
    home: 'Home',
    categories: 'Categories',
    cart: 'My cart',
    orders: 'Orders',
  },

  product: {
    unavailable: 'Product unavailable',
    unavailableHint: 'It may have been withdrawn from sale or no longer exists.',
    inStock: 'In stock: {{count}}',
    details: 'Details',
    info: 'Product information',
    similar: 'Similar products',
    youMayLike: 'You may also like',
    addToCart: 'Add to cart',
  },

  products: {
    stock: 'In warehouse: {{count}}',
    outOfStock: 'Out of stock',
    hidden: 'Not for sale',
    declined: 'Rejected',
    hide: 'Remove from sale',
    show: 'Return to sale',
    blockedByStaff: 'Taken off sale by the platform',
    addButton: 'Add product',
    empty: 'No products',
    inReview: 'In review',
  },

  favorites: {
    empty: 'You have no favorite products',
  },

  addProduct: {
    descriptionTooLong:
      'The full text shows on the product page; lists display the beginning with an ellipsis.',
    backToProducts: 'Products',
    title: 'Add product',
    images: 'Images',
    imagesMax: '(max 5)',
    imagesAdd: 'Add',
    name: 'Name',
    namePlaceholder: 'Product name',
    description: 'Description',
    descriptionPlaceholder: 'Product description',
    category: 'Category',
    categoryPlaceholder: 'Select',
    categoryModalTitle: 'Select category',
    brand: 'Brand',
    brandPlaceholder: 'Select',
    brandModalTitle: 'Select brand',
    price: 'Price',
    pricePlaceholder: '0',
    currency: 'Currency',
    currencyPlaceholder: 'Select',
    hashtag: 'Hashtag',
    hashtagPlaceholder: '#hashtag',
    measureUnit: 'Measure unit',
    measureUnitPlaceholder: 'Select',
    discountType: 'Discount type',
    discountTypeNone: 'None',
    discountTypePercentage: 'Percentage (%)',
    discountTypeFixed: 'Fixed (TMT)',
    discount: 'Discount',
    discountPlaceholder: '0',
    submit: 'Add product',
    submitting: 'Loading...',
    error: 'Please fill in all required fields',
    moderationTitle: 'Product sent for moderation',
    moderationDescription:
      'Our operators will review your product and it will be available to customers after approval.',
  },

  editProduct: {
    descriptionTooLong:
      'The full text shows on the product page; lists display the beginning with an ellipsis.',
    backToProducts: 'Products',
    title: 'Edit product',
    images: 'Images',
    imagesMax: '(max 5)',
    imagesAdd: 'Add',
    name: 'Name',
    namePlaceholder: 'Product name',
    description: 'Description',
    descriptionPlaceholder: 'Product description',
    category: 'Category',
    categoryPlaceholder: 'Select',
    categoryModalTitle: 'Select category',
    brand: 'Brand',
    brandPlaceholder: 'Select',
    brandModalTitle: 'Select brand',
    price: 'Price',
    pricePlaceholder: '0',
    currency: 'Currency',
    currencyPlaceholder: 'Select',
    hashtag: 'Hashtag',
    hashtagPlaceholder: '#hashtag',
    measureUnit: 'Measure unit',
    measureUnitPlaceholder: 'Select',
    discountType: 'Discount type',
    discountTypeNone: 'None',
    discountTypePercentage: 'Percentage (%)',
    discountTypeFixed: 'Fixed (TMT)',
    discount: 'Discount',
    discountPlaceholder: '0',
    submit: 'Save changes',
    submitting: 'Loading...',
    error: 'Please fill in all required fields',
    moderationTitle: 'Product sent for moderation',
    moderationDescription:
      'Our operators will review your product and it will be available to customers after approval.',
    saved: 'Changes saved',
  },

  checkout: {
    deliveryLater:
      'The platform will tell you the delivery cost when it confirms the order — the total above is preliminary.',
    placeOrder: 'Place order',
    addressRequired: 'Enter a delivery address.',
    pickupPointRequired: 'Choose a pickup point.',
    confirmOrder: 'Confirm order',
    clearCart: 'Clear cart',
    orderError: 'Failed to place order. Please try again.',
    insufficientStock: '"{{product}}" is out of stock. Please reduce its quantity in your cart.',
    insufficientStockGeneric:
      'One of the items in your cart is out of stock. Please check the quantities.',
    deliveryMethod: 'Delivery method',
    pickup: 'Pickup point',
    delivery: 'Delivery',
    addressPlaceholder: 'Ashgabat, Magtymguly avenue, building 1',
    noPickupPoints:
      'There are no pickup points in your city yet — choose delivery or change the city',
    showOnMap: 'Show on map',
    pickupPointsOnMap: 'Pickup points',
    mapUnavailable: 'The map is unavailable: no map server is configured.',
    paymentType: 'Payment type',
    cash: 'Cash',
    card: 'Terminal',
    cashAndCard: 'Cash and Terminal',
    comment: 'Comment',
    commentPlaceholder: 'Leave a note for your order...',
    success: {
      title: 'Order placed successfully!',
      description: 'Your order has been accepted. We will start processing it shortly.',
      goHome: 'Go to home',
      showOrder: 'Show order',
    },
  },

  analytics: {
    title: 'Store analytics',

    subtitle: 'Summary across all your stores',

    period: 'Period: {{from}} — {{to}}',

    totalRevenue: 'Revenue for the period',

    totalOrders: 'Orders',

    shopsCount: 'Stores',

    byShop: 'By store',

    topProducts: 'Best-selling products',

    ordersShort: '{{count}} ord.',

    soldShort: '{{count}} pcs',

    noShops: 'You have no stores yet',

    noShopsHint: 'Analytics appears once your store application is approved.',
  },

  cart: {
    notEnough: 'Not enough of this item in stock',
    decrease: 'Decrease quantity',
    increase: 'Increase quantity',
    unavailable: 'This product is no longer for sale',
    unavailableName: 'Product unavailable',
    remove: 'Remove',
    hasUnavailable: 'Remove the unavailable products to place the order',
    hasStockProblem:
      'Some products are not in stock in the quantity you chose — remove them or lower the quantity to place the order',
    onlyLeft: 'Only {{count}} left in stock — lower the quantity',

    restore: 'Undo',
    goToCart: 'To cart',
    title: 'My cart',
    empty: 'Your cart is empty',
    emptyHint: 'Time to fill it up!',
    confirm: 'Confirm cart',
    totalPrice: 'Total price',
    productPrice: 'Product price',
    total: 'Total:',
    discount: 'Discount:',
    grandTotal: 'Grand total:',
    aboutDelivery: 'About delivery',
    noDeliveryInfo: 'Delivery information is not available',
  },

  aboutUs: {
    title: 'About Us',
    subtitle:
      'Postshop is the e-commerce platform of the "Turkmenpost" postal service company, bringing quality products to your door.',
    historyTitle: 'Our story',
    historyDescription:
      "Turkmenpost's development dates back to its founding on April 7, 1993. Today, the company is focused on organizing its operations to meet modern requirements. On January 26, 1993, the Turkmenpost Postal Service Company was admitted to the Universal Postal Union, becoming the state's official postal operator. This has enabled it, within a very short time, to send and receive mail to and from more than 190 countries around the world.",
    foundedLabel: 'Founded',
    foundedValue: 'April 7, 1993',
    upuLabel: 'UPU membership',
    upuValue: 'Since January 26, 1993',
    countriesLabel: 'Postal reach',
    countriesValue: '190+ countries',
    servicesTitle: 'Our services',
    service1: 'Sending and receiving mail',
    service2: 'Subscribing to newspapers and magazines',
    service3: 'Postal money order payments',
    service4: 'Wholesale and retail trade',
    service5: 'Payment for communication services',
    service6: 'Payment for public and utility services',
    service7: '"Door to door" delivery service',
    service8: 'E-commerce services',
    postshopTitle: 'About Postshop',
    postshopDescription1:
      'Postshop is the e-commerce platform created by the "Turkmenpost" postal service company, letting you buy everything you need without leaving home — from the latest tech to modern clothing.',
    postshopDescription2:
      "Postshop brings together a seamless shopping and delivery experience with a wide range of high-quality products from leading brands, backed by competitive pricing and fast, reliable delivery straight to the buyer's door.",
    benefit1: 'Comfortable shopping without extra effort',
    benefit2: 'Carefully curated selection',
    benefit3: 'Fast delivery across the country',
    benefit4: 'Reliable service with customer care',
  },

  contactUs: {
    title: 'Contact with us',
    name: 'Name',
    phone: 'Phone number',
    message: 'Your message',
    submit: 'Submit',
    infoTitle: 'Contact information',
    phoneLabel: 'Phone (Mon-Sun 9:00-19:00)',
    email: 'Email',
    address: 'Address',
    showOnMap: 'Show on map',
    error: 'Please fill in all fields',
    submitting: 'Sending...',
    successTitle: 'Message sent!',
    successDescription: 'We will contact you shortly.',
  },

  links: {
    back: 'Back',
    backToHome: 'Back to home',
  },

  collections: {
    notFound: 'This collection does not exist',
    empty: 'This collection has no available products yet',
    seeAll: 'See all',
  },

  categories: {
    empty: 'No categories yet',
  },

  profileEdit: {
    title: 'Edit Profile',
    name: 'Name',
    surname: 'Surname',
    nameRequired: 'Name is required',
    surnameRequired: 'Surname is required',
    save: 'Save',
    saving: 'Saving...',
    cancel: 'Cancel',
    saved: 'Profile details saved',
  },

  notifications: {
    title: 'Notifications',
    empty: 'No notifications yet',
    markAll: 'Mark all read',
    seeAll: 'See all',
    dismiss: 'Dismiss notification',
    loadMore: 'Show more',
    deliveryDetail:
      'Delivery {{delivery}} TMT, total {{total}} TMT. Disagree? Cancel the order before it is packed.',
    kind: {
      order_created: 'New order — open it: if the item is with you, accept and pack it',
      order_cancelled: 'An order was cancelled',
      product_blocked: 'The platform took a product off sale',
      receipt_confirmed: 'Receipt confirmed, stock updated',
      product_out_of_stock: 'A product has run out — replenish it or take it off sale',
      review_received: 'New review of your product',
      return_received:
        'Return approved — the item is coming back to you. Once you receive it, mark it in "Returns"',
      shop_blocked: 'The shop was closed by the platform',
      product_approved: 'Product passed the review',
      product_declined: 'Product did not pass the review',
      shop_approved: 'Shop application approved',
      shop_rejected: 'Shop application rejected',
      order_status: 'Order status changed',
      order_shop_rejected: 'A store rejected part of your order',
      order_approved_delivery: 'Order confirmed — delivery price set',
      withdrawal_completed: 'The warehouse handed over your goods',
      withdrawal_rejected: 'The warehouse rejected your withdrawal request',
      review_approved: 'Your review is published',
      review_rejected: 'Your review was rejected',
      return_approved: 'Return approved',
      return_rejected: 'Return declined',
      return_completed: 'Your return was received and closed',
    },
  },

  storeReturns: {
    title: 'Returns',
    subtitle:
      'Returns for your store products. Postshop makes the decision; when an approved return reaches you, mark it here.',
    fboWarehouse: 'The Postshop warehouse will receive this return',
    receiveRestock: 'Received — back on sale',
    receiveDefective: 'Received — defective',
    defectiveTitle: 'Did the item come back defective?',
    defectiveText:
      'The return will be marked as received, but the item will not go back on sale — stock stays the same.',
    defectiveConfirm: 'Yes, defective',
    restocked: 'Received, back on sale',
    defective: 'Received, defective',
    receivedSaved: 'Return marked as received',
  },
  returns: {
    periodOver: 'Return period is over',
    hintUntil:
      'Not right? Press “Return” next to the item — until {{date}}. Postshop will review the request',
    amount: 'Refund: {{amount}} TMT',
    title: 'My returns',
    subtitle: 'Return requests and the decisions on them.',
    empty: 'No return requests yet',
    unknownProduct: 'Product removed',
    quantityShort: 'to return: {{count}}',
    fromOrder: 'order #{{id}}',
    cancel: 'Withdraw',
    cancelled: 'Request withdrawn',
    cancelTitle: 'Withdraw the request?',
    cancelText: 'It will disappear from the list. You can file a new one for this purchase again.',
    action: 'Return',
    hint: 'Item didn\'t suit you? Press "Return" next to it — Postshop will review the request',
    createTitle: 'Return request',
    purchased: 'purchased: {{count}}',
    quantity: 'How many you return',
    reason: 'Reason for return',
    reasonPlaceholder: 'What is wrong with the item',
    reasonRequired: 'Describe the reason for the return',
    quantityRequired: 'Enter the quantity',
    tooMany: 'You cannot return more than purchased: {{count}}',
    notice: 'The platform will review the request. You will get the decision in notifications.',
    send: 'Send request',
    sending: 'Sending...',
    sent: 'Return request sent',
    notAllowed: 'A return for this purchase is already in progress or not possible',
    awaitingItem:
      'Return approved. Bring the item to any Postshop pickup point — you will be notified when it is received.',
    receivedOn: 'Item received {{date}}',
    status: {
      received: 'Return completed',
      pending: 'Return under review',
      approved: 'Return approved',
      rejected: 'Return declined',
    },
  },

  reviews: {
    title: 'Reviews',
    none: 'No reviews yet. The first one can come from someone who buys this product.',
    count_one: '{{count}} review',
    count_other: '{{count}} reviews',
    leaveTitle: 'Leave a review',
    ratingRequired: 'Pick a rating',
    textPlaceholder: 'What you liked and what you did not (optional)',
    moderationNotice: 'The review appears on the page after it is checked.',
    send: 'Send',
    sending: 'Sending...',
    sent: 'Review sent for checking',
    onlyAfterPurchase: 'You can review this product once an order with it is completed.',
    yoursPending: 'Your review is being checked',
    yoursRejected: 'Your review was rejected',
    anonymous: 'Customer',
    rate: 'Rate',
    rateTitle: 'Rate the product',
    alreadyRated: 'Already rated',
  },

  addresses: {
    title: 'My addresses',
    subtitle: 'A saved address can be picked at checkout instead of typing it again.',
    add: 'Add address',
    editTitle: 'Edit address',
    edit: 'Edit',
    delete: 'Delete',
    save: 'Save',
    name: 'Label',
    namePlaceholder: 'Home, Work',
    address: 'Address',
    addressPlaceholder: 'City, street, building, flat',
    titleRequired: 'Enter a label',
    addressRequired: 'Enter an address',
    defaultBadge: 'Default',
    makeDefault: 'Make default',
    empty: 'No saved addresses yet',
    created: 'Address added',
    saved: 'Address saved',
    deleted: 'Address deleted',
    deleteTitle: 'Delete this address?',
    deleteText: 'It will disappear from the list. Existing orders stay unchanged.',
    chooseSaved: 'Choose an address',
    newAddress: 'Another address',
    saveThis: 'Save this address',
    saveThisName: 'Label for this address',
  },

  passwordChange: {
    title: 'Password',
    titleFirst: 'Set a password',
    subtitle: 'Enter your current password to change it — this keeps your account safe.',
    subtitleFirst: 'You sign in with an SMS code. A password lets you sign in with a username.',
    current: 'Current password',
    new: 'New password',
    repeat: 'Repeat new password',
    save: 'Change password',
    currentRequired: 'Enter your current password',
    currentWrong: 'Current password is incorrect',
    sameAsCurrent: 'The new password must differ from the current one',
    tooShort: 'Password must be at least {{count}} characters',
    mismatch: 'Passwords do not match',
    changed: 'Password changed',
    created: 'Password set',
  },

  phoneChange: {
    title: 'Phone number',
    current: 'Current number: {{phone}}',
    noneYet: 'No number set',
    newPhone: 'New number',
    hint: 'The code goes to the new number — that is how we confirm it is yours.',
    sendCode: 'Send code',
    sending: 'Sending...',
    codeSent: 'Code sent',
    codeSentTo: 'Code sent to {{phone}}',
    confirm: 'Confirm',
    confirming: 'Checking...',
    changed: 'Number changed',
    wrongCode: 'Invalid or expired code',
    unavailable: 'This number is already in use or is your current one',
    tooOften: 'A code can be requested once a minute',
    phoneIncomplete: 'Enter the full number',
  },

  termsOfUse: {
    title: 'Terms of Use',
    lastUpdated: 'Last updated: May 20, 2026',
    sections: {
      general: {
        title: '1. General Provisions',
        p1: 'These Terms of Use ("Terms") govern your access to and use of the PostShop marketplace platform, including the website, mobile applications, and all related services (collectively, the "Platform").',
        p2: 'By registering an account, browsing, or making purchases on the Platform, you agree to be bound by these Terms. If you do not agree, please discontinue use of the Platform.',
        p3: 'PostShop reserves the right to update these Terms at any time. Continued use of the Platform after changes constitutes acceptance of the revised Terms.',
      },
      accounts: {
        title: '2. User Accounts',
        p1: 'To place orders or access certain features, you must create an account by providing a valid phone number. You are responsible for maintaining the security of your account credentials.',
        p2: 'You must provide accurate and up-to-date personal information. PostShop may suspend or terminate accounts with false or incomplete information.',
        p3: 'You are responsible for all activity that occurs under your account. Notify PostShop immediately if you suspect unauthorized access.',
      },
      orders: {
        title: '3. Orders and Payments',
        p1: 'All product prices are displayed in Turkmen manat (TMT) and include applicable taxes unless otherwise stated. Prices are set by individual sellers and may change without prior notice.',
        p2: 'An order is considered confirmed once you receive an order confirmation. PostShop reserves the right to cancel orders due to pricing errors, product unavailability, or suspected fraud.',
        p3: 'Payment can be made by cash, bank card terminal, or a combination of both upon delivery or at the pickup point. All payment obligations must be fulfilled at the time of receipt.',
      },
      delivery: {
        title: '4. Delivery and Pickup Points',
        p1: 'Products can be received at a pickup point or delivered to a specified address. Delivery availability and timeframes may vary by region and product.',
        p2: 'PostShop partners with Turkmenpost for delivery services. While we strive to meet estimated delivery times, delays may occur due to circumstances beyond our control.',
        p3: 'Upon delivery, you are responsible for inspecting the products. Any damage or discrepancies must be reported within 24 hours of receipt.',
      },
      sellers: {
        title: '5. Sellers and Products',
        p1: 'PostShop serves as a marketplace connecting buyers with independent sellers. Each seller is responsible for the accuracy of product descriptions, pricing, and availability.',
        p2: 'PostShop does not manufacture, store, or directly sell products unless explicitly stated. Product quality, warranties, and compliance are the responsibility of the respective seller.',
        p3: 'If you encounter issues with a product or seller, contact PostShop support. We will mediate disputes and may take action against sellers who violate platform policies.',
      },
      returns: {
        title: '6. Returns and Refunds',
        p1: "Return and refund policies are subject to the individual seller's terms and applicable consumer protection laws of Turkmenistan.",
        p2: 'Products may be returned if they are defective, damaged during delivery, or significantly different from the description. Return requests must be submitted within 14 days of receipt.',
        p3: 'Refunds are processed using the original payment method. Processing times may vary depending on the payment provider.',
      },
      intellectual: {
        title: '7. Intellectual Property',
        p1: 'All content on the Platform, including logos, designs, text, graphics, and software, is the property of PostShop or its licensors and is protected by intellectual property laws.',
        p2: 'You may not copy, reproduce, distribute, or create derivative works from any content on the Platform without prior written consent from PostShop.',
      },
      liability: {
        title: '8. Limitation of Liability',
        p1: 'PostShop provides the Platform "as is" and does not guarantee uninterrupted, error-free, or secure access. We are not liable for any indirect, incidental, or consequential damages arising from your use of the Platform.',
        p2: 'PostShop is not responsible for the actions of sellers, the quality of products, or losses resulting from transactions between buyers and sellers on the Platform.',
      },
      privacy: {
        title: '9. Privacy and Data Protection',
        p1: 'Your personal data is collected and processed in accordance with our Privacy Policy. By using the Platform, you consent to data collection as described therein.',
        p2: 'PostShop implements appropriate technical and organizational measures to protect your personal data from unauthorized access, alteration, or disclosure.',
      },
      contact: {
        title: '10. Contact Information',
        p1: 'For questions, complaints, or suggestions regarding these Terms, please contact us:',
        phoneLabel: 'Phone:',
        emailLabel: 'Email:',
        addressLabel: 'Address:',
      },
    },
  },

  privacyPolicy: {
    title: 'Privacy Policy',
    lastUpdated: 'Last updated: May 20, 2026',
    sections: {
      intro: {
        title: '1. Introduction',
        p1: 'PostShop ("we", "us", or "our") is committed to protecting the privacy of our users. This Privacy Policy explains how we collect, use, store, and protect your personal data when you use the PostShop marketplace platform, including the website and mobile applications (the "Platform").',
        p2: 'By using the Platform, you consent to the practices described in this Privacy Policy. We encourage you to read it carefully before providing any personal information.',
      },
      dataCollected: {
        title: '2. Data We Collect',
        p1: 'Account information: When you register, we collect your phone number, first name, and last name.',
        p2: 'Order information: When you place an order, we collect your delivery address, payment method preference, and order history.',
        p3: 'Device and usage data: We automatically collect information about your device (type, operating system, browser), IP address, pages visited, and interaction patterns to improve the Platform.',
        p4: 'Seller information: If you register as a seller, we additionally collect business registration documents, tax identification data, and banking details as required by law.',
      },
      howWeUse: {
        title: '3. How We Use Your Data',
        p1: 'To create and manage your account on the Platform.',
        p2: 'To process and fulfill your orders, including delivery coordination with Turkmenpost.',
        p3: 'To communicate with you about orders, promotions, and Platform updates.',
        p4: 'To improve the Platform, analyze usage patterns, and develop new features.',
        p5: 'To prevent fraud, enforce our Terms of Use, and comply with legal obligations.',
      },
      sharing: {
        title: '4. Data Sharing',
        p1: 'With sellers: We share your name, delivery address, and phone number with sellers to fulfill your orders.',
        p2: 'With delivery partners: We share delivery details with Turkmenpost and other logistics partners to complete deliveries.',
        p3: 'With service providers: We may share data with third-party providers who assist us with hosting, analytics, and customer support, under strict confidentiality agreements.',
        p4: 'We do not sell your personal data to third parties. We may disclose data if required by law or to protect the rights, safety, or property of PostShop and its users.',
      },
      cookies: {
        title: '5. Cookies and Tracking',
        p1: 'The Platform uses cookies and similar technologies to remember your preferences, maintain your session, and analyze traffic. You can manage cookie settings in your browser, but disabling cookies may limit certain Platform features.',
        p2: 'We use local storage to keep you signed in and to store your language and region preferences.',
      },
      security: {
        title: '6. Data Security',
        p1: 'We implement industry-standard security measures, including encryption, secure servers, and access controls, to protect your personal data from unauthorized access, alteration, or disclosure.',
        p2: 'While we take reasonable precautions, no method of electronic transmission or storage is completely secure. We cannot guarantee absolute security of your data.',
      },
      retention: {
        title: '7. Data Retention',
        p1: 'We retain your personal data for as long as your account is active or as needed to provide you with our services. Order history is retained for legal and accounting purposes.',
        p2: 'Upon account deletion, your personal data will be removed within 30 days, except where retention is required by law or for legitimate business purposes such as fraud prevention.',
      },
      rights: {
        title: '8. Your Rights',
        p1: 'Access: You can view and update your personal information in your account settings at any time.',
        p2: 'Correction: You may request correction of inaccurate or incomplete data by contacting our support team.',
        p3: 'Deletion: You may delete your account through the Platform settings. This will remove your personal data, subject to legal retention requirements.',
        p4: 'Portability: You may request a copy of your personal data in a structured, commonly used format by contacting us.',
      },
      children: {
        title: '9. Children',
        p1: 'The Platform is not intended for use by children under the age of 16. We do not knowingly collect personal data from children. If we learn that we have collected data from a child, we will delete it promptly.',
      },
      changes: {
        title: '10. Changes to This Policy',
        p1: 'We may update this Privacy Policy from time to time. Changes will be posted on this page with an updated revision date.',
        p2: 'Continued use of the Platform after changes are posted constitutes acceptance of the revised Privacy Policy. For significant changes, we will notify you via the Platform or by other means.',
      },
      contact: {
        title: '11. Contact Us',
        p1: 'If you have questions, concerns, or requests regarding this Privacy Policy or your personal data, please contact us:',
        phoneLabel: 'Phone:',
        emailLabel: 'Email:',
        addressLabel: 'Address:',
      },
    },
  },
}
