export const tk = {
  meta: {
    title: 'Postshop - Arzan bahadan iň gowy harytlar',
  },
  notFound: {
    title: 'Sahypa tapylmady',
    backHome: 'Baş sahypa',
  },
  login: {
    openButton: 'Girmek',
    title: {
      phone: 'Içine girmek üçin telefon belgiňizi giriziň',
      profile: 'Aşakdaky maglumatlary giriziň',
      otp: 'SMS-däki kody giriziň',
    },
    otpSentTo: 'Kod {{phone}} belgä ugradyldy',
    codePlaceholder: 'SMS kody',
    next: 'Indiki',
    save: 'Ýatda sakla',
    resend: 'Kody täzeden ugrat',
    resendIn: 'Täzeden ugrat {{seconds}} s-den soň',
    firstName: 'Ady',
    lastName: 'Familiýasy',
    disclaimer:
      'Maglumatlary doldurup dowam etmek bilen <terms>Ulanyş kadalaryny</terms> kabul edýärin',
    errors: {
      general: 'Ýalňyşlyk ýüze çykdy. Täzeden synanyşyň.',
      invalidOtp: 'Kod nädogry. Täzeden synanyşyň.',
    },
    success: {
      title: 'Hasabyňyza girdiňiz',
      description: 'Indi sebet, halanlar we sargytlar elýeterli.',
      close: 'Dowam etmek',
    },
  },
  services: {
    tiles: {
      stores: 'Dukanlar',
      brands: 'Brendler',
      favorites: 'Halanlarym',
      becomeStore: 'Satyjy bolmak',
    },
    adds: {
      title: 'PostShop satyjy',
      heading: 'Postshop platformasynda öz işiňize başlaň',
      freeMonth: 'Birinji aý — MUGT!',
      description:
        'Biz harytlaryňyzyň netijeli logistikasyny we toplumlaýyn mahabatlandyrylmagyny üpjün edip, bazara çalt çykmaga we söwdaňyzy artdyrmaga kömek edýäris',
      cta: 'Satyjy platformasyny açmak',
    },
    phone: {
      title: 'Içine girmek üçin telefon belgiňizi giriziň',
      termsPrefix: 'Maglumatlary doldurup dowam etmek bilen',
      termsLink: 'Ulanyş düzgünlerini',
      termsSuffix: 'kabul edýärin',
    },
    tradeType: {
      title: 'Söwdaňyzyň görnüşini saýlaň',
      individual: 'Şahsy telekeçiler üçin',
      legalEntity: 'Ýuridiki şahslar üçin',
    },
    upload: {
      title:
        'Satyjy platformasyna girmek üçin gerekli resminamalaryň elektron görnüşini ýüklemegiňizi Sizden haýyş edýäris',
      individualDocs: [
        'Hususy telekeçi hökmünde döwlet belligine alnandygy baradaky şahadatnamanyň nusgasy',
        'Fiziki şahsyň salgyt töleýji hökmünde hasaba goýlandygy hakynda şahadatnamanyň nusgasy',
        'Hususy telekeçiler tarapyndan girdeji salgydynyň bellenen ululygynyň tölenendigine şaýatlyk edýän Tasssyknamanyň nusgasy',
        'Pasportyň nusgasy',
      ],
      legalEntityDocs: [
        'Tertipnamanyň nusgasyy (ähli sahypalary, möhür bilen tassyklanan)',
        'Türkmenistanyň ýuridik şahslarynyň ýeke-täk döwlet sanawyndan göçürmäniň nusgasy',
        'Ýuridik şahs döwlet tarapyndan bellige alnandygy hakynda şahadatnama',
        'Hojalyk subýektleriniň eýe bolan statistik kodlary barada maglumat haty',
        'Direktory bellemek baradaky buýruk ýa-da ynanç haty',
      ],
    },
    success: {
      title: 'Üstünlikli iberildi!',
      description: 'Siziň ýüzlenmäňiz kabul edildi. Biz siz bilen gysga wagtda habarlaşarys.',
      close: 'Ýapmak',
    },
    loginRequired: {
      login: 'Girmek',
      title: 'Ulgama girmek talap edilýär',
      description: 'Satyjy bolmak üçin ýüzlenme ibermek üçin ilki ulgama giriň.',
      favoritesDescription: 'Halanan harytlaryňyzy görmek üçin ilki ulgama giriň.',
      cartDescription: 'Sargyt bermek üçin ilki ulgama giriň.',
      close: 'Ýapmak',
    },
    next: 'Indiki',
  },
  dashboard: {
    insights: {
      title: 'Düzetmäge degýän zatlar',
      subtitle: 'Şu wagt edip boljak işleriň sanawy.',
      noRating: 'Baha ýok',
      newReviews_one: 'Aýda {{count}} täze syn',
      newReviews_other: 'Aýda {{count}} täze syn',
      unsold: 'Aýyň dowamynda satylmady',
      unsoldHint: 'Ýokarda köp görülip, satylmaýanlar: köplenç bahasy ýa suraty sebäp.',
      returned: 'Yzyna gaýtarylan',
      returnedHint: 'Bir gaýtarma tötänlik, bir haryda üç sanysy — tapgyry barlamaga sebäp.',
      returnsCount_one: '{{count}} gaýtarma',
      returnsCount_other: '{{count}} gaýtarma',
    },
    summary: {
      subtitle: 'Döwür boýunça jemler we öňkä görä üýtgeýşi.',
      noBase: 'deňeşdirer ýaly zat ýok',
      revenue: 'Girdeji',
      orders: 'Sargytlar',
      averageCheck: 'Ortaça sargyt',
      rejected: 'Ret edilen',
      period: {
        week: 'Hepde',
        month: 'Aý',
        quarter: '3 aý',
      },
    },

    revenue: {
      title: 'Girdejiler barada hasabat',
      subtitle: 'Hepdelik girdeji syn',
      currency: 'TMT',
      weekdays: ['Du', 'Si', 'Ça', 'Pe', 'An', 'Se', 'Ýe'],
      orders: 'sargyt',
      empty: 'Bu hepde entek girdeji ýok',
    },
    topProducts: {
      title: 'Iň köp satylan harytlar',
      empty: 'Entek satuw ýok',
    },
    notifications: {},
  },
  myStore: {
    notYours: 'Bu siziň dükanyňyz däl',
    notice: {
      closed:
        'Dükan ýapyk: harytlary alyjylar görmeýär. «Dükany ýapmak» bölüminde gaýtadan açyp bilersiňiz.',
      pending: 'Dükan barlagda. Harytlar tassyklanandan soň katalogda görkeziler.',
      rejected: 'Bellige alyş arzasy ret edildi. Harytlar alyjylara görkezilmeýär.',
      suspended: 'Bellige alyş wagtlaýyn togtadyldy. Harytlar alyjylara görkezilmeýär.',
    },
  },
  storeClose: {
    hasOpenWork:
      'Açyk sargytlar ýa-da tamamlanmadyk gaýtarmalar bar wagty dükany ýapyp bolmaýar. Olary tamamlaň we täzeden synanyşyň.',
    closedByStaff:
      'Dükan platforma tarapyndan ýapyldy. Ony diňe platforma açyp biler — goldaw gullugyna ýazyň.',
    title: 'Dükany ýapmak',
    subtitle:
      'Ýapyk dükan katalogdan aýrylýar: alyjylar harytlary görmeýär we sargyt edip bilmeýär. Öň edilen sargytlary tamamlamaly. Dükany islendik wagt şu ýerde gaýtadan açyp bilersiňiz.',
    close: 'Dükany ýapmak',
    closed: 'Dükan ýapyldy',
    reopenTitle: 'Dükany açmak',
    reopenSubtitle:
      'Dükan ýapyk, alyjylar harytlary görmeýär. Açylandan soň harytlar katalogda gaýtadan görkeziler.',
    reopen: 'Dükany açmak',
    reopened: 'Dükan açyldy',
    failed: 'Dükanyň ýagdaýyny üýtgetmek başartmady',
    confirmTitle: 'Dükany ýapmalymy?',
    confirmText: 'Harytlar alyjylara görkezilmegini bes eder. Bu hereketi yzyna almak bolýar.',
    confirm: 'Ýapmak',
    cancel: 'Ýatyrmak',
    deleteTitle: 'Dükany pozmak',
    deleteText:
      'Dükany özbaşdak pozmak bolmaýar: oňa sargytlar we resminamalar bagly. Goldaw gullugyna ýazyň — barlagdan soň pozarys.',
    deleteLink: 'Goldawa ýazmak',
  },
  upload: {
    processing: 'Suratlar taýýarlanýar…',
    notImage: 'Bu surat däl — JPG, PNG ýa-da WebP görnüşli surat saýlaň',
    unreadable: 'Suraty işläp bolmady — başga faýl saýlaň (JPG, PNG ýa-da WebP)',
  },

  productBarcode: {
    vendorLabel: 'Öndürijiniň ştrih-kody',
    vendorPlaceholder: 'Mysal üçin, 4600000000000',
    vendorHint: 'Hökmany däl. Gaplamadaky 8, 12, 13 ýa-da 14 san',
    invalid: 'Öndürijiniň ştrih-kody 8, 12, 13 ýa-da 14 sandan ybarat',
    duplicate: 'Dükanyňyzda bu ştrih-kodly haryt eýýäm bar',
    platformLabel: 'Postshop ştrih-kody',
    platformHint: 'Awtomatik berilýär, üýtgedip bolmaýar',
  },

  errors: {
    uploadInterrupted: 'Ýüklemek kesildi — aragatnaşyk gaty gowşak. Täzeden synanyşyň',
    network: 'Serwer bilen aragatnaşyk ýok. Birikmäni barlaň we gaýtadan synanyşyň',
    server: 'Serwerde ýalňyşlyk. Soňra synanyşyň',
    badRequest: 'Ýerine ýetirmek başartmady',
    unauthorized: 'Täzeden girmeli',
    forbidden: 'Ygtyýar ýeterlik däl',
    notFound: 'Tapylmady',
    conflict: 'Eýýäm bar',
    tooLarge: 'Faýl gaty uly',
    validation: 'Doldurylan meýdanlary barlaň',
    tooManyRequests: 'Örän köp synanyşyk. Biraz garaşyň',
    unknown: 'Bir zat ýalňyş gitdi',
  },
  common: {
    cancel: 'Ýatyrmak',
  },
  cartClear: {
    title: 'Sebedi boşatmalymy?',
    text: 'Ähli harytlar sebetden aýrylar. Bu hereketi yzyna almak bolmaýar.',
    confirm: 'Boşatmak',
  },
  contacts: {
    phoneNote: 'Esasy',
    office: 'Türkmenpoçtanyň baş edarasy',
    city: 'Aşgabat, Türkmenistan',
  },
  withdrawal: {
    action: 'Alyp git',
    title: 'Harydy ammardan alyp gitmek',
    free: 'Ammarda boş: {{count}}',
    quantity: 'Näçesini almaly',
    comment: 'Ammar üçin teswir',
    commentPlaceholder: 'Meselem, haçan we kim alyp gider',
    notice: 'Arza Postshop ammary seredýär. Açyk sargytlaryň saklaýan harydyny alyp bolmaýar.',
    send: 'Arzany ugrat',
    sent: 'Çykarmak arzasy ugradyldy',
    quantityInvalid: '1-den {{count}} çenli mukdar giriziň',
    hint: 'Harydyňyzy Postshop ammaryndan çykarmak arzalary. Täzesini bermek üçin «Ammardaky galyndylarda» harydyň ýanyndaky «Alyp git» düwmesine basyň.',
    empty: 'Çykarmak arzasy ýok',
    number: 'Arza №{{id}}',
    cancel: 'Yzyna al',
    cancelled: 'Arza yzyna alyndy',
    status: {
      pending: 'Seredilýär',
      completed: 'Haryt berildi',
      rejected: 'Ret edildi',
      cancelled: 'Yzyna alyndy',
    },
  },
  stockHistory: {
    open: 'Taryh',
    title: 'Hereketleriň taryhy',
    empty: 'Entek hereket ýok',
    op: {
      income: 'Girdeji',
      sold: 'Satuw',
      return_from_customer: 'Alyjydan gaýtarma',
      return_to_supplier: 'Üpjün edijä gaýtarma',
      return_to_shop: 'Ammardan size gaýtarma',
      write_off: 'Hasapdan aýyrma (kemçilik, ýitgi)',
      correction: 'Gaýtadan sanamak',
    },
  },
  stock: {
    title: 'Galyndylar',
    subtitle: 'Satuwa näçe haryt elýeterli. Açyk sargytlaryň eýeleýäni aýrylýar.',
    notTracked:
      'Platformanyň ammary öçürildi: FBO dükanynyň galyndysy häzir satyn almagy çäklendirmeýär. Galyndylary özüňiz alyp barmak üçin administratordan dükany FBS-e geçirmegini haýyş ediň.',
    fboTitle: 'Ammardaky galyndylar',
    fboSubtitle:
      'Harytlaryňyz Postshop ammarlarynda saklanýar. Galyndy platforma kabul ediş resminamasyny kabul edende köpelýär we her tamamlanan sargyt bilen azalýar.',
    available: 'Elýeterli: {{count}}',
    addOperation: 'Galyndy: {{count}}',
    operationTitle: 'Galyndyny üýtgetmek',
    operations: {
      income: 'Girdeji',
      return_to_supplier: 'Üpjün edijä yzyna',
      set: 'Galyndyny görkeziň',
    },
    breakdown: 'Tekjede: {{shelf}} · sargytlarda: {{reserved}} · elýeterli: {{available}}',
    alreadyEquals: 'Galyndy eýýäm şeýle — hiç zat ýazylmady',
    operationsHint: {
      income: 'Haryt ammara geldi we satuwa elýeterli',
      return_to_supplier: 'Haryt ammardan üpjün edijä gaýdýar',
      set: 'Tekjäni sanadyňyz — onda näçe haryt bardygyny ýazyň. Ýygnalan sargytlary sanamaň. Tapawudy özümiz ýazarys.',
    },
    quantityPlaceholder: 'Mukdary',
    quantityRequired: 'Nolýdan uly mukdar giriziň',
    save: 'Ýazmak',
    saved: 'Hereket ýazyldy',
    setSaved: 'Galyndy täzelendi',
    amountPlaceholder: 'Häzir näçe elýeterli',
    amountRequired: 'San görkeziň: nol ýa-da köp',
    edit: 'Üýtgetmek',
    fbsOnly:
      'Bu bölüm FBS dükanlary üçin: olar harydy özleri saklaýar. FBO dükanyň galyndylary «Ammar» bölüminde.',
  },
  intake: {
    title: 'Haryt kabul etmek',
    subtitle:
      'Haryt geldi — näçe gelendigini belläň. Galyndy şonça artar we haryt derrew satyn alnyp bilner.',
    fbsOnly:
      'Bu bölüm FBS dükanlary üçin: olar harydy özleri kabul edýär. FBO dükany harydy Postshop ammaryna ugradýar — «Ammar» bölüminde.',
    accept: 'Kabul etmek',
    modalTitle: 'Haryt kabul etmek',
    saved: 'Haryt kabul edildi',
  },
  warehouse: {
    title: 'Ammar',
    subtitle: 'Postshop ammaryndaky harydyňyz: onda näçe bar we ammara ugradyş resminamalary.',
    fboOnly:
      'Bu bölüm FBO dükanlary üçin: olaryň harydy Postshop ammarynda saklanýar. FBS dükany hasaby özi alyp barýar — «Galyndylar» we «Haryt kabul etmek» bölümlerinde.',
    tabStock: 'Ammardaky galyndylar',
    tabShipments: 'Ammara ugratmak',
    tabWithdrawals: 'Ammardan çykarmak',
  },
  receipts: {
    title: 'Ammara ugratmak',
    subtitle:
      'Harydy Postshop ammaryna ibermek. Kabul edilişi platforma tassyklaýar — şondan soň haryt galynda görkeziler.',
    notTracked:
      'Ammara kabul ediş diňe FBO dükanlary üçin gerek: olaryň harytlaryny platforma saklaýar. FBS dükany galyndylary özi «Galyndylar» sahypasynda alyp barýar.',
    create: 'Täze resminama',
    created: 'Resminama döredildi',
    empty: 'Kabul ediş resminamalary ýok',
    number: 'Resminama №{{id}}',
    status: {
      draft: 'Taslama',
      confirmed: 'Kabul edildi',
      cancelled: 'Ýatyryldy',
    },
    addItem: 'Haryt goşmak',
    itemAdded: 'Haryt goşuldy',
    selectWarehouse: 'Ammary saýlaň',
    selectProduct: 'Haryt saýlaň',
    productRequired: 'Haryt saýlaň',
    addItemsFirst: 'Haryt goşuň — boş resminamany platforma kabul etmez',
    awaitingConfirmation: 'Platformanyň tassyklamasyna garaşýar',
    cancel: 'Ýatyrmak',
    cancelled: 'Resminama ýatyryldy',
    cancelTitle: 'Resminama ýatyrylsynmy?',
    cancelText: 'Resminama işden çykar. Ondaky harytlar ammara gelmez.',
  },
  storeSidebar: {
    closeStore: 'Dükany ýapmak',
    analytics: 'Analitika',
    dashboard: 'Statistika',
    orders: 'Sargytlarym',
    products: 'Harytlarym',
    storeInformation: 'Dükan maglumatlary',
    agreement: 'Ulanyş kadalary',
    privacyPolicy: 'Gizlinlik syýasaty',
    favorites: 'Halanlarym',
    cart: 'Sebedim',
    becomeSeller: 'Satyjy bolmak',
    logout: 'Ulgamdan çykmak',
  },
  logoutPage: {
    title: 'Ulgamdan çykmak',
    subtitle: 'Ulgamdan çykmak isleýärsiňizmi?',
    confirm: 'Çykmak',
    cancel: 'Ýatyr',
  },
  orders: {
    orderNumber: 'Sargyt #{{id}}',
    storeRejected: 'Dükan ret etdi',
    partiallyRejected: 'Sargydyň bir bölegini dükan ret etdi',
    months: {
      1: 'Ýanwar',
      2: 'Fewral',
      3: 'Mart',
      4: 'Aprel',
      5: 'Maý',
      6: 'Iýun',
      7: 'Iýul',
      8: 'Awgust',
      9: 'Sentýabr',
      10: 'Oktýabr',
      11: 'Noýabr',
      12: 'Dekabr',
    },
    status: {
      done: 'Taýýar',
      cancelled: 'Ýatyryldy',
      pending: 'Garaşylýar',
      in_progress: 'Taýýarlanýar',
      attention: 'Üns bermek',
    },
    detail: {
      cancelOrder: 'Sargydy ýatyrmak',
      unnamedStore: 'Atsyz dükan',
      cancelSuccessTitle: 'Sargyt ýatyryldy',
      cancelSuccessDescription: 'Administrator ýatyrylandygy barada habarly edildi.',
      cancelConfirmSubtitle: 'Bu sargydy ýatyrmagy isleýärsiňizmi?',
      cancelConfirmButton: 'Hawa, ýatyr',
      productPrice: 'Harytlaryň bahasy',
      total: 'Jemi:',
      discount: 'Arzanladyş:',
      deliveryPrice: 'Eltip bermegiň bahasy',
      rejectedStores: 'Dükanlaryň ret edeni',
      deliveryPending: 'Bahasyny operator tassyklanda belleýär',
      cancelReason: 'Ýatyrmagyň sebäbi',
      cancelTooLate:
        'Sargyt eýýäm ýygnaldy, ýolda ýa-da tamamlandy — ony ýatyryp bolmaýar. Ýagdaýy täzelendi.',
      cancelReasonPlaceholder: 'Hökmany däl — dükan näme bolandygyna düşüner',
      grandTotal: 'Umumy jemi:',
      pieces: 'sany',
    },
    empty: 'Sargytlaryňyz ýok',
  },
  orderStatus: {
    pending: 'Tassyklanmagyna garaşýar',
    approved: 'Kabul edildi',
    ready_to_take: 'Ýygnaldy',
    ready_to_deliver: 'Almaga taýýar',
    completed: 'Tamamlandy',
    rejected: 'Ýatyryldy',
    pickup: {
      ready_to_deliver: 'Bermek nokadynda garaşýar',
      completed: 'Alyndy',
    },
    delivery: {
      ready_to_deliver: 'Eltip bermäge tabşyryldy',
      completed: 'Eltip berildi',
    },
  },
  storeWarehouse: {
    title: 'Ammar görnüşi: {{type}}',
    fbs: {
      meaning: 'Haryt sizde saklanýar.',
      intake: 'Haryt geldi — <link>«Haryt kabul etmek»</link> bölüminde belläň',
      stock: 'Tekjäni täzeden sanadyňyz — <link>«Galyndylar»</link> bölüminde düzediň',
      orders:
        '<link>Täze sargyt</link> — kabul ediň we «Ýygnaldy» diýip belläň, operator ony alyp gider',
      returns: 'Gaýtarma — haryt yzyna gelende, <link>«Yzyna gaýtarmalar»</link> bölüminde belläň',
    },
    fbo: {
      meaning: 'Haryt Postshop ammarynda saklanýar.',
      shipments: 'Harydy ammara ugradyň: <link>«Ammar» → «Ammara ugratmak»</link>',
      stock: 'Ammardaky galyndylar — <link>«Ammar» → «Ammardaky galyndylar»</link>',
      orders:
        '<link>Sargytlary</link> Postshop ammary ýygnaýar we berýär — sizden hiç zat talap edilmeýär',
      returns: '<link>Gaýtarmalary</link> Postshop ammary kabul edýär',
    },
    changeNote: 'Ammar görnüşini diňe Postshop üýtgedýär — <link>goldaw gullugyna</link> ýazyň.',
  },
  storeOrders: {
    empty: 'Sargytlar ýok',
    customer: 'Alyjy',
    noPhone: 'Telefon belgi görkezilmedi',
    noName: 'Ady görkezilmedi',
    comment: 'Teswir',
    approve: 'Kabul etmek',
    reject: 'Ret etmek',
    fboNote: 'Sargydy Postshop ammary ýygnaýar — sizden hiç zat talap edilmeýär.',
    notApproved:
      'Operator sargydy kabul edenden soň, sargyt bilen baglanyşykly hereketler elýeterli bolar.',
    markPacked: 'Ýygnaldy',
    rejectConfirmTitle: 'Sargydy ret etmek',
    rejectReason: 'Ret etmegiň sebäbi',
    rejectReasonPlaceholder: 'Ony alyjy görer — meselem, «ýok»',
    rejectConfirmSubtitle: 'Bu sargydy ret etmek isleýärsiňizmi?',
    rejectConfirmButton: 'Hawa, ret etmek',
    status: {
      pending: 'Täze — sargydy kabul ediň',
      approved: 'Kabul edildi — ýygnaň',
      ready_to_take: 'Ýygnaldy — operatora tabşyryň',
      rejected: 'Siz ret etdiňiz',
    },
  },
  header: {
    storeClosed: 'ýapyk',
    searchPlaceholder: 'Harydyňyzy, bölümiňizi ýa-da dükäny giriziň',
    login: 'Girmek',
    selectCity: 'Şäheriňizi saýlaň',
    selectLanguage: 'Dili saýlaň',
    myStore: 'Menin dükanym',
    selectStore: 'Dükany saýlaň',
    fastSearch: 'Çalt gözleg',
    foundProducts: 'Tapylan harytlar',
    foundBrands: 'Tapylan brendler',
    foundStores: 'Tapylan dükanlar',
    viewAll: 'Hemmesini görmek',
    searching: 'Gözlenýär...',
  },

  breadcrumbs: {
    home: 'Esasy sahypa',
    stores: 'Dükanlar',
    brands: 'Brendler',
  },

  search: {
    title: 'Gözleg',
    resultsFor: '"{{query}}" boýunça gözleg netijeleri',
    noResults: 'Hiç zat tapylmady',
    categories: 'Kategoriýalar',
    brands: 'Brendler',
    stores: 'Dükanlar',
  },

  store: {
    sort: 'Sortlamak',
    filter: 'Filtrlemek',
    about: 'Dükan barada',
    phone: 'Telefon belgisi',
    address: 'Salgy',
    description: 'Dükanyň beýany',
  },

  doc: {
    individual: {
      registration: 'Şahsy telekeçini hasaba alyş şahadatnamasy',
      patent: 'Patent (hereket edýän)',
      certificate: 'Hasaba alyş şahadatnamasy',
      passport: 'Pasportyň nusgasy',
    },
    legal: {
      charter: 'Kärhananyň düzgünnamasy (ähli sahypalary möhür bilen tassyklanan)',
      extract: 'ÝGÝHR-dan göçürme',
      certificate: 'Hasaba alyş şahadatnamasy',
      statistics: 'Statistika baradaky kepilnama (OKED kodlary bilen)',
      powerOfAttorney: 'Ynanç haty ýa-da direktor bellemek barada buýruk',
    },
  },

  nav: {
    next: 'Indiki',
  },

  storeInformation: {
    title: 'Dükan maglumatlary',
    subtitle: 'Dükanyňyzyň maglumatlaryny görüň we üýtgediň.',
  },
  storeActivate: {
    goToStore: 'Dükan kabinetine geçmek',
    underReview:
      'Dükany bellige almak arzasy iberildi we barlaga garaşýar. Harytlar tassyklanandan soň katalogda görkeziler.',
    title: 'Dükanyňyzy işjeňleşdiriň',
    subtitle:
      'Dükanyňyzy doly açmak üçin aşakdaky ädimleriň barysyny tamamlaň. Hökmany meýdançalary doldurmazdan hasabyňyz işjeň bolmaz.',
    completedSteps: 'Tamamlanan ädimler',
    todos: {
      warehouseType: 'Ammar görnüşi',
      warehouseTypeDesc: 'Harytlaryňyzy saklamak üçin ammaryň görnüşini saýlaň',
      warehouseTypeLocked: '{{type}} · administrator üýtgedýär',
      name: 'Dükanyň ady we beýany',
      nameDesc: 'Alyjylara görkeziljek dükanyňyzyň adyny giriziň',
      addresses: 'Salgylar',
      addressesDesc: 'Dükanyňyzyň salgylaryny giriziň',
      phoneNumbers: 'Telefon belgileri',
      phoneNumbersDesc: 'Müşderileriň habarlaşmagy üçin telefon belgilerini giriziň',
      color: 'Reňk',
      colorDesc: 'Dükanyňyzyň esasy reňkini saýlaň',
      city: 'Şäher',
      cityDesc: 'Dükanyňyzyň ýerleşýän şäherini saýlaň',
      logo: 'Logotip',
      logoDesc: 'Dükanyňyzyň logotipini ýükläň (.webp formata geçiriler)',
    },
    cityModal: {
      title: 'Şäheriňizi saýlaň',
      save: 'Ýatda sakla',
      saving: 'Ýüklenýär...',
    },
    nameModal: {
      title: 'Dükanyň ady we düşündirişi',
      nameLabel: 'Dükanyň ady',
      descriptionLabel: 'Düşündiriş',
      save: 'Ýatda sakla',
      saving: 'Ýüklenýär...',
      nameError: 'Dükanyň adyny giriziň',
      descriptionError: 'Düşündiriş giriziň',
    },
    addressesModal: {
      title: 'Dükanyň salgylary',
      label: 'Salgy',
      placeholder: 'Salgy giriziň',
      add: 'Salgy goşmak',
      save: 'Ýatda sakla',
      saving: 'Ýüklenýär...',
      error: 'Azyndan bir salgy giriziň',
    },
    phoneNumbersModal: {
      title: 'Telefon belgileri',
      label: 'Telefon belgisi',
      placeholder: 'Telefon belgisini giriziň',
      add: 'Telefon belgisini goşmak',
      save: 'Ýatda sakla',
      saving: 'Ýüklenýär...',
      error: 'Azyndan bir telefon belgisini giriziň',
    },
    logoModal: {
      title: 'Dükanyň logotipi',
      upload: 'Logotipi ýüklemek üçin basyň',
      save: 'Ýatda sakla',
      saving: 'Ýüklenýär...',
      error: 'Logotip suratyny saýlaň',
    },
    warehouseTypeModal: {
      title: 'Söwdaňyzyň görnüşini saýlaň',
      save: 'Ýatda sakla',
      saving: 'Ýüklenýär...',
      fbs: {
        name: 'FBS (Fulfilment by Seller)',
        description:
          'FBS harytlar satyjynyň ammarynda saklanýar, satyjy özi gaplaýar we sargyt boýunça getirýär',
      },
      fbo: {
        name: 'FBO (Fulfilment by Operator)',
        description: 'FBO harytlar marketpleýsiň ammarynda saklanýar we şol ýerden iberilýär',
      },
    },
    colorModal: {
      title: 'Dükanyň reňki',
      selected: 'Saýlanan reňk',
      bgColor: 'Fon reňki',
      textColor: 'Tekst reňki',
      customLabel: 'Öz reňkiňiz',
      save: 'Ýatda sakla',
      saving: 'Ýüklenýär...',
      contrastUnreadable: 'Bu fonda tekst görünmeýär. Saklamak üçin başga reňk saýlaň.',
    },
  },

  filter: {
    title: 'Filtrler',
    category: 'Bölüm',
    brand: 'Brend',
    brandSearch: 'Brend gözleg',
    store: 'Dükan',
    storeSearch: 'Dükan gözleg',
    sort: 'Sortlamak',
    priceRange: 'Baha aralyk',
    priceFrom: 'başlap',
    priceTo: 'çenli',
    showAll: 'Hemmesini görmek',
    showLess: 'Az görmek',
    clearAll: 'Filtrleri arassala',
  },

  sort: {
    expensiveToCheap: 'Gymmatdan arzana',
    cheapToExpensive: 'Arzandan gymmada',
    newProducts: 'Täze harytlar',
    discount: 'Arzanlaşyk',
    bestSelling: 'Iň köp satylýan',
  },

  category: {
    all: 'Hemmesi',
    male: 'Erkek',
    female: 'Aýal',
  },

  footer: {
    aboutUs: 'Biz barada',
    contact: 'Habarlaşmak',
    termsOfUse: 'Ulanyş kadalary',
    privacyPolicy: 'Gizlinlik syýasaty',
    profile: 'Profil',
    myOrders: 'Sargytlarym',
    favorites: 'Halanlarym',
    brands: 'Brendler',
    stores: 'Dükanlar',
    becomeSeller: 'Satyjy bolmak',
    scrollToTop: 'Ýokary',
    followUs: 'Bizi sosial ulgamlarda yzarlaň:',
    home: 'Baş sahypa',
    categories: 'Bölümler',
    cart: 'Sebedim',
    orders: 'Sargytlarym',
  },

  product: {
    unavailable: 'Haryt elýeterli däl',
    unavailableHint: 'Ol satuwdan aýrylan ýa-da indi ýok bolmagy mümkin.',
    inStock: 'Bar: {{count}}',
    details: 'Maglumatlar',
    info: 'Haryt maglumatlary',
    similar: 'Meňzeş harytlar',
    youMayLike: 'Size ýarap biler',
    addToCart: 'Sebede goş',
  },

  products: {
    stock: 'Ammarda: {{count}}',
    outOfStock: 'Ýok',
    hidden: 'Satuwdan aýryldy',
    declined: 'Ret edildi',
    hide: 'Satuwdan aýyrmak',
    show: 'Satuwa gaýtarmak',
    blockedByStaff: 'Platforma tarapyndan satuwdan aýryldy',
    addButton: 'Haryt goşmak',
    empty: 'Haryt ýok',
    inReview: 'Barlanýar',
  },

  favorites: {
    empty: 'Halanan harytlaryňyz ýok',
  },

  addProduct: {
    descriptionTooLong:
      'Doly beýany diňe haryt sahypasynda görüner; sanawda başy we üç nokat görkeziler.',
    backToProducts: 'Harytlar',
    title: 'Haryt goşmak',
    images: 'Suratlar',
    imagesMax: '(iň köp 5)',
    imagesAdd: 'Goşmak',
    name: 'Ady',
    namePlaceholder: 'Harydyň ady',
    description: 'Beýany',
    descriptionPlaceholder: 'Harydyň beýany',
    category: 'Kategoriýa',
    categoryPlaceholder: 'Saýlaň',
    categoryModalTitle: 'Kategoriýa saýlaň',
    brand: 'Brend',
    brandPlaceholder: 'Saýlaň',
    brandModalTitle: 'Brend saýlaň',
    price: 'Bahasy',
    pricePlaceholder: '0',
    currency: 'Walýuta',
    currencyPlaceholder: 'Saýlaň',
    hashtag: 'Hashtag',
    hashtagPlaceholder: '#hashtag',
    measureUnit: 'Ölçeg birligi',
    measureUnitPlaceholder: 'Saýlaň',
    discountType: 'Arzanladyş görnüşi',
    discountTypeNone: 'Ýok',
    discountTypePercentage: 'Göterim (%)',
    discountTypeFixed: 'Kesgitli (TMT)',
    discount: 'Arzanladyş',
    discountPlaceholder: '0',
    submit: 'Haryt goşmak',
    submitting: 'Ýüklenýär...',
    error: 'Ähli hökmany meýdanlary dolduryň',
    moderationTitle: 'Haryt moderasiýa üçin iberildi',
    moderationDescription:
      'Operatorlarymyz harydyňyzy barlar we tassyklandan soň müşderilere elýeterli bolar.',
  },

  editProduct: {
    descriptionTooLong:
      'Doly beýany diňe haryt sahypasynda görüner; sanawda başy we üç nokat görkeziler.',
    backToProducts: 'Harytlar',
    title: 'Harydy üýtgetmek',
    images: 'Suratlar',
    imagesMax: '(iň köp 5)',
    imagesAdd: 'Goşmak',
    name: 'Ady',
    namePlaceholder: 'Harydyň ady',
    description: 'Beýany',
    descriptionPlaceholder: 'Harydyň beýany',
    category: 'Kategoriýa',
    categoryPlaceholder: 'Saýlaň',
    categoryModalTitle: 'Kategoriýa saýlaň',
    brand: 'Brend',
    brandPlaceholder: 'Saýlaň',
    brandModalTitle: 'Brend saýlaň',
    price: 'Bahasy',
    pricePlaceholder: '0',
    currency: 'Walýuta',
    currencyPlaceholder: 'Saýlaň',
    hashtag: 'Hashtag',
    hashtagPlaceholder: '#hashtag',
    measureUnit: 'Ölçeg birligi',
    measureUnitPlaceholder: 'Saýlaň',
    discountType: 'Arzanladyş görnüşi',
    discountTypeNone: 'Ýok',
    discountTypePercentage: 'Göterim (%)',
    discountTypeFixed: 'Kesgitli (TMT)',
    discount: 'Arzanladyş',
    discountPlaceholder: '0',
    submit: 'Üýtgeşmeleri ýatda sakla',
    submitting: 'Ýüklenýär...',
    error: 'Ähli hökmany meýdanlary dolduryň',
    moderationTitle: 'Haryt moderasiýa üçin iberildi',
    moderationDescription:
      'Operatorlarymyz harydyňyzy barlar we tassyklandan soň müşderilere elýeterli bolar.',
    saved: 'Üýtgeşmeler saklandy',
  },

  checkout: {
    deliveryLater:
      'Eltip berme bahasyny platforma sargydy tassyklanda habar berer — ýokardaky jemi deslapky.',
    placeOrder: 'Sargyt etmek',
    addressRequired: 'Eltip bermek salgysyny görkeziň.',
    pickupPointRequired: 'Eltip berme nokadyny saýlaň.',
    confirmOrder: 'Sargydy tassyklamak',
    clearCart: 'Sebedi pozmak',
    orderError: 'Sargyt ýerleşdirmek başartmady. Täzeden synanyşyň.',
    insufficientStock: '«{{product}}» harydy skladda ýeterlik däl. Sebetdäki mukdaryny azaldyň.',
    insufficientStockGeneric: 'Sebetdäki harytlaryň biri skladda ýeterlik däl. Mukdaryny barlaň.',
    deliveryMethod: 'Almak usuly',
    pickup: 'Alyş nokady',
    delivery: 'Eltip bermek',
    addressPlaceholder: 'Aşgabat, Magtymguly şaýoly, jaý 1',
    noPickupPoints:
      'Siziň şäheriňizde entek alyş nokady ýok — eltip bermegi saýlaň ýa-da şäheri üýtgediň',
    showOnMap: 'Kartada görkez',
    pickupPointsOnMap: 'Alyş nokatlary',
    mapUnavailable: 'Karta elýeterli däl: karta serweri düzülmedik.',
    paymentType: 'Töleg görnüşi',
    cash: 'Nagt',
    card: 'Terminal',
    cashAndCard: 'Nagt we Terminal',
    comment: 'Teswir',
    commentPlaceholder: 'Sargydyňyz üçin bellik galdyryň...',
    success: {
      title: 'Sargyt üstünlikli kabul edildi!',
      description: 'Sargydyňyz kabul edildi. Ony ýakyn wagtda gaýtadan işläp başlarys.',
      goHome: 'Baş sahypa',
      showOrder: 'Sargydy görkez',
    },
  },

  analytics: {
    title: 'Dükanlaryň analitikasy',

    subtitle: 'Ähli dükanlaryňyz boýunça jemi',

    period: 'Döwür: {{from}} — {{to}}',

    totalRevenue: 'Döwür üçin girdeji',

    totalOrders: 'Sargytlar',

    shopsCount: 'Dükanlar',

    byShop: 'Dükanlar boýunça',

    topProducts: 'Iň köp satylan harytlar',

    ordersShort: '{{count}} sarg.',

    soldShort: '{{count}} sany',

    noShops: 'Häzirlikçe dükanyňyz ýok',

    noShopsHint: 'Analitika dükan haýyşy tassyklanandan soň peýda bolar.',
  },

  cart: {
    notEnough: 'Bu harytdan ammarda ýeterlik däl',
    decrease: 'Sanyny azalt',
    increase: 'Sanyny köpelt',
    unavailable: 'Haryt indi satylmaýar',
    unavailableName: 'Haryt elýeterli däl',
    remove: 'Aýyrmak',
    hasUnavailable: 'Sargyt etmek üçin elýeterli däl harytlary aýyryň',
    hasStockProblem:
      'Käbir harytlar gerekli mukdarda ýok — sargyt etmek üçin olary aýyryň ýa-da mukdaryny azaldyň',
    onlyLeft: 'Diňe {{count}} sany bar — mukdaryny azaldyň',

    restore: 'Yzyna getir',
    goToCart: 'Sebede',
    title: 'Sebedim',
    empty: 'Sebediňizde entek hiç zat ýok',
    emptyHint: 'Ony doldurmagyň wagty geldi!',
    confirm: 'Sebedi tassykla',
    totalPrice: 'Umumy baha',
    productPrice: 'Harytlaryň bahasy',
    total: 'Jemi:',
    discount: 'Arzanladyş:',
    grandTotal: 'Umumy jemi:',
    aboutDelivery: 'Eltip bermek barada',
    noDeliveryInfo: 'Eltip bermek barada maglumat elýeterli däl',
  },

  aboutUs: {
    title: 'Biz barada',
    subtitle:
      '«Postshop» — «Türkmenpoçta» poçta aragatnaşyk kompaniýasynyň elektron söwda platformasy bolup, ýokary hilli harytlary siziň gapyňyza çenli eltip berýär.',
    historyTitle: 'Taryhymyz',
    historyDescription:
      '«Türkmenpoçta» poçta aragatnaşyk kompaniýasy özüniň esasy ösüşini 1993-nji ýylyň 7-nji aprelinde dörän gününden alyp gaýdýar. Häzirki wagtda kompaniýa öz işini döwrebap talaplara laýyklykda guramak wezipesini öňde goýýar. Türkmenistan döwletiniň adyndan 1993-nji ýylyň 26-njy ýanwarynda Bütindünýä poçta birleşmesiniň agzalygyna kabul edilen «Türkmenpoçta» kompaniýasy döwletiň poçta operatory hökmünde çykyş edýär. Bu bolsa örän gysga wagtyň içinde dünýäniň 190-dan gowrak ýurduna hat-habarlary we poçta ugratmalaryny ibermäge hem-de kabul etmäge mümkinçilik berdi.',
    foundedLabel: 'Döredilen senesi',
    foundedValue: '1993-nji ýylyň 7-nji apreli',
    upuLabel: 'BPB agzasy',
    upuValue: '1993-nji ýylyň 26-njy ýanwaryndan bäri',
    countriesLabel: 'Poçta alyş-çalşygy',
    countriesValue: '190-dan gowrak ýurt bilen',
    servicesTitle: 'Hyzmatlarymyz',
    service1: 'Poçta ugratmalaryny ugratmak we kabul etmek',
    service2: 'Gazet-žurnallara abuna ýazylyşygyny gurnamak',
    service3: 'Poçta pul geçirimlerini kabul etmek we gowşurmak',
    service4: 'Lomaý we bölek söwda',
    service5: 'Aragatnaşyk hyzmatlarynyň töleglerini kabul etmek',
    service6: 'Jemagat we kommunal hyzmatlaryň töleglerini kabul etmek',
    service7: '«Salgydan-salga» eltip bermek hyzmaty',
    service8: 'Elektron söwda hyzmatlary',
    postshopTitle: '«Postshop» barada',
    postshopDescription1:
      '«Postshop» — «Türkmenpoçta» poçta aragatnaşyk kompaniýasynyň döreden, öýden çykman gerekli ähli harytlary satyn almaga mümkinçilik berýän elektron söwda platformasydyr. Bu ýerden iň soňky enjamlardan başlap döwrebap egin-eşiklere çenli ähli zady tapyp bilersiňiz.',
    postshopDescription2:
      '«Postshop» elektron söwda platformasy alyş-berişi we eltip bermäni bir ýere jemläp, öňdebaryjy brendleriň ýokary hilli harytlaryny bäsdeşlige ukyply bahalar bilen hödürleýär hem-de harydy göni satyn alyjynyň gapysyna çenli çalt we ynamdar eltip berýär.',
    benefit1: 'Artykmaç alada etmezden amatly söwda',
    benefit2: 'Ünsli saýlanan haryt görnüşleri',
    benefit3: 'Ýurt boýunça çalt eltip bermek',
    benefit4: 'Müşderilere alada bilen ygtybarly hyzmat',
  },

  contactUs: {
    title: 'Biz bilen habarlaşyň',
    name: 'Adyňyz',
    phone: 'Telefon belgiňiz',
    message: 'Hatyňyz',
    submit: 'Ugratmak',
    infoTitle: 'Habarlaşmak üçin maglumat',
    phoneLabel: 'Telefon (Duş-Ýek 9:00-19:00)',
    email: 'Email',
    address: 'Salgy',
    showOnMap: 'Kartada görkez',
    error: 'Ähli meýdançalary dolduryň',
    submitting: 'Iberilýär...',
    successTitle: 'Hat iberildi!',
    successDescription: 'Biz siziň bilen ýakyn wagtda habarlaşarys.',
  },

  links: {
    back: 'Yza',
    backToHome: 'Baş sahypa gaýdyň',
  },

  collections: {
    notFound: 'Beýle saýlama ýok',
    empty: 'Bu saýlamada häzir elýeterli haryt ýok',
    seeAll: 'Ählisini görmek',
  },

  categories: {
    empty: 'Häzirlikçe kategoriýa ýok',
  },

  profileEdit: {
    title: 'Profili üýtget',
    name: 'Ady',
    surname: 'Familiýasy',
    nameRequired: 'Ady hökmany',
    surnameRequired: 'Familiýasy hökmany',
    save: 'Ýatda sakla',
    saving: 'Saklanýar...',
    cancel: 'Ýatyr',
    saved: 'Profil maglumatlary saklandy',
  },

  notifications: {
    title: 'Bildirişler',
    empty: 'Bildiriş ýok',
    markAll: 'Ählisini okadym',
    seeAll: 'Ählisini görmek',
    dismiss: 'Habarnamany aýyrmak',
    loadMore: 'Ýene görkez',
    deliveryDetail:
      'Eltip bermek {{delivery}} TMT, jemi {{total}} TMT. Razy däl bolsaňyz, sargydy ýygnalmazdan öň ýatyryň.',
    kind: {
      order_created: 'Täze sargyt — açyň: haryt sizde bolsa, kabul ediň we ýygnaň',
      order_cancelled: 'Sargyt ýatyryldy',
      product_blocked: 'Platforma harydy satuwdan aýyrdy',
      receipt_confirmed: 'Kabul ediliş tassyklandy, haryt galyndyda',
      product_out_of_stock: 'Haryt gutardy — ony täzeden getiriň ýa-da satuwdan aýryň',
      review_received: 'Harydyňyz barada täze syn',
      return_received:
        'Gaýtarma tassyklandy — haryt size gaýdyp geler. Alanyňyzda, muny «Yzyna gaýtarmalar» bölüminde belläň',
      shop_blocked: 'Dükan platforma tarapyndan ýapyldy',
      product_approved: 'Haryt barlagdan geçdi',
      product_declined: 'Haryt barlagdan geçmedi',
      shop_approved: 'Dükan arzasy tassyklandy',
      shop_rejected: 'Dükan arzasy kabul edilmedi',
      order_status: 'Sargydyň ýagdaýy üýtgedi',
      order_shop_rejected: 'Dükan sargydyň bir böleginden ýüz öwürdi',
      order_approved_delivery: 'Sargyt tassyklandy — eltip bermegiň bahasy bellendi',
      withdrawal_completed: 'Ammar harydyňyzy berdi',
      withdrawal_rejected: 'Ammar çykarmak arzasyny ret etdi',
      review_approved: 'Synyňyz ýerleşdirildi',
      review_rejected: 'Synyňyz kabul edilmedi',
      return_approved: 'Yzyna gaýtarmak tassyklandy',
      return_rejected: 'Yzyna gaýtarmak kabul edilmedi',
      return_completed: 'Gaýtarma kabul edildi we ýapyldy',
    },
  },

  storeReturns: {
    title: 'Yzyna gaýtarmalar',
    subtitle:
      'Dükanyňyzyň harytlary boýunça yzyna gaýtarmalar. Karary Postshop kabul edýär; tassyklanan gaýtarma size gelende, ony şu ýerde belläň.',
    fboWarehouse: 'Gaýtarmany Postshop ammary kabul eder',
    receiveRestock: 'Alyndy — satuwa gaýtarmak',
    receiveDefective: 'Alyndy — kemçilikli',
    defectiveTitle: 'Haryt kemçilikli geldimi?',
    defectiveText:
      'Gaýtarma alnan diýip bellener, ýöne haryt satuwa gaýtarylmaz — galyndy üýtgemez.',
    defectiveConfirm: 'Hawa, kemçilikli',
    restocked: 'Alyndy, satuwa gaýtaryldy',
    defective: 'Alyndy, kemçilikli',
    receivedSaved: 'Gaýtarma alnan diýip bellendi',
  },
  returns: {
    periodOver: 'Gaýtarma möhleti geçdi',
    hintUntil:
      'Haryt laýyk gelmedimi? Onuň ýanyndaky «Gaýtar» düwmesine basyň — {{date}} çenli. Arza Postshop seredýär',
    amount: 'Gaýtarylýan möçber: {{amount}} TMT',
    title: 'Gaýtarmalarym',
    subtitle: 'Yzyna gaýtarmak arzalary we olar boýunça çözgütler.',
    empty: 'Gaýtarmak arzasy ýok',
    unknownProduct: 'Haryt aýryldy',
    quantityShort: 'gaýtarylýan: {{count}}',
    fromOrder: 'sargyt №{{id}}',
    cancel: 'Yzyna al',
    cancelled: 'Arza yzyna alyndy',
    cancelTitle: 'Arzany yzyna almalymy?',
    cancelText: 'Arza sanawdan aýrylar. Bu satyn alyş boýunça täzesini ýene berip bolar.',
    action: 'Yzyna gaýtar',
    hint: 'Haryt gelişmedimi? Onuň ýanyndaky «Yzyna gaýtar» düwmesine basyň — arzany Postshop gözden geçirer',
    createTitle: 'Yzyna gaýtarmak arzasy',
    purchased: 'satyn alnan: {{count}}',
    quantity: 'Näçesini gaýtarýarsyňyz',
    reason: 'Gaýtarmagyň sebäbi',
    reasonPlaceholder: 'Harytda näme bar',
    reasonRequired: 'Sebäbini ýazyň',
    quantityRequired: 'Sanyny görkeziň',
    tooMany: 'Satyn alnandan köp gaýtaryp bolmaýar: {{count}}',
    notice: 'Arzany platforma serederer. Netije bildirişlerde geler.',
    send: 'Arzany ugrat',
    sending: 'Ugradylýar...',
    sent: 'Yzyna gaýtarmak arzasy ugradyldy',
    notAllowed: 'Bu satyn alyş boýunça gaýtarmak eýýäm dowam edýär ýa-da mümkin däl',
    awaitingItem:
      'Gaýtarma tassyklandy. Harydy islendik Postshop bermek nokadyna getiriň — kabul edilende habar geler.',
    receivedOn: 'Haryt kabul edildi {{date}}',
    status: {
      received: 'Gaýtarma tamamlandy',
      pending: 'Gaýtarmak seredilýär',
      approved: 'Gaýtarmak tassyklandy',
      rejected: 'Gaýtarmak kabul edilmedi',
    },
  },

  reviews: {
    title: 'Synlar',
    none: 'Hazyr syn ýok. Birinjini bu harydy satyn alan galdyryp biler.',
    count_one: '{{count}} syn',
    count_other: '{{count}} syn',
    leaveTitle: 'Syn galdyr',
    ratingRequired: 'Baha beriň',
    textPlaceholder: 'Näme ýarady, näme ýaramady (hökmany däl)',
    moderationNotice: 'Syn barlanandan soň sahypada görüner.',
    send: 'Ugrat',
    sending: 'Ugradylýar...',
    sent: 'Syn barlaga ugradyldy',
    onlyAfterPurchase: 'Syn bu haryt bilen sargyt tamamlanandan soň galdyrylyp bilner.',
    yoursPending: 'Siziň synyňyz barlagda',
    yoursRejected: 'Siziň synyňyz kabul edilmedi',
    anonymous: 'Alyjy',
    rate: 'Baha ber',
    rateTitle: 'Haryda baha ber',
    alreadyRated: 'Eýýäm baha berdiňiz',
  },

  addresses: {
    title: 'Salgylarym',
    subtitle: 'Ýatda saklanan salgyny sargyt edeniňizde saýlap bolýar, gaýtadan ýazmak gerek däl.',
    add: 'Salgy goş',
    editTitle: 'Salgyny üýtget',
    edit: 'Üýtget',
    delete: 'Poz',
    save: 'Ýatda sakla',
    name: 'Ady',
    namePlaceholder: 'Öý, Iş',
    address: 'Salgy',
    addressPlaceholder: 'Şäher, köçe, jaý, kwartira',
    titleRequired: 'Ady giriziň',
    addressRequired: 'Salgyny giriziň',
    defaultBadge: 'Esasy',
    makeDefault: 'Esasy et',
    empty: 'Ýatda saklanan salgy ýok',
    created: 'Salgy goşuldy',
    saved: 'Salgy saklandy',
    deleted: 'Salgy pozuldy',
    deleteTitle: 'Salgyny pozmalymy?',
    deleteText: 'Salgy sanawdan aýrylar. Öňki sargytlar üýtgemez.',
    chooseSaved: 'Salgyny saýlaň',
    newAddress: 'Başga salgy',
    saveThis: 'Bu salgyny ýatda sakla',
    saveThisName: 'Salgy üçin at',
  },

  passwordChange: {
    title: 'Parol',
    titleFirst: 'Parol belläň',
    subtitle: 'Paroly çalyşmak üçin häzirki paroly giriziň — hasabyňyz şeýle goralýar.',
    subtitleFirst: 'Siz SMS koduň üsti bilen girýärsiňiz. Parol login boýunça girmäge ýol açar.',
    current: 'Häzirki parol',
    new: 'Täze parol',
    repeat: 'Täze paroly gaýtalaň',
    save: 'Paroly çalyş',
    currentRequired: 'Häzirki paroly giriziň',
    currentWrong: 'Häzirki parol nädogry',
    sameAsCurrent: 'Täze parol häzirkiden tapawutly bolmaly',
    tooShort: 'Parol azyndan {{count}} simwol bolmaly',
    mismatch: 'Parollar gabat gelmeýär',
    changed: 'Parol çalşyryldy',
    created: 'Parol bellendi',
  },

  phoneChange: {
    title: 'Telefon belgisi',
    current: 'Häzirki belgi: {{phone}}',
    noneYet: 'Belgi görkezilmedik',
    newPhone: 'Täze belgi',
    hint: 'Kod täze belgä geler — şeýlelikde onuň siziňki bolşuna göz ýetirýäris.',
    sendCode: 'Kod al',
    sending: 'Ugradylýar...',
    codeSent: 'Kod ugradyldy',
    codeSentTo: 'Kod {{phone}} belgä ugradyldy',
    confirm: 'Tassykla',
    confirming: 'Barlanýar...',
    changed: 'Belgi çalşyryldy',
    wrongCode: 'Kod nädogry ýa-da wagty geçen',
    unavailable: 'Bu belgi eýýäm ulanylýar ýa-da häzirkisi bilen deň',
    tooOften: 'Kody minutda bir gezek sorap bolýar',
    phoneIncomplete: 'Belgini doly giriziň',
  },

  termsOfUse: {
    title: 'Ulanyş düzgünleri',
    lastUpdated: 'Soňky täzelenme: 2026-njy ýylyň 20-nji maýy',
    sections: {
      general: {
        title: '1. Umumy düzgünler',
        p1: 'Şu Ulanyş düzgünleri («Düzgünler») PostShop söwda platformasyna, şol sanda web saýtyna, mobil programmalaryna we ähli bagly hyzmatlara (bilelikde «Platforma») girmegi we ulanmagy düzgünleşdirýär.',
        p2: 'Hasap açmak, görmek ýa-da Platformada satyn almak bilen, siz şu Düzgünleri kabul edýärsiňiz. Eger razy bolmasaňyz, Platformany ulanmagy bes ediň.',
        p3: 'PostShop şu Düzgünleri islendik wagtda täzelemek hukugyny özünde saklaýar. Üýtgeşmelerden soň Platformany ulanmagy dowam etmek täzelenen Düzgünleri kabul etmegi aňladýar.',
      },
      accounts: {
        title: '2. Ulanyjy hasaplary',
        p1: 'Sargyt bermek ýa-da käbir aýratynlyklara girmek üçin hereket edýän telefon belgisini görkezip hasap döretmeli. Hasabyňyzyň howpsuzlygyny saklamak siziň jogapkärçiligiňizdir.',
        p2: 'Takyk we häzirki şahsy maglumatlary bermeli. PostShop ýalan ýa-da doly däl maglumatly hasaplary togtadyp ýa-da ýok edip biler.',
        p3: 'Hasabyňyzyň astynda amala aşyrylýan ähli hereketler üçin jogapkärsiňiz. Rugsat berilmedik giriş şübhelense, derrew PostShop-a habar beriň.',
      },
      orders: {
        title: '3. Sargytlar we töleg',
        p1: 'Ähli haryt bahalary türkmen manadynda (TMT) görkezilýär we başgaça bellenilmedik bolsa, degişli salgytlary öz içine alýar. Bahalar satyjylar tarapyndan bellenilýär we öňünden duýdurmazdan üýtgedilip bilner.',
        p2: 'Sargyt tassyklama alanyňyzdan soň tassyklanan hasaplanýar. PostShop baha ýalňyşlyklary, harydyň ýoklugy ýa-da galplyk şübhesi sebäpli sargytlary ýatyrmak hukugyny özünde saklaýar.',
        p3: 'Töleg nagt, bank terminaly ýa-da ikisiniň kombinasiýasy arkaly eltip berilende ýa-da alnyp gidilende amala aşyrylýar. Ähli töleg borçnamalary haryt alnan wagtynda ýerine ýetirilmeli.',
      },
      delivery: {
        title: '4. Eltip bermek we özüň almak',
        p1: 'Harytlary alyş nokadyndan ýa-da görkezilen salga eltip bermek arkaly alyp bolýar. Eltip bermegiň elýeterliligi we möhletleri sebite we haryda görä üýtgäp biler.',
        p2: 'PostShop eltip bermek hyzmatlaryny bermek üçin «Türkmenpoçta» bilen hyzmatdaşlyk edýär. Çak edilýän eltip bermek möhletlerini berjaý etmäge çalyşýarys, ýöne biziň gözegçiligimizden daşary ýagdaýlar sebäpli gijä galyp biler.',
        p3: 'Harydy alanyňyzda ony barlamak borjuňyzdyr. Islendik zeper ýa-da tapawutlyklyk barada alnan wagtyndan 24 sagadyň dowamynda habar bermeli.',
      },
      sellers: {
        title: '5. Satyjylar we harytlar',
        p1: 'PostShop alyjylary garaşsyz satyjylar bilen birleşdirýän söwda platformasydyr. Her satyjy haryt düşündirişleriniň, bahalarynyň we elýeterliliginiň takyklygy üçin jogapkärdir.',
        p2: 'PostShop harytlary öndürmeýär, saklamaýar we gönüden-göni satmaýar, başgaça açyk görkezilmedik bolsa. Harydyň hili, kepillikleri we standartlara laýyklygy satyjynyň jogapkärçiligindedir.',
        p3: 'Haryt ýa-da satyjy bilen baglanyşykly mesele ýüze çyksa, PostShop goldaw gullugyna ýüz tutuň. Jedelleri çözmäge kömek ederis we platforma düzgünlerini bozýan satyjylara garşy çäre görüp bileris.',
      },
      returns: {
        title: '6. Gaýtaryp bermek we yzyna gaýtarmak',
        p1: 'Gaýtaryp bermek we yzyna gaýtarmak düzgünleri her satyjynyň şertlerine we Türkmenistanyň sarp edijileriň hukuklaryny goramak baradaky kanunçylygyna laýyklykda kesgitlenýär.',
        p2: 'Haryt kemçilikli bolsa, eltip berilende zaýalanan bolsa ýa-da düşündirişden ep-esli tapawutlanýan bolsa yzyna gaýtarylyp bilner. Gaýtaryş arzasy alnan gününden 14 günüň dowamynda berilmeli.',
        p3: 'Yzyna gaýtarmak öňki töleg usuly bilen amala aşyrylýar. Gaýtadan işleme wagty töleg üpjün edijisine bagly bolup biler.',
      },
      intellectual: {
        title: '7. Intellektual eýeçilik',
        p1: 'Platformadaky ähli mazmun, şol sanda logotipler, dizaýnlar, tekstler, grafikalar we programma üpjünçiligi PostShop-yň ýa-da onuň ygtyýarnamaçylarynyň eýeçiligindedir we intellektual eýeçilik kanunlary bilen goralýar.',
        p2: 'PostShop-yň öňünden ýazmaça razylygy bolmazdan Platformanyň mazmunyny göçürmek, köpeltmek, ýaýratmak ýa-da onuň esasynda gaýtadan işlemeler döretmek gadagandyr.',
      },
      liability: {
        title: '8. Jogapkärçiligiň çäklendirilmegi',
        p1: 'PostShop Platformany «bardygy ýaly» hödürleýär we üznüksiz, ýalňyşsyz ýa-da ygtybarly girişi kepillendirmeýär. Platformany ulanmagyňyz bilen baglanyşykly gytaklaýyn, tötänleýin ýa-da ýanyşyk zyýanlar üçin jogapkär däldiris.',
        p2: 'PostShop satyjylaryň hereketleri, harytlaryň hili ýa-da Platformadaky alyjylar bilen satyjylaryň arasyndaky geleşiklerden dörän ýitgiler üçin jogapkär däldir.',
      },
      privacy: {
        title: '9. Gizlinlik we maglumatlary goramak',
        p1: 'Şahsy maglumatlaryňyz Gizlinlik syýasatymyza laýyklykda ýygnalyp işlenýär. Platformany ulanmak bilen, onda beýan edilen maglumat ýygnamasyna razyçylyk berýärsiňiz.',
        p2: 'PostShop şahsy maglumatlaryňyzy rugsat berilmedik girişden, üýtgetmekden ýa-da aýan etmekden goramak üçin degişli tehniki we guramaçylyk çärelerini amala aşyrýar.',
      },
      contact: {
        title: '10. Habarlaşmak üçin maglumatlar',
        p1: 'Şu Düzgünler bilen baglanyşykly soraglar, şikaýatlar ýa-da teklipler üçin biziň bilen habarlaşyň:',
        phoneLabel: 'Telefon:',
        emailLabel: 'E-poçta:',
        addressLabel: 'Salgy:',
      },
    },
  },

  privacyPolicy: {
    title: 'Gizlinlik syýasaty',
    lastUpdated: 'Soňky täzelenme: 2026-njy ýylyň 20-nji maýy',
    sections: {
      intro: {
        title: '1. Giriş',
        p1: 'PostShop («biz», «bizi» ýa-da «biziň») ulanyjylarymyzyň gizlinligini goramaga borçlanýar. Şu Gizlinlik syýasaty PostShop söwda platformasyny, şol sanda web saýtyny we mobil programmalaryny («Platforma») ulananyňyzda şahsy maglumatlaryňyzy nädip ýygnaýandygymyzy, ulanýandygymyzy, saklaýandygymyzy we goraýandygymyzy düşündirýär.',
        p2: 'Platformany ulanmak bilen, şu Gizlinlik syýasatynda beýan edilen tejribelere razyçylyk berýärsiňiz. Şahsy maglumat bermezden ozal ony ünsli okamagy maslahat berýäris.',
      },
      dataCollected: {
        title: '2. Ýygnaýan maglumatlarymyz',
        p1: 'Hasap maglumatlary: hasaba duranyňyzda telefon belgiňizi, adyňyzy we familiýaňyzy ýygnaýarys.',
        p2: 'Sargyt maglumatlary: sargyt bereniňizde eltip bermek salgyňyzy, töleg usuly saýlawyňyzy we sargyt taryhyňyzy ýygnaýarys.',
        p3: 'Enjam we ulanmak maglumatlary: Platformany gowulandyrmak üçin enjamyňyz (görnüşi, operasion ulgamy, brauzeri), IP salgyňyz, barylan sahypalar we aragatnaşyk nusgalary barada maglumatlary awtomatiki ýygnaýarys.',
        p4: 'Satyjy maglumatlary: satyjy hökmünde hasaba duranyňyzda, kanun talaplaryna laýyklykda telekeçilik hasaba alyş resminamalary, salgyt kesgitleýiş maglumatlary we bank rekwizitlerini goşmaça ýygnaýarys.',
      },
      howWeUse: {
        title: '3. Maglumatlaryňyzy nädip ulanýarys',
        p1: 'Platformada hasabyňyzy döretmek we dolandyrmak üçin.',
        p2: 'Sargytlaryňyzy gaýtadan işlemek we ýerine ýetirmek, şol sanda «Türkmenpoçta» bilen eltip bermegi utgaşdyrmak üçin.',
        p3: 'Sargytlar, mahabatlar we Platforma täzelikleri barada siz bilen habarlaşmak üçin.',
        p4: 'Platformany gowulandyrmak, ulanmak nusgalaryny seljermek we täze aýratynlyklary işläp düzmek üçin.',
        p5: 'Galplygyň öňüni almak, Ulanyş düzgünlerini berjaý etmek we kanun borçnamalaryny ýerine ýetirmek üçin.',
      },
      sharing: {
        title: '4. Maglumatlary paýlaşmak',
        p1: 'Satyjylar bilen: sargytlaryňyzy ýerine ýetirmek üçin adyňyzy, eltip bermek salgyňyzy we telefon belgiňizi satyjylara berýäris.',
        p2: 'Eltip bermek hyzmatdaşlary bilen: eltip bermegi amala aşyrmak üçin eltip bermek maglumatlaryny «Türkmenpoçta» we beýleki logistika hyzmatdaşlaryna berýäris.',
        p3: 'Hyzmat üpjün edijiler bilen: berk gizlinlik şertnamalary esasynda hosting, analitika we müşderi goldawy bilen kömek edýän üçünji tarap üpjün edijilere maglumat berip bileris.',
        p4: 'Şahsy maglumatlaryňyzy üçünji taraplara satmaýarys. Kanun talap etse ýa-da PostShop-yň we ulanyjylarynyň hukuklaryny, howpsuzlygyny ýa-da emlägini goramak üçin maglumatlary aýan edip bileris.',
      },
      cookies: {
        title: '5. Cookie faýllary we yzarlamak',
        p1: 'Platforma saýlawlaryňyzy ýatda saklamak, sessiýaňyzy goldamak we traffigi seljermek üçin cookie faýllaryny we şuňa meňzeş tehnologiýalary ulanýar. Brauzeriňizde cookie sazlamalaryny dolandyryp bilersiňiz, ýöne cookie-ni öçürmek Platformanyň käbir aýratynlyklaryny çäklendirip biler.',
        p2: 'Içine girip galmagy we dil hem-de sebit saýlawlaryňyzy saklamak üçin ýerli ammary ulanýarys.',
      },
      security: {
        title: '6. Maglumatlaryň howpsuzlygy',
        p1: 'Şahsy maglumatlaryňyzy rugsat berilmedik girişden, üýtgetmekden ýa-da aýan etmekden goramak üçin şifrlemek, goragly serwerleri we giriş gözegçiligini öz içine alýan pudak standart howpsuzlyk çärelerini durmuşa geçirýäris.',
        p2: 'Ähli ähtimallyklara taýyn bolsak-da, hiç bir elektron geçiriş ýa-da saklama usuly dolulygyna howpsuz däldir. Maglumatlaryňyzyň doly howpsuzlygyny kepillendirip bilmeris.',
      },
      retention: {
        title: '7. Maglumatlary saklamak',
        p1: 'Hasabyňyz işjeň bolup dursa ýa-da hyzmatlarymyzy bermek üçin zerur bolsa, şahsy maglumatlaryňyzy saklaýarys. Sargyt taryhy hukuk we buhgalteriýa maksatlary üçin saklanýar.',
        p2: 'Hasap pozulandan soň, şahsy maglumatlaryňyz 30 günüň dowamynda aýrylar, kanun tarapyndan saklama talap edilýän ýa-da galplygyň öňüni almak ýaly kanuny iş maksatlary bolan ýagdaýlardan başga.',
      },
      rights: {
        title: '8. Siziň hukuklaryňyz',
        p1: 'Girmek: islendik wagtda hasap sazlamalarynda şahsy maglumatlaryňyzy görüp we täzeläp bilersiňiz.',
        p2: 'Düzetmek: nätakyk ýa-da doly däl maglumatlary düzetmegi goldaw toparymyza ýüz tutup sorap bilersiňiz.',
        p3: 'Pozmak: Platforma sazlamalary arkaly hasabyňyzy pozup bilersiňiz. Bu şahsy maglumatlaryňyzyň kanun talaplaryna laýyklykda aýrylmagyna getirer.',
        p4: 'Göçürmek: bize ýüz tutup, şahsy maglumatlaryňyzyň gurluşly, umumy ulanylýan formatda nusgasyny sorap bilersiňiz.',
      },
      children: {
        title: '9. Çagalar',
        p1: 'Platforma 16 ýaşdan kiçi çagalaryň ulanmagy üçin niýetlenen däldir. Çagalardan bilkastlaýyn şahsy maglumat ýygnamaýarys. Çaganyň maglumatlaryny ýygnapdyrys diýip bilsek, olary dessine pozarys.',
      },
      changes: {
        title: '10. Şu syýasatdaky üýtgeşmeler',
        p1: 'Wagtal-wagtal şu Gizlinlik syýasatyny täzeläp bileris. Üýtgeşmeler täzelenen sene bilen şu sahypada çap ediler.',
        p2: 'Üýtgeşmeler çap edilenden soň Platformany ulanmagy dowam etmek täzelenen Gizlinlik syýasatyny kabul etmegi aňladýar. Möhüm üýtgeşmeler üçin Platforma arkaly ýa-da başga usullar bilen habar bereris.',
      },
      contact: {
        title: '11. Biziň bilen habarlaşyň',
        p1: 'Şu Gizlinlik syýasaty ýa-da şahsy maglumatlaryňyz barada soraglaryňyz, bellikleriňiz ýa-da islegleriňiz bar bolsa, biziň bilen habarlaşyň:',
        phoneLabel: 'Telefon:',
        emailLabel: 'E-poçta:',
        addressLabel: 'Salgy:',
      },
    },
  },
}
