export const tr = {
  meta: {
    title: 'Postshop - En İyi Ürünler Uygun Fiyatlarla',
  },
  notFound: {
    title: 'Sayfa bulunamadı',
    backHome: 'Ana sayfaya dön',
  },
  login: {
    openButton: 'Giriş yap',
    title: {
      phone: 'Giriş yapmak için telefon numaranızı girin',
      profile: 'Aşağıdaki bilgileri girin',
      otp: 'SMS ile gelen kodu girin',
    },
    otpSentTo: 'Kod {{phone}} numarasına gönderildi',
    codePlaceholder: 'SMS kodu',
    next: 'İleri',
    save: 'Kaydet',
    resend: 'Kodu tekrar gönder',
    resendIn: '{{seconds}} saniye sonra tekrar gönder',
    firstName: 'Ad',
    lastName: 'Soyad',
    disclaimer: 'Devam ederek <terms>Kullanım Şartlarını</terms> kabul ediyorsunuz',
    errors: {
      general: 'Bir hata oluştu. Lütfen tekrar deneyin.',
      invalidOtp: 'Kod hatalı. Lütfen tekrar deneyin.',
    },
    success: {
      title: 'Hesabınıza giriş yaptınız',
      description: 'Sepet, favoriler ve siparişler artık kullanılabilir.',
      close: 'Devam et',
    },
  },
  services: {
    tiles: {
      stores: 'Mağazalar',
      brands: 'Markalar',
      favorites: 'Favorilerim',
      becomeStore: 'Satıcı ol',
    },
    adds: {
      title: 'PostShop satıcı',
      heading: 'Postshop platformunda işinize başlayın',
      freeMonth: 'İlk ay — ÜCRETSİZ!',
      description:
        'Ürünlerinizin etkin lojistiğini ve kapsamlı tanıtımını sağlayarak pazara hızlı girmenize ve satışlarınızı artırmanıza yardımcı oluyoruz',
      cta: 'Satıcı platformunu aç',
    },
    phone: {
      title: 'Giriş yapmak için telefon numaranızı girin',
      termsPrefix: 'Bilgileri doldurmaya devam ederek',
      termsLink: 'Kullanım Şartlarını',
      termsSuffix: 'kabul ediyorum',
    },
    tradeType: {
      title: 'Ticaret türünüzü seçin',
      individual: 'Bireysel girişimciler için',
      legalEntity: 'Tüzel kişiler için',
    },
    upload: {
      title:
        'Satıcı platformuna erişmek için gerekli belgelerin elektronik kopyalarını yüklemenizi rica ediyoruz',
      individualDocs: [
        'Bireysel girişimci tescil belgesi',
        'Patent (geçerli)',
        'Tescil belgesi',
        'Pasaport kopyası',
      ],
      legalEntityDocs: [
        'Şirket tüzüğü (tüm sayfalar mühürlü)',
        'Tüzel kişiler devlet sicilinden alıntı',
        'Tescil belgesi',
        'İstatistik belgesi (OKED kodları ile)',
        'Vekaletname veya müdür atama emri',
      ],
    },
    success: {
      title: 'Başarıyla gönderildi!',
      description: 'Talebiniz alındı. En kısa sürede sizinle iletişime geçeceğiz.',
      close: 'Kapat',
    },
    loginRequired: {
      login: 'Giriş yap',
      title: 'Giriş yapmanız gerekiyor',
      description: 'Satıcı olmak için başvurmadan önce giriş yapmalısınız.',
      favoritesDescription: 'Favori ürünlerinizi görmek için lütfen önce giriş yapın.',
      cartDescription: 'Sipariş vermek için lütfen önce giriş yapın.',
      close: 'Kapat',
    },
    next: 'İleri',
  },
  dashboard: {
    insights: {
      title: 'Düzeltmeye değer',
      subtitle: 'Şimdi harekete geçebileceğiniz listeler.',
      noRating: 'Henüz puan yok',
      newReviews_one: 'Bu ay {{count}} yeni yorum',
      newReviews_other: 'Bu ay {{count}} yeni yorum',
      unsold: 'Bu ay satılmadı',
      unsoldHint: 'En çok görüntülenenler önce: bakıp almıyorlarsa genelde fiyat ya da fotoğraf.',
      returned: 'İade edildi',
      returnedHint: 'Bir iade tesadüf, tek üründe üç iade partiyi kontrol etme sebebi.',
      returnsCount_one: '{{count}} iade',
      returnsCount_other: '{{count}} iade',
    },
    summary: {
      subtitle: 'Dönem toplamları ve bir öncekine göre değişim.',
      noBase: 'karşılaştıracak veri yok',
      revenue: 'Ciro',
      orders: 'Sipariş',
      averageCheck: 'Ortalama sepet',
      rejected: 'Reddedilen',
      period: {
        week: 'Hafta',
        month: 'Ay',
        quarter: '3 ay',
      },
    },

    revenue: {
      title: 'Gelir raporu',
      subtitle: 'Haftalık gelir özeti',
      currency: 'TMT',
      weekdays: ['Pt', 'Sa', 'Ça', 'Pe', 'Cu', 'Ct', 'Pa'],
      orders: 'sipariş',
      empty: 'Bu hafta henüz gelir yok',
    },
    topProducts: {
      title: 'En çok satan ürünler',
      empty: 'Henüz satış yok',
    },
    notifications: {},
  },
  myStore: {
    notYours: 'Bu mağaza size ait değil',
    notice: {
      closed:
        'Mağaza kapalı: ürünleri müşteriler görmüyor. «Mağazayı kapat» bölümünden yeniden açabilirsiniz.',
      pending: 'Mağaza incelemede. Ürünler onaylandıktan sonra katalogda görünecek.',
      rejected: 'Kayıt başvurusu reddedildi. Ürünler müşterilere gösterilmiyor.',
      suspended: 'Kayıt askıya alındı. Ürünler müşterilere gösterilmiyor.',
    },
  },
  storeClose: {
    hasOpenWork:
      'Açık siparişler veya tamamlanmamış iadeler varken mağaza kapatılamaz. Bunları tamamlayıp tekrar deneyin.',
    closedByStaff:
      'Mağaza platform tarafından kapatıldı. Yalnızca platform yeniden açabilir — destekle iletişime geçin.',
    title: 'Mağazayı kapat',
    subtitle:
      'Kapalı mağaza katalogdan kaybolur: müşteriler ürünleri göremez ve sipariş veremez. Verilmiş siparişlerin tamamlanması gerekir. Mağazayı istediğiniz zaman buradan yeniden açabilirsiniz.',
    close: 'Mağazayı kapat',
    closed: 'Mağaza kapatıldı',
    reopenTitle: 'Mağazayı aç',
    reopenSubtitle:
      'Mağaza kapalı, müşteriler ürünleri görmüyor. Açtıktan sonra ürünler katalogda yeniden görünür.',
    reopen: 'Mağazayı aç',
    reopened: 'Mağaza açıldı',
    failed: 'Mağaza durumu değiştirilemedi',
    confirmTitle: 'Mağaza kapatılsın mı?',
    confirmText: 'Ürünler müşterilere gösterilmeyi bırakır. Bu işlem geri alınabilir.',
    confirm: 'Kapat',
    cancel: 'İptal',
    deleteTitle: 'Mağazayı sil',
    deleteText:
      'Mağaza kendi başınıza silinemez: siparişler ve belgeler ona bağlı kalır. Destek ekibine yazın, inceleme sonrası sileriz.',
    deleteLink: 'Desteğe yaz',
  },
  upload: {
    processing: 'Fotoğraflar hazırlanıyor…',
    notImage: 'Bu bir görsel değil — JPG, PNG veya WebP formatında bir fotoğraf seçin',
    unreadable: 'Görsel işlenemedi — başka bir dosya seçin (JPG, PNG veya WebP)',
  },

  productBarcode: {
    vendorLabel: 'Üretici barkodu',
    vendorPlaceholder: 'Örneğin, 4600000000000',
    vendorHint: 'İsteğe bağlı. Ambalajdaki 8, 12, 13 veya 14 hane',
    invalid: 'Üretici barkodu 8, 12, 13 veya 14 haneden oluşur',
    duplicate: 'Mağazanızda bu üretici barkoduna sahip bir ürün zaten var',
    platformLabel: 'Postshop barkodu',
    platformHint: 'Otomatik atanır, değiştirilemez',
  },

  errors: {
    uploadInterrupted: 'Yükleme yarıda kesildi — bağlantı çok zayıf. Lütfen tekrar deneyin',
    network: 'Sunucuya bağlantı yok. Bağlantınızı kontrol edip tekrar deneyin',
    server: 'Sunucu hatası. Daha sonra tekrar deneyin',
    badRequest: 'İşlem tamamlanamadı',
    unauthorized: 'Yeniden giriş yapmanız gerekiyor',
    forbidden: 'Yetki yetersiz',
    notFound: 'Bulunamadı',
    conflict: 'Zaten mevcut',
    tooLarge: 'Dosya çok büyük',
    validation: 'Doldurduğunuz alanları kontrol edin',
    tooManyRequests: 'Çok fazla deneme. Biraz bekleyin',
    unknown: 'Bir şeyler ters gitti',
  },
  common: {
    cancel: 'İptal',
  },
  cartClear: {
    title: 'Sepet boşaltılsın mı?',
    text: 'Tüm ürünler sepetten kaldırılacak. Bu işlem geri alınamaz.',
    confirm: 'Boşalt',
  },
  contacts: {
    phoneNote: 'Ana',
    office: 'Türkmenpoçta merkez ofisi',
    city: 'Aşkabat, Türkmenistan',
  },
  withdrawal: {
    action: 'Geri al',
    title: 'Ürünü depodan geri al',
    free: 'Depoda serbest: {{count}}',
    quantity: 'Ne kadar alınacak',
    comment: 'Depo için not',
    commentPlaceholder: 'Örn. ne zaman ve kim alacak',
    notice: 'Talebi Postshop deposu inceleyecek. Açık siparişlerin tuttuğu ürün alınamaz.',
    send: 'Talebi gönder',
    sent: 'Çekme talebi gönderildi',
    quantityInvalid: '1 ile {{count}} arasında miktar girin',
    hint: 'Ürününüzü Postshop deposundan geri alma talepleri. Yeni talep için «Depodaki stok» bölümünde ürünün yanındaki «Geri al»a basın.',
    empty: 'Çekme talebi yok',
    number: 'Talep #{{id}}',
    cancel: 'Geri çek',
    cancelled: 'Talep geri çekildi',
    status: {
      pending: 'İnceleniyor',
      completed: 'Ürün teslim edildi',
      rejected: 'Reddedildi',
      cancelled: 'Geri çekildi',
    },
  },
  stockHistory: {
    open: 'Geçmiş',
    title: 'Stok hareketleri',
    empty: 'Henüz hareket yok',
    op: {
      income: 'Giriş',
      sold: 'Satış',
      return_from_customer: 'Müşteri iadesi',
      return_to_supplier: 'Tedarikçiye iade',
      return_to_shop: 'Depodan size iade',
      write_off: 'Zayi (kusur, kayıp)',
      correction: 'Sayım',
    },
  },
  stock: {
    title: 'Stok',
    subtitle: 'Satışa ne kadar ürün hazır. Açık siparişlerin tuttuğu miktar düşülür.',
    notTracked:
      'Platform deposu kapalı: FBO mağazasının stoku şu anda satın almayı sınırlamıyor. Stoku kendiniz yönetmek için yöneticiden mağazayı FBS’e geçirmesini isteyin.',
    fboTitle: 'Depodaki stok',
    fboSubtitle:
      'Ürünleriniz Postshop depolarında saklanır. Stok, platform kabul belgesini onayladığında artar ve her tamamlanan siparişle azalır.',
    available: 'Mevcut: {{count}}',
    addOperation: 'Stok: {{count}}',
    operationTitle: 'Stoğu değiştir',
    operations: {
      income: 'Giriş',
      return_to_supplier: 'Tedarikçiye iade',
      set: 'Stoğu belirt',
    },
    breakdown: 'Rafta: {{shelf}} · siparişlerde: {{reserved}} · mevcut: {{available}}',
    alreadyEquals: 'Stok zaten bu kadar — hiçbir şey kaydedilmedi',
    operationsHint: {
      income: 'Ürün depoya geldi ve satışa hazır',
      return_to_supplier: 'Ürün depodan tedarikçiye dönüyor',
      set: 'Rafı saydınız — üzerinde ne kadar olduğunu girin. Paketlenmiş siparişleri saymayın. Farkı biz kaydederiz.',
    },
    quantityPlaceholder: 'Miktar',
    quantityRequired: 'Sıfırdan büyük bir miktar girin',
    save: 'Kaydet',
    saved: 'Hareket kaydedildi',
    setSaved: 'Stok güncellendi',
    amountPlaceholder: 'Rafta kaç adet var',
    amountRequired: 'Bir sayı girin: sıfır veya daha fazla',
    edit: 'Değiştir',
    fbsOnly:
      'Bu bölüm FBS mağazaları içindir: ürünlerini kendileri saklar. FBO mağazasının stoku «Depo» bölümündedir.',
  },
  intake: {
    title: 'Ürün kabulü',
    subtitle:
      'Ürün geldi — ne kadar geldiğini girin. Stok bu miktar kadar artar ve ürün hemen satın alınabilir.',
    fbsOnly:
      'Bu bölüm FBS mağazaları içindir: ürünü kendileri kabul eder. FBO mağazası ürünü Postshop deposuna gönderir — «Depo» bölümünde.',
    accept: 'Kabul et',
    modalTitle: 'Ürün kabulü',
    saved: 'Ürün kabul edildi',
  },
  warehouse: {
    title: 'Depo',
    subtitle: 'Postshop deposundaki ürünleriniz: orada ne kadar var ve depoya gönderim belgeleri.',
    fboOnly:
      'Bu bölüm FBO mağazaları içindir: ürünleri Postshop deposunda saklanır. FBS mağazası kaydını kendisi tutar — «Stok» ve «Ürün kabulü» bölümlerinde.',
    tabStock: 'Depodaki stok',
    tabShipments: 'Depoya gönderim',
    tabWithdrawals: 'Depodan çekme',
  },
  receipts: {
    title: 'Depoya gönderim',
    subtitle:
      'Ürünün Postshop deposuna gönderilmesi. Kabulü platform onaylar — ardından ürün stoka girer.',
    notTracked:
      'Depo kabulü yalnızca FBO mağazaları içindir: ürünlerini platform saklar. FBS mağazası stokunu «Stok» sayfasında kendisi yönetir.',
    create: 'Yeni belge',
    created: 'Belge oluşturuldu',
    empty: 'Henüz kabul belgesi yok',
    number: 'Belge №{{id}}',
    status: {
      draft: 'Taslak',
      confirmed: 'Kabul edildi',
      cancelled: 'İptal edildi',
    },
    addItem: 'Ürün ekle',
    itemAdded: 'Ürün eklendi',
    selectWarehouse: 'Depo seçin',
    selectProduct: 'Ürün seçin',
    productRequired: 'Ürün seçin',
    addItemsFirst: 'Ürün ekleyin — platform boş belgeyi kabul etmez',
    awaitingConfirmation: 'Platform onayı bekleniyor',
    cancel: 'İptal et',
    cancelled: 'Belge iptal edildi',
    cancelTitle: 'Belge iptal edilsin mi?',
    cancelText: 'Belge iş akışından çıkar. İçindeki ürünler depoya gelmez.',
  },
  storeSidebar: {
    closeStore: 'Mağazayı kapat',
    analytics: 'Analitik',
    dashboard: 'İstatistikler',
    orders: 'Siparişlerim',
    products: 'Ürünlerim',
    storeInformation: 'Mağaza bilgileri',
    agreement: 'Kullanım şartları',
    privacyPolicy: 'Gizlilik politikası',
    favorites: 'Favorilerim',
    cart: 'Sepetim',
    becomeSeller: 'Satıcı ol',
    logout: 'Çıkış yap',
  },
  logoutPage: {
    title: 'Çıkış yap',
    subtitle: 'Çıkış yapmak istediğinizden emin misiniz?',
    confirm: 'Çıkış yap',
    cancel: 'İptal',
  },
  orders: {
    orderNumber: 'Sipariş #{{id}}',
    storeRejected: 'Mağaza reddetti',
    partiallyRejected: 'Siparişin bir kısmı mağaza tarafından reddedildi',
    months: {
      1: 'Ocak',
      2: 'Şubat',
      3: 'Mart',
      4: 'Nisan',
      5: 'Mayıs',
      6: 'Haziran',
      7: 'Temmuz',
      8: 'Ağustos',
      9: 'Eylül',
      10: 'Ekim',
      11: 'Kasım',
      12: 'Aralık',
    },
    status: {
      done: 'Tamamlandı',
      cancelled: 'İptal edildi',
      pending: 'Beklemede',
      in_progress: 'Hazırlanıyor',
      attention: 'Dikkat',
    },
    detail: {
      cancelOrder: 'Siparişi iptal et',
      unnamedStore: 'Adsız mağaza',
      cancelSuccessTitle: 'Sipariş iptal edildi',
      cancelSuccessDescription: 'Yönetici bilgilendirildi.',
      cancelConfirmSubtitle: 'Bu siparişi iptal etmek istediğinizden emin misiniz?',
      cancelConfirmButton: 'Evet, iptal et',
      productPrice: 'Ürün fiyatı',
      total: 'Toplam:',
      discount: 'İndirim:',
      deliveryPrice: 'Teslimat ücreti',
      rejectedStores: 'Mağazaların reddettiği',
      deliveryPending: 'Fiyatı operatör onayda belirler',
      cancelReason: 'İptal nedeni',
      cancelTooLate:
        'Sipariş zaten hazırlandı, yolda veya tamamlandı — artık iptal edilemez. Durum güncellendi.',
      cancelReasonPlaceholder: 'İsteğe bağlı — mağaza ne olduğunu anlar',
      grandTotal: 'Genel toplam:',
      pieces: 'adet',
    },
    empty: 'Henüz siparişiniz yok',
  },
  orderStatus: {
    pending: 'Onay bekliyor',
    approved: 'Kabul edildi',
    ready_to_take: 'Hazırlandı',
    ready_to_deliver: 'Teslim almaya hazır',
    completed: 'Tamamlandı',
    rejected: 'İptal edildi',
    pickup: {
      ready_to_deliver: 'Teslim noktasında bekliyor',
      completed: 'Teslim alındı',
    },
    delivery: {
      ready_to_deliver: 'Teslimata verildi',
      completed: 'Teslim edildi',
    },
  },
  storeWarehouse: {
    title: 'Depo türü: {{type}}',
    fbs: {
      meaning: 'Ürünler sizde saklanır.',
      intake: 'Ürün geldi — <link>«Ürün kabulü»</link> bölümünde işaretleyin',
      stock: 'Rafı yeniden saydınız — <link>«Stok»</link> bölümünde düzeltin',
      orders:
        '<link>Yeni sipariş</link> — kabul edin ve «Hazırlandı» olarak işaretleyin, operatör teslim alacak',
      returns: 'İade — ürün geri geldiğinde <link>«İadeler»</link> bölümünde işaretleyin',
    },
    fbo: {
      meaning: 'Ürünler Postshop deposunda saklanır.',
      shipments: 'Ürünleri depoya gönderin: <link>«Depo» → «Depoya gönderim»</link>',
      stock: 'Depodaki stok — <link>«Depo» → «Depodaki stok»</link>',
      orders:
        '<link>Siparişleri</link> Postshop deposu hazırlar ve teslim eder — sizden bir şey gerekmez',
      returns: '<link>İadeleri</link> Postshop deposu teslim alır',
    },
    changeNote: 'Depo türünü yalnızca Postshop değiştirebilir — <link>desteğe</link> yazın.',
  },
  storeOrders: {
    empty: 'Sipariş yok',
    customer: 'Müşteri',
    noPhone: 'Telefon numarası belirtilmedi',
    noName: 'Ad belirtilmedi',
    comment: 'Yorum',
    approve: 'Onayla',
    reject: 'Reddet',
    fboNote: 'Bu siparişi Postshop deposu hazırlıyor — sizden bir şey yapmanız gerekmiyor.',
    notApproved: 'Operatör siparişi kabul ettikten sonra sipariş işlemleri kullanılabilir olacak.',
    markPacked: 'Hazırlandı',
    rejectConfirmTitle: 'Siparişi reddet',
    rejectReason: 'Ret nedeni',
    rejectReasonPlaceholder: 'Müşteri görecek — örn. “stokta yok”',
    rejectConfirmSubtitle: 'Bu siparişi reddetmek istediğinizden emin misiniz?',
    rejectConfirmButton: 'Evet, reddet',
    status: {
      pending: 'Yeni — siparişi kabul edin',
      approved: 'Kabul edildi — hazırlayın',
      ready_to_take: 'Hazırlandı — operatöre teslim edin',
      rejected: 'Reddettiniz',
    },
  },
  header: {
    storeClosed: 'kapalı',
    searchPlaceholder: 'Ürün, bölüm veya mağaza arayın',
    login: 'Giriş yap',
    selectCity: 'Şehir seçin',
    selectLanguage: 'Dil seçin',
    myStore: 'Mağazam',
    selectStore: 'Mağaza seçin',
    fastSearch: 'Hızlı arama',
    foundProducts: 'Bulunan ürünler',
    foundBrands: 'Bulunan markalar',
    foundStores: 'Bulunan mağazalar',
    viewAll: 'Tümünü gör',
    searching: 'Aranıyor...',
  },

  breadcrumbs: {
    home: 'Ana sayfa',
    stores: 'Mağazalar',
    brands: 'Markalar',
  },

  search: {
    title: 'Arama',
    resultsFor: '"{{query}}" için arama sonuçları',
    noResults: 'Sonuç bulunamadı',
    categories: 'Kategoriler',
    brands: 'Markalar',
    stores: 'Mağazalar',
  },

  store: {
    sort: 'Sırala',
    filter: 'Filtrele',
    about: 'Mağaza hakkında',
    phone: 'Telefon numarası',
    address: 'Adres',
    description: 'Mağaza açıklaması',
  },

  doc: {
    individual: {
      registration: 'Bireysel girişimci tescil belgesi',
      patent: 'Patent (geçerli)',
      certificate: 'Tescil belgesi',
      passport: 'Pasaport kopyası',
    },
    legal: {
      charter: 'Şirket tüzüğü (tüm sayfalar mühürlü olarak onaylanmış)',
      extract: 'Devlet sicilinden alıntı',
      certificate: 'Tescil belgesi',
      statistics: 'İstatistik belgesi (OKED kodları ile)',
      powerOfAttorney: 'Vekaletname veya müdür atama emri',
    },
  },

  nav: {
    next: 'İleri',
  },

  storeInformation: {
    title: 'Mağaza bilgileri',
    subtitle: 'Mağaza bilgilerinizi görüntüleyin ve düzenleyin.',
  },
  storeActivate: {
    goToStore: 'Mağaza paneline git',
    underReview:
      'Mağaza kayıt başvurusu gönderildi ve incelemeyi bekliyor. Ürünler onaylandıktan sonra katalogda görünecek.',
    title: 'Mağazanızı etkinleştirin',
    subtitle:
      'Mağazanızı tamamen açmak için aşağıdaki adımların tamamını tamamlayın. Zorunlu alanlar doldurulmadan hesabınız aktif olmayacaktır.',
    completedSteps: 'Tamamlanan adımlar',
    todos: {
      warehouseType: 'Depo türü',
      warehouseTypeDesc: 'Ürünlerinizi depolamak için depo türünü seçin',
      warehouseTypeLocked: '{{type}} · yönetici değiştirir',
      name: 'Mağaza adı ve açıklaması',
      nameDesc: 'Müşterilerin göreceği mağaza adını girin',
      addresses: 'Adresler',
      addressesDesc: 'Mağaza adreslerinizi girin',
      phoneNumbers: 'Telefon numaraları',
      phoneNumbersDesc: 'Müşterilerin ulaşabileceği telefon numaralarını girin',
      color: 'Renk',
      colorDesc: 'Mağazanızın ana rengini seçin',
      city: 'Şehir',
      cityDesc: 'Mağazanızın bulunduğu şehri seçin',
      logo: 'Logo',
      logoDesc: 'Mağaza logonuzu yükleyin (.webp formatına dönüştürülecek)',
    },
    cityModal: {
      title: 'Şehrinizi seçin',
      save: 'Kaydet',
      saving: 'Kaydediliyor...',
    },
    nameModal: {
      title: 'Mağaza adı ve açıklaması',
      nameLabel: 'Mağaza adı',
      descriptionLabel: 'Açıklama',
      save: 'Kaydet',
      saving: 'Kaydediliyor...',
      nameError: 'Mağaza adını girin',
      descriptionError: 'Açıklama girin',
    },
    addressesModal: {
      title: 'Mağaza adresleri',
      label: 'Adres',
      placeholder: 'Adres girin',
      add: 'Adres ekle',
      save: 'Kaydet',
      saving: 'Kaydediliyor...',
      error: 'En az bir adres girin',
    },
    phoneNumbersModal: {
      title: 'Telefon numaraları',
      label: 'Telefon numarası',
      placeholder: 'Telefon numarası girin',
      add: 'Telefon numarası ekle',
      save: 'Kaydet',
      saving: 'Kaydediliyor...',
      error: 'En az bir telefon numarası girin',
    },
    logoModal: {
      title: 'Mağaza logosu',
      upload: 'Logo yüklemek için tıklayın',
      save: 'Kaydet',
      saving: 'Kaydediliyor...',
      error: 'Logo resmi seçin',
    },
    warehouseTypeModal: {
      title: 'Depo türünüzü seçin',
      save: 'Kaydet',
      saving: 'Kaydediliyor...',
      fbs: {
        name: 'FBS (Satıcı Tarafından Karşılama)',
        description: 'Ürünler satıcının deposunda saklanır ve satıcı tarafından gönderilir',
      },
      fbo: {
        name: 'FBO (Operatör Tarafından Karşılama)',
        description: 'Ürünler pazar yerinin deposunda saklanır ve oradan gönderilir',
      },
    },
    colorModal: {
      title: 'Mağaza rengi',
      selected: 'Seçilen renk',
      bgColor: 'Arka plan rengi',
      textColor: 'Metin rengi',
      customLabel: 'Özel renk',
      save: 'Kaydet',
      saving: 'Kaydediliyor...',
      contrastUnreadable:
        'Bu metin bu arka planda görünmüyor. Kaydetmek için başka bir renk seçin.',
    },
  },

  filter: {
    title: 'Filtreler',
    category: 'Kategori',
    brand: 'Marka',
    brandSearch: 'Marka ara',
    store: 'Mağaza',
    storeSearch: 'Mağaza ara',
    sort: 'Sırala',
    priceRange: 'Fiyat aralığı',
    priceFrom: 'en az',
    priceTo: 'en çok',
    showAll: 'Tümünü gör',
    showLess: 'Daha az gör',
    clearAll: 'Filtreleri temizle',
  },

  sort: {
    expensiveToCheap: 'Pahalıdan ucuza',
    cheapToExpensive: 'Ucuzdan pahalıya',
    newProducts: 'Yeni ürünler',
    discount: 'İndirimler',
    bestSelling: 'En çok satan',
  },

  category: {
    all: 'Tümü',
    male: 'Erkek',
    female: 'Kadın',
  },

  footer: {
    aboutUs: 'Hakkımızda',
    contact: 'İletişim',
    termsOfUse: 'Kullanım şartları',
    privacyPolicy: 'Gizlilik politikası',
    profile: 'Profil',
    myOrders: 'Siparişlerim',
    favorites: 'Favorilerim',
    brands: 'Markalar',
    stores: 'Mağazalar',
    becomeSeller: 'Satıcı ol',
    scrollToTop: 'Yukarı',
    followUs: 'Bizi sosyal medyada takip edin:',
    home: 'Ana sayfa',
    categories: 'Kategoriler',
    cart: 'Sepetim',
    orders: 'Siparişlerim',
  },

  product: {
    unavailable: 'Ürün mevcut değil',
    unavailableHint: 'Satıştan kaldırılmış ya da artık mevcut olmayabilir.',
    inStock: 'Stokta: {{count}}',
    details: 'Detaylar',
    info: 'Ürün bilgileri',
    similar: 'Benzer ürünler',
    youMayLike: 'Beğenebilirsiniz',
    addToCart: 'Sepete ekle',
  },

  products: {
    stock: 'Depoda: {{count}}',
    outOfStock: 'Stokta yok',
    hidden: 'Satışta değil',
    declined: 'Reddedildi',
    hide: 'Satıştan kaldır',
    show: 'Satışa döndür',
    blockedByStaff: 'Platform tarafından satıştan kaldırıldı',
    addButton: 'Ürün ekle',
    empty: 'Ürün yok',
    inReview: 'İncelemede',
  },

  favorites: {
    empty: 'Favori ürününüz yok',
  },

  addProduct: {
    descriptionTooLong:
      'Tam metin ürün sayfasında görünür; listelerde başı ve üç nokta gösterilir.',
    backToProducts: 'Ürünler',
    title: 'Ürün ekle',
    images: 'Görseller',
    imagesMax: '(en fazla 5)',
    imagesAdd: 'Ekle',
    name: 'Ad',
    namePlaceholder: 'Ürün adı',
    description: 'Açıklama',
    descriptionPlaceholder: 'Ürün açıklaması',
    category: 'Kategori',
    categoryPlaceholder: 'Seçin',
    categoryModalTitle: 'Kategori seçin',
    brand: 'Marka',
    brandPlaceholder: 'Seçin',
    brandModalTitle: 'Marka seçin',
    price: 'Fiyat',
    pricePlaceholder: '0',
    currency: 'Para birimi',
    currencyPlaceholder: 'Seçin',
    hashtag: 'Hashtag',
    hashtagPlaceholder: '#hashtag',
    measureUnit: 'Ölçü birimi',
    measureUnitPlaceholder: 'Seçin',
    discountType: 'İndirim türü',
    discountTypeNone: 'Yok',
    discountTypePercentage: 'Yüzde (%)',
    discountTypeFixed: 'Sabit (TMT)',
    discount: 'İndirim',
    discountPlaceholder: '0',
    submit: 'Ürün ekle',
    submitting: 'Yükleniyor...',
    error: 'Lütfen tüm zorunlu alanları doldurun',
    moderationTitle: 'Ürün moderasyona gönderildi',
    moderationDescription:
      'Operatörlerimiz ürününüzü inceleyecek ve onaylandıktan sonra müşterilere sunulacaktır.',
  },

  editProduct: {
    descriptionTooLong:
      'Tam metin ürün sayfasında görünür; listelerde başı ve üç nokta gösterilir.',
    backToProducts: 'Ürünler',
    title: 'Ürünü düzenle',
    images: 'Görseller',
    imagesMax: '(en fazla 5)',
    imagesAdd: 'Ekle',
    name: 'Ad',
    namePlaceholder: 'Ürün adı',
    description: 'Açıklama',
    descriptionPlaceholder: 'Ürün açıklaması',
    category: 'Kategori',
    categoryPlaceholder: 'Seçin',
    categoryModalTitle: 'Kategori seçin',
    brand: 'Marka',
    brandPlaceholder: 'Seçin',
    brandModalTitle: 'Marka seçin',
    price: 'Fiyat',
    pricePlaceholder: '0',
    currency: 'Para birimi',
    currencyPlaceholder: 'Seçin',
    hashtag: 'Hashtag',
    hashtagPlaceholder: '#hashtag',
    measureUnit: 'Ölçü birimi',
    measureUnitPlaceholder: 'Seçin',
    discountType: 'İndirim türü',
    discountTypeNone: 'Yok',
    discountTypePercentage: 'Yüzde (%)',
    discountTypeFixed: 'Sabit (TMT)',
    discount: 'İndirim',
    discountPlaceholder: '0',
    submit: 'Değişiklikleri kaydet',
    submitting: 'Yükleniyor...',
    error: 'Lütfen tüm zorunlu alanları doldurun',
    moderationTitle: 'Ürün moderasyona gönderildi',
    moderationDescription:
      'Operatörlerimiz ürününüzü inceleyecek ve onaylandıktan sonra müşterilere sunulacaktır.',
    saved: 'Değişiklikler kaydedildi',
  },

  checkout: {
    deliveryLater:
      'Teslimat ücretini platform siparişi onaylarken bildirecek — yukarıdaki toplam ön bilgidir.',
    placeOrder: 'Sipariş ver',
    addressRequired: 'Teslimat adresini girin.',
    pickupPointRequired: 'Bir teslim alma noktası seçin.',
    confirmOrder: 'Siparişi onayla',
    clearCart: 'Sepeti temizle',
    orderError: 'Sipariş verilemedi. Lütfen tekrar deneyin.',
    insufficientStock: '"{{product}}" stokta yeterli değil. Lütfen sepetteki miktarı azaltın.',
    insufficientStockGeneric:
      'Sepetinizdeki ürünlerden biri stokta yeterli değil. Lütfen miktarları kontrol edin.',
    deliveryMethod: 'Teslimat yöntemi',
    pickup: 'Teslim alma noktası',
    delivery: 'Teslimat',
    addressPlaceholder: 'Aşkabat, Mahtumkulu bulvarı, bina 1',
    noPickupPoints:
      'Şehrinizde henüz teslim alma noktası yok — teslimatı seçin veya şehri değiştirin',
    showOnMap: 'Haritada göster',
    pickupPointsOnMap: 'Teslim alma noktaları',
    mapUnavailable: 'Harita kullanılamıyor: harita sunucusu yapılandırılmamış.',
    paymentType: 'Ödeme türü',
    cash: 'Nakit',
    card: 'Terminal',
    cashAndCard: 'Nakit ve Terminal',
    comment: 'Yorum',
    commentPlaceholder: 'Siparişiniz için not bırakın...',
    success: {
      title: 'Sipariş başarıyla verildi!',
      description: 'Siparişiniz alındı. En kısa sürede işleme almaya başlayacağız.',
      goHome: 'Ana sayfaya git',
      showOrder: 'Siparişi göster',
    },
  },

  analytics: {
    title: 'Mağaza analitiği',

    subtitle: 'Tüm mağazalarınızın özeti',

    period: 'Dönem: {{from}} — {{to}}',

    totalRevenue: 'Dönem cirosu',

    totalOrders: 'Sipariş',

    shopsCount: 'Mağaza',

    byShop: 'Mağazaya göre',

    topProducts: 'En çok satan ürünler',

    ordersShort: '{{count}} sip.',

    soldShort: '{{count}} adet',

    noShops: 'Henüz mağazanız yok',

    noShopsHint: 'Analitik, mağaza başvurunuz onaylandıktan sonra görünür.',
  },

  cart: {
    notEnough: 'Bu üründen stokta yeterli yok',
    decrease: 'Adedi azalt',
    increase: 'Adedi artır',
    unavailable: 'Bu ürün artık satışta değil',
    unavailableName: 'Ürün kullanılamıyor',
    remove: 'Kaldır',
    hasUnavailable: 'Siparişi vermek için kullanılamayan ürünleri kaldırın',
    hasStockProblem:
      'Bazı ürünler seçtiğiniz miktarda stokta yok — siparişi vermek için onları kaldırın veya miktarı azaltın',
    onlyLeft: 'Stokta yalnızca {{count}} adet var — miktarı azaltın',

    restore: 'Geri al',
    goToCart: 'Sepete',
    title: 'Sepetim',
    empty: 'Sepetiniz boş',
    emptyHint: 'Doldurmaya başlamanın zamanı geldi!',
    confirm: 'Sepeti onayla',
    totalPrice: 'Toplam fiyat',
    productPrice: 'Ürün fiyatı',
    total: 'Toplam:',
    discount: 'İndirim:',
    grandTotal: 'Genel toplam:',
    aboutDelivery: 'Teslimat hakkında',
    noDeliveryInfo: 'Teslimat bilgisi mevcut değil',
  },

  aboutUs: {
    title: 'Hakkımızda',
    subtitle:
      'Postshop, "Türkmenpoçta" posta şirketinin e-ticaret platformudur; kaliteli ürünleri kapınıza kadar ulaştırır.',
    historyTitle: 'Hikayemiz',
    historyDescription:
      "Türkmenpoçta'nın gelişimi, kuruluş tarihi olan 7 Nisan 1993'e dayanmaktadır. Bugün şirket, faaliyetlerini modern gereksinimlere uygun şekilde organize etme hedefini gütmektedir. 26 Ocak 1993'te Türkmenpoçta Posta Hizmetleri Şirketi, Dünya Posta Birliği'ne kabul edilerek devletin resmi posta operatörü haline gelmiştir. Bu sayede çok kısa bir sürede dünyanın 190'dan fazla ülkesine posta gönderme ve bu ülkelerden posta alma imkânı sağlanmıştır.",
    foundedLabel: 'Kuruluş tarihi',
    foundedValue: '7 Nisan 1993',
    upuLabel: 'Dünya Posta Birliği üyeliği',
    upuValue: "26 Ocak 1993'ten beri",
    countriesLabel: 'Posta alışverişi',
    countriesValue: "190'dan fazla ülkeyle",
    servicesTitle: 'Hizmetlerimiz',
    service1: 'Posta gönderimi ve teslim alma',
    service2: 'Gazete ve dergi abonelik hizmetleri',
    service3: 'Posta havalesi ödemeleri',
    service4: 'Toptan ve perakende ticaret',
    service5: 'İletişim hizmetleri ödemeleri',
    service6: 'Kamu ve komünal hizmet ödemeleri',
    service7: 'Kapıdan kapıya teslimat hizmeti',
    service8: 'E-ticaret hizmetleri',
    postshopTitle: 'Postshop Hakkında',
    postshopDescription1:
      'Postshop, Türkmenpoçta posta şirketi tarafından oluşturulan, evden çıkmadan ihtiyacınız olan her şeyi satın almanızı sağlayan bir e-ticaret platformudur. En son teknolojik cihazlardan modern giyime kadar her şeyi burada bulabilirsiniz.',
    postshopDescription2:
      'Postshop e-ticaret platformu, alışveriş ve teslimat deneyimini bir araya getirerek önde gelen markaların kaliteli ürünlerini rekabetçi fiyatlarla sunar; ürünleri hızlı ve güvenilir bir şekilde doğrudan alıcının kapısına kadar teslim eder.',
    benefit1: 'Ekstra çaba gerektirmeyen rahat alışveriş',
    benefit2: 'Özenle seçilmiş ürün çeşitleri',
    benefit3: 'Ülke genelinde hızlı teslimat',
    benefit4: 'Müşteri odaklı güvenilir hizmet',
  },

  contactUs: {
    title: 'Bizimle iletişime geçin',
    name: 'Adınız',
    phone: 'Telefon numaranız',
    message: 'Mesajınız',
    submit: 'Gönder',
    infoTitle: 'İletişim bilgileri',
    phoneLabel: 'Telefon (Pzt-Paz 9:00-19:00)',
    email: 'E-posta',
    address: 'Adres',
    showOnMap: 'Haritada göster',
    error: 'Lütfen tüm alanları doldurun',
    submitting: 'Gönderiliyor...',
    successTitle: 'Mesajınız gönderildi!',
    successDescription: 'En kısa sürede sizinle iletişime geçeceğiz.',
  },

  links: {
    back: 'Geri',
    backToHome: 'Ana sayfaya dön',
  },

  collections: {
    notFound: 'Böyle bir koleksiyon yok',
    empty: 'Bu koleksiyonda henüz uygun ürün yok',
    seeAll: 'Tümünü gör',
  },

  categories: {
    empty: 'Henüz kategori yok',
    productsEmpty: 'Bu bölümde henüz ürün yok',
    seeParent: '«{{name}}» bölümündeki tüm ürünler',
    brandEmpty: 'Bu markanın henüz ürünü yok',
    storeEmpty: 'Bu mağazada henüz ürün yok',
    filteredEmpty: 'Filtrelere uyan sonuç yok',
    filteredEmptyHint: 'Koşulları değiştirin veya filtreleri sıfırlayın',
    productsCount_one: '{{count}} ürün',
    productsCount_other: '{{count}} ürün',
    soon: 'Yakında',
  },

  profileEdit: {
    title: 'Profili düzenle',
    name: 'Ad',
    surname: 'Soyad',
    nameRequired: 'Ad zorunludur',
    surnameRequired: 'Soyad zorunludur',
    save: 'Kaydet',
    saving: 'Kaydediliyor...',
    cancel: 'İptal',
    saved: 'Profil bilgileri kaydedildi',
  },

  notifications: {
    title: 'Bildirimler',
    empty: 'Henüz bildirim yok',
    markAll: 'Tümünü okundu işaretle',
    seeAll: 'Tümünü gör',
    dismiss: 'Bildirimi kaldır',
    loadMore: 'Daha fazla göster',
    deliveryDetail:
      'Teslimat {{delivery}} TMT, toplam {{total}} TMT. Kabul etmiyorsanız siparişi paketlenmeden iptal edin.',
    kind: {
      order_created: 'Yeni sipariş — açın: ürün sizdeyse kabul edip hazırlayın',
      order_cancelled: 'Sipariş iptal edildi',
      product_blocked: 'Platform bir ürünü satıştan kaldırdı',
      receipt_confirmed: 'Kabul onaylandı, stok güncellendi',
      product_out_of_stock: 'Ürün tükendi — yeniden tedarik edin ya da satıştan kaldırın',
      review_received: 'Ürününüze yeni yorum',
      return_received:
        'İade onaylandı — ürün size geri dönecek. Teslim aldığınızda «İadeler» bölümünde işaretleyin',
      shop_blocked: 'Mağaza platform tarafından kapatıldı',
      product_approved: 'Ürün kontrolü geçti',
      product_declined: 'Ürün kontrolü geçemedi',
      shop_approved: 'Mağaza başvurusu onaylandı',
      shop_rejected: 'Mağaza başvurusu reddedildi',
      order_status: 'Sipariş durumu değişti',
      order_shop_rejected: 'Bir mağaza siparişinizin bir kısmını reddetti',
      order_approved_delivery: 'Sipariş onaylandı — teslimat ücreti belirlendi',
      withdrawal_completed: 'Depo ürününüzü teslim etti',
      withdrawal_rejected: 'Depo çekme talebinizi reddetti',
      review_approved: 'Yorumunuz yayınlandı',
      review_rejected: 'Yorumunuz reddedildi',
      return_approved: 'İade onaylandı',
      return_rejected: 'İade reddedildi',
      return_completed: 'İadeniz teslim alındı ve kapatıldı',
    },
  },

  storeReturns: {
    title: 'İadeler',
    subtitle:
      'Mağazanızın ürünleri için iadeler. Kararı Postshop verir; onaylanan iade size ulaştığında burada işaretleyin.',
    fboWarehouse: 'Bu iadeyi Postshop deposu teslim alacak',
    receiveRestock: 'Teslim alındı — satışa geri koy',
    receiveDefective: 'Teslim alındı — kusurlu',
    defectiveTitle: 'Ürün kusurlu mu geldi?',
    defectiveText:
      'İade teslim alındı olarak işaretlenecek, ancak ürün satışa dönmeyecek — stok değişmez.',
    defectiveConfirm: 'Evet, kusurlu',
    restocked: 'Teslim alındı, satışa geri kondu',
    defective: 'Teslim alındı, kusurlu',
    receivedSaved: 'İade teslim alındı olarak işaretlendi',
  },
  returns: {
    periodOver: 'İade süresi doldu',
    hintUntil:
      'Uymadı mı? Ürünün yanındaki «İade et»e basın — {{date}} tarihine kadar. Talebi Postshop inceleyecek',
    amount: 'İade tutarı: {{amount}} TMT',
    title: 'İadelerim',
    subtitle: 'İade talepleri ve bunlarla ilgili kararlar.',
    empty: 'Henüz iade talebi yok',
    unknownProduct: 'Ürün kaldırıldı',
    quantityShort: 'iade edilecek: {{count}}',
    fromOrder: 'sipariş #{{id}}',
    cancel: 'Geri çek',
    cancelled: 'Talep geri çekildi',
    cancelTitle: 'Talep geri çekilsin mi?',
    cancelText: 'Listeden kaybolur. Bu satın alma için yenisini tekrar açabilirsiniz.',
    action: 'İade et',
    hint: 'Ürün uymadı mı? Yanındaki «İade et» düğmesine basın — talebi Postshop inceleyecek',
    createTitle: 'İade talebi',
    purchased: 'satın alınan: {{count}}',
    quantity: 'Kaç adet iade ediyorsunuz',
    reason: 'İade nedeni',
    reasonPlaceholder: 'Üründe ne sorun var',
    reasonRequired: 'İade nedenini yazın',
    quantityRequired: 'Adet girin',
    tooMany: 'Satın alınandan fazlasını iade edemezsiniz: {{count}}',
    notice: 'Talebi platform inceleyecek. Karar bildirimlerde gelir.',
    send: 'Talebi gönder',
    sending: 'Gönderiliyor...',
    sent: 'İade talebi gönderildi',
    notAllowed: 'Bu satın alma için iade zaten sürüyor veya mümkün değil',
    awaitingItem:
      'İade onaylandı. Ürünü herhangi bir Postshop teslim noktasına getirin — teslim alındığında bildirim gelecek.',
    receivedOn: 'Ürün teslim alındı {{date}}',
    status: {
      received: 'İade tamamlandı',
      pending: 'İade inceleniyor',
      approved: 'İade onaylandı',
      rejected: 'İade reddedildi',
    },
  },

  reviews: {
    title: 'Yorumlar',
    none: 'Henüz yorum yok. İlkini bu ürünü satın alan biri bırakabilir.',
    count_one: '{{count}} yorum',
    count_other: '{{count}} yorum',
    leaveTitle: 'Yorum bırak',
    ratingRequired: 'Bir puan seçin',
    textPlaceholder: 'Neyi beğendiniz, neyi beğenmediniz (isteğe bağlı)',
    moderationNotice: 'Yorum, kontrol edildikten sonra sayfada görünür.',
    send: 'Gönder',
    sending: 'Gönderiliyor...',
    sent: 'Yorum kontrole gönderildi',
    onlyAfterPurchase: 'Bu ürünü, içeren sipariş tamamlandıktan sonra yorumlayabilirsiniz.',
    yoursPending: 'Yorumunuz kontrol ediliyor',
    yoursRejected: 'Yorumunuz reddedildi',
    anonymous: 'Müşteri',
    rate: 'Puan ver',
    rateTitle: 'Ürüne puan ver',
    alreadyRated: 'Zaten puan verdiniz',
  },

  addresses: {
    title: 'Adreslerim',
    subtitle: 'Kayıtlı adresi sipariş verirken seçebilirsiniz, yeniden yazmanız gerekmez.',
    add: 'Adres ekle',
    editTitle: 'Adresi düzenle',
    edit: 'Düzenle',
    delete: 'Sil',
    save: 'Kaydet',
    name: 'Etiket',
    namePlaceholder: 'Ev, İş',
    address: 'Adres',
    addressPlaceholder: 'Şehir, sokak, bina, daire',
    titleRequired: 'Bir etiket girin',
    addressRequired: 'Adres girin',
    defaultBadge: 'Varsayılan',
    makeDefault: 'Varsayılan yap',
    empty: 'Kayıtlı adres yok',
    created: 'Adres eklendi',
    saved: 'Adres kaydedildi',
    deleted: 'Adres silindi',
    deleteTitle: 'Adres silinsin mi?',
    deleteText: 'Adres listeden kaybolur. Mevcut siparişler değişmez.',
    chooseSaved: 'Adres seçin',
    newAddress: 'Başka adres',
    saveThis: 'Bu adresi kaydet',
    saveThisName: 'Adres için etiket',
  },

  passwordChange: {
    title: 'Şifre',
    titleFirst: 'Şifre belirle',
    subtitle: 'Şifreyi değiştirmek için mevcut şifreyi girin — hesabınız böyle korunur.',
    subtitleFirst: 'SMS koduyla giriş yapıyorsunuz. Şifre, kullanıcı adıyla girmenizi sağlar.',
    current: 'Mevcut şifre',
    new: 'Yeni şifre',
    repeat: 'Yeni şifreyi yineleyin',
    save: 'Şifreyi değiştir',
    currentRequired: 'Mevcut şifreyi girin',
    currentWrong: 'Mevcut şifre hatalı',
    sameAsCurrent: 'Yeni şifre mevcut olandan farklı olmalı',
    tooShort: 'Şifre en az {{count}} karakter olmalı',
    mismatch: 'Şifreler eşleşmiyor',
    changed: 'Şifre değiştirildi',
    created: 'Şifre belirlendi',
  },

  phoneChange: {
    title: 'Telefon numarası',
    current: 'Mevcut numara: {{phone}}',
    noneYet: 'Numara belirtilmemiş',
    newPhone: 'Yeni numara',
    hint: 'Kod yeni numaraya gelir — böylece numaranın size ait olduğunu doğrularız.',
    sendCode: 'Kod al',
    sending: 'Gönderiliyor...',
    codeSent: 'Kod gönderildi',
    codeSentTo: 'Kod {{phone}} numarasına gönderildi',
    confirm: 'Onayla',
    confirming: 'Kontrol ediliyor...',
    changed: 'Numara değiştirildi',
    wrongCode: 'Kod geçersiz veya süresi dolmuş',
    unavailable: 'Bu numara zaten kullanılıyor veya mevcut numaranız',
    tooOften: 'Kod dakikada bir kez istenebilir',
    phoneIncomplete: 'Numarayı eksiksiz girin',
  },

  termsOfUse: {
    title: 'Kullanım Şartları',
    lastUpdated: 'Son güncelleme: 20 Mayıs 2026',
    sections: {
      general: {
        title: '1. Genel Hükümler',
        p1: 'Bu Kullanım Şartları ("Şartlar"), web sitesi, mobil uygulamalar ve tüm ilgili hizmetler dahil PostShop pazar yeri platformuna erişiminizi ve kullanımınızı ("Platform") düzenler.',
        p2: 'Hesap oluşturarak, platformda gezinerek veya satın alım yaparak bu Şartlara bağlı olmayı kabul edersiniz. Kabul etmiyorsanız Platformu kullanmayı bırakın.',
        p3: 'PostShop bu Şartları istediği zaman güncelleme hakkını saklı tutar. Değişikliklerden sonra Platformu kullanmaya devam etmek, güncellenmiş Şartları kabul etmek anlamına gelir.',
      },
      accounts: {
        title: '2. Kullanıcı Hesapları',
        p1: 'Sipariş vermek veya belirli özelliklere erişmek için geçerli bir telefon numarası girerek hesap oluşturmanız gerekir. Hesap güvenliğinizi sağlamak sizin sorumluluğunuzdadır.',
        p2: 'Doğru ve güncel kişisel bilgiler sağlamalısınız. PostShop, yanlış veya eksik bilgili hesapları askıya alabilir veya silebilir.',
        p3: "Hesabınız altında gerçekleşen tüm işlemlerden siz sorumlusunuz. Yetkisiz erişimden şüphelenirseniz derhal PostShop'a bildirin.",
      },
      orders: {
        title: '3. Siparişler ve Ödemeler',
        p1: 'Tüm ürün fiyatları aksi belirtilmedikçe Türkmen manatı (TMT) cinsinden gösterilir ve geçerli vergileri içerir. Fiyatlar satıcılar tarafından belirlenir ve önceden haber verilmeksizin değişebilir.',
        p2: 'Sipariş onayı aldıktan sonra sipariş onaylanmış sayılır. PostShop, fiyat hataları, ürün bulunmaması veya dolandırıcılık şüphesi nedeniyle siparişleri iptal etme hakkını saklı tutar.',
        p3: 'Ödeme, teslimat veya teslim alma sırasında nakit, banka terminali veya her ikisinin kombinasyonu ile yapılabilir. Tüm ödeme yükümlülükleri ürün teslim alındığında yerine getirilmelidir.',
      },
      delivery: {
        title: '4. Teslimat ve Teslim Alma',
        p1: 'Ürünler bir teslim alma noktasından veya belirtilen adrese teslimat yoluyla alınabilir. Teslimat imkânı ve süreleri bölgeye ve ürüne göre değişebilir.',
        p2: 'PostShop, teslimat hizmetleri için Türkmenpoçta ile ortaklık kurmaktadır. Tahmini teslimat sürelerine uymaya çalışsak da kontrolümüz dışındaki durumlar nedeniyle gecikmeler yaşanabilir.',
        p3: 'Teslimat sırasında ürünleri incelemeniz sizin sorumluluğunuzdadır. Herhangi bir hasar veya tutarsızlık teslim alındıktan sonra 24 saat içinde bildirilmelidir.',
      },
      sellers: {
        title: '5. Satıcılar ve Ürünler',
        p1: 'PostShop, alıcıları bağımsız satıcılarla buluşturan bir pazar yeri olarak hizmet vermektedir. Her satıcı, ürün açıklamalarının, fiyatlandırmanın ve stok durumunun doğruluğundan sorumludur.',
        p2: 'PostShop, açıkça belirtilmedikçe ürünleri üretmez, depolamaz veya doğrudan satmaz. Ürün kalitesi, garantiler ve uyumluluk ilgili satıcının sorumluluğundadır.',
        p3: 'Bir ürün veya satıcıyla ilgili sorun yaşarsanız PostShop desteğiyle iletişime geçin. Anlaşmazlıkları çözmeye yardımcı olacak ve platform politikalarını ihlal eden satıcılara karşı işlem yapabiliriz.',
      },
      returns: {
        title: '6. İadeler ve Geri Ödemeler',
        p1: 'İade ve geri ödeme politikaları, bireysel satıcının şartlarına ve Türkmenistan tüketici koruma kanunlarına tabidir.',
        p2: 'Ürünler, kusurlu olmaları, teslimat sırasında hasar görmüş olmaları veya açıklamadan önemli ölçüde farklı olmaları durumunda iade edilebilir. İade talepleri teslim alındıktan sonra 14 gün içinde yapılmalıdır.',
        p3: 'Geri ödemeler orijinal ödeme yöntemiyle işlenir. İşlem süreleri ödeme sağlayıcısına göre değişebilir.',
      },
      intellectual: {
        title: '7. Fikri Mülkiyet',
        p1: "Logolar, tasarımlar, metinler, grafikler ve yazılım dahil Platformdaki tüm içerik PostShop'un veya lisans verenlerinin mülkiyetindedir ve fikri mülkiyet yasalarıyla korunmaktadır.",
        p2: "PostShop'un önceden yazılı onayı olmaksızın Platformdaki herhangi bir içeriği kopyalayamaz, çoğaltamaz, dağıtamaz veya türev çalışmalar oluşturamazsınız.",
      },
      liability: {
        title: '8. Sorumluluk Sınırlaması',
        p1: 'PostShop, Platformu "olduğu gibi" sunar ve kesintisiz, hatasız veya güvenli erişimi garanti etmez. Platformu kullanımınızdan kaynaklanan dolaylı, tesadüfi veya sonuçsal zararlardan sorumlu değiliz.',
        p2: "PostShop, satıcıların eylemlerinden, ürünlerin kalitesinden veya Platform'daki alıcılar ve satıcılar arasındaki işlemlerden kaynaklanan kayıplardan sorumlu değildir.",
      },
      privacy: {
        title: '9. Gizlilik ve Veri Koruma',
        p1: 'Kişisel verileriniz Gizlilik Politikamıza uygun olarak toplanır ve işlenir. Platformu kullanarak orada açıklanan veri toplamayı kabul etmiş olursunuz.',
        p2: 'PostShop, kişisel verilerinizi yetkisiz erişim, değiştirme veya ifşaya karşı korumak için uygun teknik ve organizasyonel önlemleri uygular.',
      },
      contact: {
        title: '10. İletişim Bilgileri',
        p1: 'Bu Şartlarla ilgili sorular, şikayetler veya öneriler için bizimle iletişime geçin:',
        phoneLabel: 'Telefon:',
        emailLabel: 'E-posta:',
        addressLabel: 'Adres:',
      },
    },
  },

  privacyPolicy: {
    title: 'Gizlilik Politikası',
    lastUpdated: 'Son güncelleme: 20 Mayıs 2026',
    sections: {
      intro: {
        title: '1. Giriş',
        p1: 'PostShop ("biz", "bize" veya "bizim") kullanıcılarımızın gizliliğini korumaya kararlıdır. Bu Gizlilik Politikası, web sitesi ve mobil uygulamalar dahil PostShop pazar yeri platformunu ("Platform") kullandığınızda kişisel verilerinizi nasıl topladığımızı, kullandığımızı, sakladığımızı ve koruduğumuzu açıklar.',
        p2: 'Platformu kullanarak bu Gizlilik Politikasında açıklanan uygulamalara onay vermiş olursunuz. Herhangi bir kişisel bilgi sağlamadan önce dikkatlice okumanızı tavsiye ederiz.',
      },
      dataCollected: {
        title: '2. Topladığımız Veriler',
        p1: 'Hesap bilgileri: Kayıt olduğunuzda telefon numaranızı, adınızı ve soyadınızı topluyoruz.',
        p2: 'Sipariş bilgileri: Sipariş verdiğinizde teslimat adresinizi, ödeme yöntemi tercihinizi ve sipariş geçmişinizi topluyoruz.',
        p3: 'Cihaz ve kullanım verileri: Platformu iyileştirmek için cihazınız (tür, işletim sistemi, tarayıcı), IP adresiniz, ziyaret edilen sayfalar ve etkileşim kalıpları hakkında bilgileri otomatik olarak topluyoruz.',
        p4: 'Satıcı bilgileri: Satıcı olarak kayıt olduğunuzda yasal gerekliliklere uygun olarak ticari tescil belgeleri, vergi kimlik verileri ve bankacılık bilgilerini ek olarak topluyoruz.',
      },
      howWeUse: {
        title: '3. Verilerinizi Nasıl Kullanıyoruz',
        p1: 'Platformda hesabınızı oluşturmak ve yönetmek için.',
        p2: 'Türkmenpoçta ile teslimat koordinasyonu dahil siparişlerinizi işleme koymak ve yerine getirmek için.',
        p3: 'Siparişler, promosyonlar ve Platform güncellemeleri hakkında sizinle iletişim kurmak için.',
        p4: 'Platformu iyileştirmek, kullanım kalıplarını analiz etmek ve yeni özellikler geliştirmek için.',
        p5: 'Dolandırıcılığı önlemek, Kullanım Şartlarımızı uygulamak ve yasal yükümlülükleri yerine getirmek için.',
      },
      sharing: {
        title: '4. Veri Paylaşımı',
        p1: 'Satıcılarla: Siparişlerinizi yerine getirmek için adınızı, teslimat adresinizi ve telefon numaranızı satıcılarla paylaşırız.',
        p2: 'Teslimat ortaklarıyla: Teslimatları tamamlamak için teslimat bilgilerini Türkmenpoçta ve diğer lojistik ortaklarıyla paylaşırız.',
        p3: 'Hizmet sağlayıcılarla: Barındırma, analitik ve müşteri desteği konusunda bize yardımcı olan üçüncü taraf sağlayıcılarla katı gizlilik sözleşmeleri kapsamında veri paylaşabiliriz.',
        p4: "Kişisel verilerinizi üçüncü taraflara satmıyoruz. Yasal olarak gerekli olduğunda veya PostShop'un ve kullanıcılarının haklarını, güvenliğini veya mülkünü korumak için verileri ifşa edebiliriz.",
      },
      cookies: {
        title: '5. Çerezler ve İzleme',
        p1: 'Platform, tercihlerinizi hatırlamak, oturumunuzu sürdürmek ve trafiği analiz etmek için çerezler ve benzer teknolojiler kullanır. Tarayıcınızda çerez ayarlarını yönetebilirsiniz, ancak çerezleri devre dışı bırakmak belirli Platform özelliklerini kısıtlayabilir.',
        p2: 'Oturumunuzu açık tutmak ve dil ile bölge tercihlerinizi saklamak için yerel depolama kullanıyoruz.',
      },
      security: {
        title: '6. Veri Güvenliği',
        p1: 'Kişisel verilerinizi yetkisiz erişim, değiştirme veya ifşaya karşı korumak için şifreleme, güvenli sunucular ve erişim kontrollerini içeren endüstri standardı güvenlik önlemleri uyguluyoruz.',
        p2: 'Makul önlemler alsak da hiçbir elektronik iletim veya depolama yöntemi tamamen güvenli değildir. Verilerinizin mutlak güvenliğini garanti edemeyiz.',
      },
      retention: {
        title: '7. Veri Saklama',
        p1: 'Kişisel verilerinizi hesabınız aktif olduğu sürece veya hizmetlerimizi sağlamak için gerektiği kadar saklarız. Sipariş geçmişi yasal ve muhasebe amaçları için saklanır.',
        p2: 'Hesap silindiğinde, yasal saklama gereklilikleri veya dolandırıcılığı önleme gibi meşru iş amaçları dışında kişisel verileriniz 30 gün içinde kaldırılacaktır.',
      },
      rights: {
        title: '8. Haklarınız',
        p1: 'Erişim: Kişisel bilgilerinizi istediğiniz zaman hesap ayarlarınızda görüntüleyebilir ve güncelleyebilirsiniz.',
        p2: 'Düzeltme: Destek ekibimizle iletişime geçerek hatalı veya eksik verilerin düzeltilmesini talep edebilirsiniz.',
        p3: 'Silme: Platform ayarları aracılığıyla hesabınızı silebilirsiniz. Bu, yasal saklama gerekliliklerine tabi olarak kişisel verilerinizin kaldırılmasına yol açacaktır.',
        p4: 'Taşınabilirlik: Bizimle iletişime geçerek yapılandırılmış, yaygın kullanılan formatta kişisel verilerinizin bir kopyasını talep edebilirsiniz.',
      },
      children: {
        title: '9. Çocuklar',
        p1: 'Platform, 16 yaşın altındaki çocukların kullanımına yönelik değildir. Çocuklardan bilerek kişisel veri toplamıyoruz. Bir çocuğun verilerini topladığımızı öğrenirsek derhal sileriz.',
      },
      changes: {
        title: '10. Bu Politikadaki Değişiklikler',
        p1: 'Bu Gizlilik Politikasını zaman zaman güncelleyebiliriz. Değişiklikler güncellenmiş tarihle bu sayfada yayımlanacaktır.',
        p2: 'Değişiklikler yayımlandıktan sonra Platformu kullanmaya devam etmek, güncellenmiş Gizlilik Politikasını kabul etmek anlamına gelir. Önemli değişiklikler için Platform aracılığıyla veya başka yollarla bilgilendireceğiz.',
      },
      contact: {
        title: '11. Bizimle İletişime Geçin',
        p1: 'Bu Gizlilik Politikası veya kişisel verileriniz hakkında sorularınız, endişeleriniz veya talepleriniz varsa bizimle iletişime geçin:',
        phoneLabel: 'Telefon:',
        emailLabel: 'E-posta:',
        addressLabel: 'Adres:',
      },
    },
  },
}
