export const ru = {
  header: {
    openMenu: 'Открыть меню',
    collapseSidebar: 'Свернуть боковое меню',
    expandSidebar: 'Развернуть боковое меню',
  },
  notFound: {
    title: 'Страница не найдена',
    text: 'Такого раздела нет. Возможно, адрес введён с ошибкой.',
    home: 'На главную',
  },
  search: 'Поиск...',
  actions: {
    delete: 'Удалить',
  },
  pagination: {
    range: '{{from}}–{{to}} из {{total}}',
    pageOf: '{{page}} / {{pages}}',
    prev: 'Назад',
    next: 'Вперёд',
  },
  confirm: {
    cancel: 'Отмена',
    confirm: 'Подтвердить',
    blockTitle: 'Выключить?',
    blockText:
      'Объект перестанет показываться покупателям. Включить обратно можно этим же переключателем.',
    blockConfirm: 'Выключить',
    blockShopTitle: 'Заблокировать магазин?',
    blockShopText: 'Магазин и все его товары исчезнут с витрины. Уже оформленные заказы останутся.',
    blockUserTitle: 'Заблокировать пользователя?',
    blockUserText: 'Пользователь не сможет войти в систему.',
    declineProductTitle: 'Отклонить товар?',
    declineProductText: 'Товар не появится на витрине. Продавец увидит указанную причину.',
    declineShopTitle: 'Отклонить заявку?',
    declineShopText: 'Заявка будет отклонена. Из этого раздела вернуть её нельзя.',
    rejectOrderTitle: 'Отклонить заказ?',
    rejectOrderText: 'Заказ будет отменён, покупатель увидит отказ.',
    resetReceiptTitle: 'Сбросить документ?',
    resetReceiptText: 'Все набранные позиции будут удалены.',
    deleteBannerTitle: 'Удалить баннер?',
    deleteBannerText: '«{{name}}» и его изображения будут удалены безвозвратно.',
    deleteCollectionTitle: 'Удалить подборку?',
    deleteCollectionText: '«{{name}}» будет удалена. Сами товары останутся на месте.',
  },
  errors: {
    network: 'Нет связи с сервером. Проверьте подключение и попробуйте снова',
    server: 'Ошибка на сервере. Попробуйте позже',
    badRequest: 'Не удалось выполнить',
    unauthorized: 'Нужно войти заново',
    forbidden: 'Недостаточно прав',
    notFound: 'Не найдено',
    conflict: 'Уже существует',
    tooLarge: 'Файл слишком большой',
    validation: 'Проверьте заполненные поля',
    tooManyRequests: 'Слишком много попыток. Подождите немного',
    unknown: 'Что-то пошло не так',
  },
  // reusable
  create: 'Создать',
  noResults: 'Ничего не найдено.',
  back: 'Назад',
  cancel: 'Отмена',
  save: 'Сохранить',
  active: 'Активный',
  blocked: 'Заблокированный',
  individual_entrepreneur: 'Индивидуальный предприниматель',
  legal_entity: 'Юридическое лицо',
  fields: {
    firstName: 'Имя',
    username: 'Логин',
    password: 'Пароль',
    confirmPassword: 'Подтвердите пароль',
    name: 'Название',
    nameRu: 'Название (RU)',
    nameTk: 'Название (TK)',
    nameEn: 'Название (EN)',
    nameTr: 'Название (TR)',
    fullName: 'ФИО',
    surname: 'Фамилия',
    email: 'Email',
    phone: 'Телефон',
    createdAt: 'Дата создания',
    status: 'Статус',
    image: 'Изображение',
    message: 'Сообщение',
  },
  placeholders: {
    username: 'Введите имя пользователя',
    password: 'Введите пароль',
    confirmPassword: 'Повторите пароль',
    name: 'Введите название',
  },

  // pages
  pages: {
    dashboard: 'Главная',
    brands: 'Бренды',
    categories: 'Категории',
    createCategory: 'Создать категорию',
    editCategory: 'Редактировать категорию',
    createBrand: 'Создать бренд',
    editBrand: 'Редактировать бренд',
    countries: 'Страны',
    createCountry: 'Создать страну',
    editCountry: 'Редактировать страну',
    regions: 'Регионы',
    createRegion: 'Создать регион',
    editRegion: 'Редактировать регион',
    cities: 'Города',
    createCity: 'Создать город',
    editCity: 'Редактировать город',
    currencies: 'Валюты',
    createCurrency: 'Создать валюту',
    editCurrency: 'Редактировать валюту',
    measureUnits: 'Единицы измерения',
    createMeasureUnit: 'Создать единицу измерения',
    editMeasureUnit: 'Редактировать единицу измерения',
    users: 'Пользователи',
    createUser: 'Создать пользователя',
    editUser: 'Редактировать пользователя',
    stores: 'Магазины',
    storeDetail: 'Детали магазина',
    becomeStoreRequests: 'Заявки на магазин',
    becomeStoreRequestDetail: 'Детали заявки',
    banners: 'Баннеры',
    createBanner: 'Создать баннер',
    editBanner: 'Редактировать баннер',
    collections: 'Коллекции',
    createCollection: 'Создать коллекцию',
    editCollection: 'Редактировать коллекцию',
    deliveryMessage: 'Сообщение о доставке',
    contactUs: 'Обращения',
    warehouses: 'Склады',
    warehouseDetail: 'Детали склада',
    createWarehouse: 'Создать склад',
    editWarehouse: 'Редактировать склад',
    pickupPoints: 'Пункты выдачи',
    createPickupPoint: 'Создать пункт выдачи',
    editPickupPoint: 'Редактировать пункт выдачи',
    goodsReceiving: 'Прием товара',
    createGoodsReceiving: 'Прием товара на склад',
    goodsReceivingDetail: 'Детали приема',
    profile: 'Профиль',
    accountSettings: 'Настройки аккаунта',
    orders: 'Заказы',
    orderDetail: 'Детали заказа',
    productModeration: 'Модерация товаров',
    reviewModeration: 'Модерация отзывов',
    returnRequests: 'Заявки на возврат',
    productModerationDetail: 'Детали товара',
  },

  dashboard: {
    shopsTitle: 'Магазины',
    clientsTitle: 'Клиенты',
    ordersTitle: 'Заказы',
    registeredClients: 'Зарегистрированных клиентов',
  },

  // page specific translations
  login: {
    welcomeBack: 'Добро пожаловать',
    subtitle: 'Войдите в панель управления',
    signIn: 'Войти',
    error: 'Неверное имя пользователя или пароль',
    allRightsReserved: 'Все права защищены.',
  },
  brands: {
    searchPlaceholder: 'Поиск брендов...',
    namePlaceholder: 'Введите название бренда',
    image: 'Изображение',
    uploadImage: 'Загрузить',
  },
  measureUnits: {
    searchPlaceholder: 'Поиск единиц измерения...',
    code: 'Код',
    codePlaceholder: 'шт',
  },
  currencies: {
    searchPlaceholder: 'Поиск валют...',
    code: 'Код валюты',
    codePlaceholder: 'TMT',
  },
  countries: {
    searchPlaceholder: 'Поиск стран...',
    isoCode: 'ISO код',
    isoCodePlaceholder: 'TM',
  },
  regions: {
    searchPlaceholder: 'Поиск регионов...',
    country: 'Страна',
    selectCountry: 'Выберите страну',
  },
  cities: {
    searchPlaceholder: 'Поиск городов...',
    region: 'Регион',
    selectRegion: 'Выберите регион',
  },
  users: {
    searchPlaceholder: 'Поиск пользователей...',
    namePlaceholder: 'Введите имя',
    surnamePlaceholder: 'Введите фамилию',
    usernamePlaceholder: 'Введите логин',
    phonePlaceholder: 'Введите номер телефона',
    passwordPlaceholder: 'Введите пароль',
    confirmPasswordPlaceholder: 'Повторите пароль',
    passwordMismatch: 'Пароли не совпадают',
    permissions: 'Права доступа',
    selectAllPermissions: 'Выбрать все',
    deselectAllPermissions: 'Снять все',
    savePermissions: 'Сохранить права',
  },
  categories: {
    searchPlaceholder: 'Поиск категорий...',
    created: 'Категория создана',
    parent: 'Родительская категория',
    selectParent: 'Выберите категорию',
    noParent: 'Без родительской категории',
    uploadImage: 'Загрузить изображение',
  },
  banners: {
    deleted: 'Баннер удалён',
    searchPlaceholder: 'Поиск баннеров...',
    namePlaceholder: 'Введите название баннера',
    position: 'Позиция',
    positionPlaceholder: 'Выберите позицию',
    positions: {
      home_top: 'Главная — верх',
      home_middle: 'Главная — середина',
      home_bottom: 'Главная — низ',
    },
    link: 'Ссылка',
    linkPlaceholder: 'Введите ссылку',
    priority: 'Приоритет',
    startDate: 'Дата начала',
    endDate: 'Дата окончания',
    uploadImage: 'Загрузить изображение',
    imageTk: 'Изображение (TK)',
    imageRu: 'Изображение (RU)',
    imageEn: 'Изображение (EN)',
    imageTr: 'Изображение (TR)',
  },
  collections: {
    deleted: 'Подборка удалена',
    searchPlaceholder: 'Поиск коллекций...',
    namePlaceholder: 'Введите название коллекции',
    products: 'Продукты',
    searchProducts: 'Поиск продуктов...',
    noProducts: 'Нет доступных продуктов',
    selectedCount: 'Выбрано: {{count}}',
  },
  warehouses: {
    searchPlaceholder: 'Поиск складов...',
    name: 'Название склада',
    namePlaceholder: 'Введите название склада',
    address: 'Адрес',
    addressPlaceholder: 'Введите адрес склада',
    phones: 'Номера телефона',
    phonesPlaceholder: 'Введите номер телефона',
    addPhone: 'Добавить номер',
    actions: 'Действия',
    edit: 'Редактировать',
    products: 'Товары на складе',
    totalProducts: 'Всего: {{count}}',
    searchProducts: 'Поиск товаров...',
    productName: 'Наименование',
    productPrice: 'Цена',
    productQuantity: 'Остаток',
    noProducts: 'На складе нет товаров',
  },
  goodsReceiving: {
    confirm: 'Подтвердить приём',
    confirmTitle: 'Подтвердить приём товара?',
    confirmText:
      'Подтверждение означает, что товар физически принят на склад: он попадёт в остаток магазина. Отменить это будет нельзя.',
    searchPlaceholderList: 'Поиск перемещений...',
    productsCount: 'Кол-во товаров',
    totalQuantity: 'Общее количество',
    status: {
      draft: 'Черновик',
      confirmed: 'Подтверждено',
    },
    measureUnit: 'Ед. изм.',
    warehouse: 'Склад',
    selectWarehouse: 'Выберите склад',
    store: 'Магазин',
    searchStorePlaceholder: 'Поиск магазина...',
    onlyFbo: 'Магазины FBO не найдены. Приёмка — только для них: их товар хранит платформа.',
    detailTitle: 'Прием №{{id}}',
    productsList: 'Товары',
    productsTotal: 'Всего: {{count}}',
    searchProducts: 'Поиск товара',
    searchPlaceholder: 'Введите название товара...',
    noProducts: 'Товары не найдены',
    emptyTable: 'Добавьте товары для приема на склад',
    productName: 'Наименование',
    price: 'Цена',
    quantity: 'Количество',
    operations: 'Операции',
    reset: 'Сброс',
    accept: 'Принять',
  },
  pickupPoints: {
    searchPlaceholder: 'Поиск пунктов выдачи...',
    name: 'Название',
    namePlaceholder: 'Введите название пункта выдачи',
    address: 'Адрес',
    addressPlaceholder: 'Введите адрес',
    city: 'Город',
    selectCity: 'Выберите город',
    latitude: 'Широта',
    latitudePlaceholder: 'Введите широту',
    longitude: 'Долгота',
    longitudePlaceholder: 'Введите долготу',
    location: 'Расположение на карте',
    latitudeRequired: 'Укажите широту — числом или щелчком по карте',
    longitudeRequired: 'Укажите долготу — числом или щелчком по карте',
    latitudeInvalid: 'Широта — число от −90 до 90',
    longitudeInvalid: 'Долгота — число от −180 до 180',
    latitudeHint: 'От −90 до 90, например 37.960100',
    longitudeHint: 'От −180 до 180, например 58.326100',
    mapUnavailable:
      'Карта недоступна: картографический сервер не настроен (VITE_MAP_TILES_URL). Введите широту и долготу в поля выше.',
  },
  stores: {
    searchPlaceholder: 'Поиск магазинов...',
    logo: 'Логотип',
    warehouseType: 'Тип склада',
    addresses: 'Адреса',
    phoneNumbers: 'Телефоны',
    block: 'Заблокировать',
    unblock: 'Разблокировать',
    products: 'Товары магазина',
    noProducts: 'У магазина нет товаров',
    changeWarehouseType: 'Сменить',
    changeWarehouseTypeTitle: 'Перевести магазин на {{type}}?',
    toFbsText:
      'Магазин будет сам хранить товар и вести остатки. Сменить тип можно, только когда у магазина нет остатков (ни своих, ни на складе платформы), открытых заказов и черновиков приёмки: сначала заберите товар со склада и дождитесь завершения заказов.',
    toFboText:
      'Товар магазина будет храниться на складах платформы, и купить его можно будет только после подтверждения приёмки. Сменить тип можно, только когда у магазина нет остатков, открытых заказов и черновиков приёмки: сначала обнулите остатки, которые магазин вёл сам, и дождитесь завершения заказов.',
    fboDisabledHint: 'Склад платформы отключён — перевести на FBO нельзя',
    warehouseTypeChanged: 'Тип склада изменён',
    warehouseTypeBlocked:
      'Сменить тип склада сейчас нельзя: у магазина не должно быть остатков, открытых заказов и черновиков приёмки',
    warehouseTypeBlockers: {
      openOrders: 'открытые заказы: {{count}}',
      draftReceipts: 'черновики приёмки: {{count}}',
      fbsStock: 'товары с остатком у магазина (FBS): {{count}}',
      fboStock: 'товары на складе платформы (FBO): {{count}}',
    },
  },
  warehouseType: {
    fbs: 'FBS',
    fbo: 'FBO',
    none: 'Не выбран',
    fulfilment: {
      fbs: 'FBS — собирает продавец',
      fbo: 'FBO — собирает склад Postshop',
    },
  },
  documentKind: {
    individual_registration: 'Свидетельство о регистрации ИП',
    individual_patent: 'Патент (действующий)',
    individual_certificate: 'Свидетельство о постановке на учёт',
    individual_passport: 'Копия паспорта',
    legal_charter: 'Устав предприятия',
    legal_extract: 'Выписка из ЕГРЮЛ',
    legal_certificate: 'Свидетельство о постановке на учёт',
    legal_statistics: 'Справка из статистики (коды ОКЭД)',
    legal_power_of_attorney: 'Доверенность или приказ о назначении директора',
    unknown: 'Документ (вид не указан)',
    missing: 'Не загружены:',
  },
  documentScan: {
    clean: 'Проверен антивирусом',
    notScanned: 'Не проверен антивирусом',
  },
  becomeStoreRequests: {
    rejectReasonPlaceholder: 'Укажите, что нужно исправить',
    rejectReason: 'Причина отказа',
    shopId: 'ID магазина',
    ownerId: 'ID владельца',
    surname: 'Фамилия',
    legalEntityType: 'Тип лица',
    documents: 'Документы',
    registrationStatus: 'Статус заявки',
    updatedAt: 'Дата обновления',
    accept: 'Принять',
    reject: 'Отклонить',
    pending: 'На рассмотрении',
  },
  registrationStatus: {
    pending: 'На рассмотрении',
    approved: 'Одобрено',
    rejected: 'Отклонено',
    suspended: 'Приостановлено',
  },

  deliveryMessage: {
    textRu: 'Текст (RU)',
    textTk: 'Текст (TK)',
    textEn: 'Текст (EN)',
    textTr: 'Текст (TR)',
    saved: 'Сообщение о доставке сохранено',
  },

  orders: {
    searchPlaceholder: 'Поиск по ID заказа или ID пользователя...',
    userId: 'Пользователь',
    userIdLabel: 'ID {{id}}',
    status: 'Статус',
    deliveryType: 'Доставка / Самовывоз',
    items: 'Кол-во товаров',
    orderNumber: 'Заказ №{{id}}',
    actions: 'Действия',
    approve: 'Принять',
    reject: 'Отклонить',
    readyToPickup: 'Готов к выдаче',
    readyToDeliver: 'Готов к доставке',
    complete: 'Завершить',
    customer: 'Покупатель',
    itemsTitle: 'Товары',
    total: 'Итого',
    grandTotal: 'К оплате',
    shopsTitle: 'Магазины',
    notAllShopsReady: 'Не все магазины готовы к выдаче',
    fboPartWaitsApproval:
      'Статус этой части ведёт склад Postshop — после того как заказ будет принят',
    rejectPartTitle: 'Отклонить часть заказа магазина «{{shop}}»?',
    rejectPartText:
      'Товары этого магазина не будут выданы, покупатель получит уведомление об отказе. Остальные магазины продолжат собирать свои части.',
    rejectPartCommentPlaceholder: 'Причина отказа (необязательно)',
    paymentType: 'Способ оплаты',
    pickupPoint: 'Пункт выдачи',
    deliveryAddress: 'Адрес доставки',
    deliveryPrice: 'Цена доставки',
    deliveryPriceRequired: 'Укажите цену доставки — без неё заказ с доставкой принять нельзя',
    deliveryPriceInvalid: 'Цена доставки должна быть числом не меньше нуля',
    deliveryPriceHint: 'Назначается один раз, при приёме заказа',
    comment: 'Комментарий',
    updatedAt: 'Дата обновления',
    payment: {
      cash: 'Наличные',
      card: 'Банковская карта',
      cashAndCard: 'Наличные и карта',
    },
    statusLabel: {
      pending: 'Ожидание',
      approved: 'Одобрено',
      rejected: 'Отклонено',
      ready_to_take: 'Готов к выдаче',
      ready_to_deliver: 'Готов к доставке',
      completed: 'Завершено',
    },
  },

  // general
  account: {
    logOut: 'Выйти',
  },

  // others
  moderation: {
    shopId: 'Магазин',
    price: 'Цена',
    approve: 'Одобрить',
    decline: 'Отклонить',
    discount: 'Скидка',
    measureUnit: 'Ед. измерения',
    brand: 'Бренд',
    hashtag: 'Хэштег',
    barcode: 'Штрихкод Postshop',
    vendorBarcode: 'Штрихкод производителя',
    alreadyApproved: 'Товар уже одобрен — возможно, другим модератором',
    alreadyDeclined: 'Товар уже отклонён — возможно, другим модератором',
    moderationComment: 'Комментарий модератора',
    updatedAt: 'Дата обновления',
    images: 'Изображения',
    translations: 'Переводы',
    description: 'Описание',
  },

  contactUs: {
    new: 'Новое',
    handled: 'Обработано',
    markHandled: 'Отметить обработанным',
    markNew: 'Вернуть в работу',
  },

  returnStatus: {
    pending: 'На рассмотрении',
    approved: 'Подтверждён',
    rejected: 'Отказано',
  },

  returnRequests: {
    buyer: 'Покупатель',
    order: 'Заказ',
    product: 'Товар',
    quantity: 'Кол-во',
    reason: 'Причина покупателя',
    approveTitle: 'Подтвердить возврат?',
    approveText: 'Подтверждение означает, что товар у платформы: он вернётся на склад магазина.',
    approvePlaceholder: 'Комментарий покупателю (не обязательно)',
    rejectTitle: 'Отказать в возврате?',
    rejectText: 'Причину увидит покупатель — без неё заявка закрывается молча.',
    rejectPlaceholder: 'Почему возврат невозможен',
  },

  reviewStatus: {
    pending: 'На проверке',
    approved: 'Опубликован',
    rejected: 'Отклонён',
  },

  reviewModeration: {
    product: 'Товар',
    rating: 'Оценка',
    text: 'Текст',
    author: 'Автор',
    rejectTitle: 'Отклонить отзыв?',
    rejectText:
      'Причину увидит автор — без неё отзыв просто исчезнет, и исправить его будет нельзя.',
    rejectPlaceholder: 'Почему отзыв не подходит',
  },

  productStatus: {
    pending: 'На модерации',
    approved: 'Одобрено',
    declined: 'Отклонено',
  },

  sidebar: {
    catalog: 'Каталог',
    geography: 'География',
    management: 'Управление',
    stores: 'Магазины и Заказы',
    settings: 'Настройки',
    warehousesAndProducts: 'Склады и товары',
    moderation: 'Модерация',
  },
} as const
