export const tk = {
  header: {
    openMenu: 'Menýuny açmak',
    collapseSidebar: 'Gapdal menýuny ýygyrmak',
    expandSidebar: 'Gapdal menýuny açmak',
  },
  notFound: {
    title: 'Sahypa tapylmady',
    text: 'Beýle bölüm ýok. Salgy ýalňyş girizilen bolmagy mümkin.',
    home: 'Baş sahypa',
  },
  search: 'Gözleg...',
  actions: {
    delete: 'Pozmak',
  },
  pagination: {
    range: '{{total}} sanydan {{from}}–{{to}}',
    pageOf: '{{page}} / {{pages}}',
    prev: 'Yza',
    next: 'Öňe',
  },
  confirm: {
    cancel: 'Ýatyrmak',
    confirm: 'Tassyklamak',
    blockTitle: 'Öçürmelimi?',
    blockText: 'Bu ýazgy alyjylara görkezilmegini bes eder. Şu düwmeden gaýtadan açyp bilersiňiz.',
    blockConfirm: 'Öçürmek',
    blockShopTitle: 'Dükany blokirlemelimi?',
    blockShopText: 'Dükan we ähli harytlary katalogdan aýrylar. Öň edilen sargytlar galar.',
    blockUserTitle: 'Ulanyjyny blokirlemelimi?',
    blockUserText: 'Ulanyjy ulgama girip bilmez.',
    declineProductTitle: 'Haryt ret edilsinmi?',
    declineProductText: 'Haryt katalogda görkezilmez. Satyjy görkezilen sebäbi görer.',
    declineShopTitle: 'Arza ret edilsinmi?',
    declineShopText: 'Arza ret ediler. Bu bölümden yzyna gaýtarmak bolmaýar.',
    rejectOrderTitle: 'Sargyt ret edilsinmi?',
    rejectOrderText: 'Sargyt ýatyrylar, alyjy ret edilenini görer.',
    resetReceiptTitle: 'Resminama arassalanylsynmy?',
    resetReceiptText: 'Girizilen ähli setirler pozular.',
    deleteBannerTitle: 'Banneri pozmalymy?',
    deleteBannerText: '«{{name}}» we onuň suratlary hemişelik pozular.',
    deleteCollectionTitle: 'Ýygyndyny pozmalymy?',
    deleteCollectionText: '«{{name}}» pozular. Harytlaryň özi ýerinde galar.',
  },
  errors: {
    network: 'Serwer bilen aragatnaşyk ýok. Birikmäni barlaň we gaýtadan synanyşyň',
    server: 'Serwerde ýalňyşlyk. Soňra synanyşyň',
    badRequest: 'Ýerine ýetirmek başartmady',
    unauthorized: 'Täzeden girmeli',
    forbidden: 'Ygtyýar ýeterlik däl',
    notFound: 'Tapylmady',
    conflict: 'Eýýäm bar',
    tooLarge: 'Faýl gaty uly',
    validation: 'Doldurylan meýdanlary barlaň',
    tooManyRequests: 'Örän köp synanyşyk. Biraz garaşyň',
    unknown: 'Bir zat ýalňyş gitdi',
  },
  // reusable
  create: 'Döretmek',
  noResults: 'Hiç zat tapylmady.',
  back: 'Yza',
  cancel: 'Ýatyr',
  save: 'Ýatda sakla',
  active: 'Işjeň',
  blocked: 'Bloklanan',
  individual_entrepreneur: 'Hususy telekeçi',
  legal_entity: 'Ýuridik şahslar',
  fields: {
    firstName: 'Ady',
    username: 'Ulanyjy ady',
    password: 'Açar söz',
    confirmPassword: 'Açar sözi tassyklaň',
    name: 'Ady',
    nameRu: 'Ady (RU)',
    nameTk: 'Ady (TK)',
    nameEn: 'Ady (EN)',
    nameTr: 'Ady (TR)',
    fullName: 'Doly ady',
    surname: 'Familiýasy',
    email: 'Email',
    phone: 'Telefon',
    createdAt: 'Döredilen senesi',
    status: 'Ýagdaýy',
    image: 'Surat',
    message: 'Habar',
  },
  placeholders: {
    username: 'Ulanyjy adyny giriziň',
    password: 'Açar sözi giriziň',
    confirmPassword: 'Açar sözi gaýtalaň',
    name: 'Adyny giriziň',
  },

  // pages
  pages: {
    withdrawals: 'Harydy çykarmak',
    dashboard: 'Baş sahypa',
    brands: 'Brendler',
    categories: 'Kategoriýalar',
    createCategory: 'Kategoriýa döretmek',
    editCategory: 'Kategoriýany redaktirlemek',
    createBrand: 'Brend döretmek',
    editBrand: 'Brendy redaktirlemek',
    countries: 'Ýurtlar',
    createCountry: 'Ýurt döretmek',
    editCountry: 'Ýurdy redaktirlemek',
    regions: 'Welaýatlar',
    createRegion: 'Welaýat döretmek',
    editRegion: 'Welaýaty redaktirlemek',
    cities: 'Şäherler',
    createCity: 'Şäher döretmek',
    editCity: 'Şäheri redaktirlemek',
    currencies: 'Walýutalar',
    createCurrency: 'Walýuta döretmek',
    editCurrency: 'Walýutany redaktirlemek',
    measureUnits: 'Ölçeg birlikleri',
    createMeasureUnit: 'Ölçeg birligini döretmek',
    editMeasureUnit: 'Ölçeg birligini redaktirlemek',
    users: 'Ulanyjylar',
    createUser: 'Ulanyjy döretmek',
    editUser: 'Ulanyjyny redaktirlemek',
    stores: 'Dükanlar',
    storeDetail: 'Dükanyň jikme-jigi',
    becomeStoreRequests: 'Dükan arzalary',
    becomeStoreRequestDetail: 'Arzanyň jikme-jigi',
    banners: 'Bannerler',
    createBanner: 'Banner döretmek',
    editBanner: 'Banneri redaktirlemek',
    collections: 'Kolleksiýalar',
    createCollection: 'Kolleksiýa döretmek',
    editCollection: 'Kolleksiýany redaktirlemek',
    deliveryMessage: 'Eltip bermek habary',
    contactUs: 'Ýüzlenmeler',
    warehouses: 'Ammarlar',
    warehouseDetail: 'Ammaryň jikme-jigi',
    createWarehouse: 'Ammar döretmek',
    editWarehouse: 'Ammary redaktirlemek',
    pickupPoints: 'Eltip berme nokatlary',
    createPickupPoint: 'Eltip berme nokadyny döretmek',
    editPickupPoint: 'Eltip berme nokadyny redaktirlemek',
    goodsReceiving: 'Haryt kabul etmek',
    createGoodsReceiving: 'Ammara haryt kabul etmek',
    goodsReceivingDetail: 'Kabul etmegiň jikme-jigi',
    profile: 'Profil',
    accountSettings: 'Hasap sazlamalary',
    orders: 'Sargytlar',
    orderDetail: 'Sargytyň jikme-jigi',
    productModeration: 'Haryt moderasiýasy',
    reviewModeration: 'Syn moderasiýasy',
    returnRequests: 'Gaýtarmak arzalary',
    productModerationDetail: 'Harytyň jikme-jigi',
  },

  dashboard: {
    shopsTitle: 'Dükanlar',
    clientsTitle: 'Müşderiler',
    ordersTitle: 'Sargytlar',
    registeredClients: 'Hasaba alnan müşderiler',
  },

  // page specific translations
  login: {
    welcomeBack: 'Hoş geldiňiz',
    subtitle: 'Dolandyryş paneline giriň',
    signIn: 'Giriş',
    error: 'Nädogry ulanyjy ady ýa-da açar söz',
    allRightsReserved: 'Ähli hukuklar goralan.',
  },
  brands: {
    searchPlaceholder: 'Brendleri gözlemek...',
    namePlaceholder: 'Brendiň adyny giriziň',
    image: 'Surat',
    uploadImage: 'Ýüklemek',
  },
  measureUnits: {
    searchPlaceholder: 'Ölçeg birliklerini gözlemek...',
    code: 'Kody',
    codePlaceholder: 'sany',
  },
  currencies: {
    searchPlaceholder: 'Walýutalary gözlemek...',
    code: 'Walýuta kody',
    codePlaceholder: 'TMT',
  },
  countries: {
    searchPlaceholder: 'Ýurtlary gözlemek...',
    isoCode: 'ISO kody',
    isoCodePlaceholder: 'TM',
  },
  regions: {
    searchPlaceholder: 'Welaýatlary gözlemek...',
    country: 'Ýurt',
    selectCountry: 'Ýurt saýlaň',
  },
  cities: {
    searchPlaceholder: 'Şäherleri gözlemek...',
    region: 'Welaýat',
    selectRegion: 'Welaýat saýlaň',
  },
  users: {
    searchPlaceholder: 'Ulanyjylary gözlemek...',
    namePlaceholder: 'Adyny giriziň',
    surnamePlaceholder: 'Familiýasyny giriziň',
    usernamePlaceholder: 'Ulanyjy adyny giriziň',
    phonePlaceholder: 'Telefon belgisini giriziň',
    passwordPlaceholder: 'Açar sözi giriziň',
    confirmPasswordPlaceholder: 'Açar sözi gaýtalaň',
    passwordMismatch: 'Açar sözler gabat gelmeýär',
    permissions: 'Rugsat hukuklary',
    selectAllPermissions: 'Hemmesini saýla',
    deselectAllPermissions: 'Hemmesini aýyr',
    savePermissions: 'Hukuklary ýatda sakla',
  },
  categories: {
    searchPlaceholder: 'Kategoriýalary gözlemek...',
    namePlaceholder: 'Kategoriýanyň adyny giriziň',
    created: 'Kategoriýa döredildi',
    parent: 'Esasy kategoriýa',
    selectParent: 'Kategoriýa saýlaň',
    noParent: 'Esasy kategoriýasyz',
    uploadImage: 'Surat ýüklemek',
  },
  banners: {
    deleted: 'Banner pozuldy',
    searchPlaceholder: 'Bannerleri gözlemek...',
    namePlaceholder: 'Banneriň adyny giriziň',
    position: 'Pozisiýa',
    positionPlaceholder: 'Pozisiýany saýlaň',
    positions: {
      home_top: 'Baş sahypa — ýokary',
      home_middle: 'Baş sahypa — orta',
      home_bottom: 'Baş sahypa — aşaky',
    },
    link: 'Baglanyşyk',
    linkPlaceholder: 'Baglanyşygy giriziň',
    priority: 'Ileri tutma',
    startDate: 'Başlangyç senesi',
    endDate: 'Gutarýan senesi',
    uploadImage: 'Surat ýüklemek',
    imageTk: 'Surat (TK)',
    imageRu: 'Surat (RU)',
    imageEn: 'Surat (EN)',
    imageTr: 'Surat (TR)',
  },
  collections: {
    deleted: 'Ýygyndy pozuldy',
    searchPlaceholder: 'Kolleksiýalary gözlemek...',
    namePlaceholder: 'Kolleksiýanyň adyny giriziň',
    products: 'Önümler',
    searchProducts: 'Önümleri gözlemek...',
    noProducts: 'Önüm ýok',
    selectedCount: 'Saýlanan: {{count}}',
  },
  warehouses: {
    history: 'Taryh',
    historyTitle: 'Taryh: {{product}}',
    operation: 'Amal',
    op: {
      income: 'Girdeji',
      sold: 'Satuw',
      return_from_customer: 'Alyjydan gaýtarma',
      return_to_shop: 'Dükana gaýtarma',
      write_off: 'Hasapdan aýyrma',
    },
    writeOff: 'Hasapdan aýyr',
    returnToShop: 'Dükana gaýtar',
    writeOffTitle: '«{{product}}» hasapdan aýyrmalymy?',
    returnToShopTitle: '«{{product}}» dükana gaýtarmalymy?',
    writeOffText:
      'Kemçilik, zaýalanma ýa-da ýitgi: haryt satylman galyndydan aýrylar. Ammarda: {{count}}. Açyk sargytlaryň saklaýan harydyny aýryp bolmaýar.',
    returnToShopText:
      'Haryt Postshop ammaryndan satyja gaýtarylýar. Ammarda: {{count}}. Açyk sargytlaryň saklaýan harydyny gaýtaryp bolmaýar.',
    outgoQuantity: 'Mukdar',
    searchPlaceholder: 'Ammarlary gözlemek...',
    name: 'Ammaryň ady',
    namePlaceholder: 'Ammaryň adyny giriziň',
    address: 'Salgysy',
    addressPlaceholder: 'Ammaryň salgysyny giriziň',
    phones: 'Telefon belgileri',
    phonesPlaceholder: 'Telefon belgisini giriziň',
    addPhone: 'Belgi goşmak',
    actions: 'Hereketler',
    edit: 'Redaktirlemek',
    products: 'Ammardaky harytlar',
    totalProducts: 'Jemi: {{count}}',
    searchProducts: 'Harytlary gözlemek...',
    productName: 'Ady',
    productPrice: 'Bahasy',
    productQuantity: 'Galyndy',
    noProducts: 'Ammarda haryt ýok',
  },
  withdrawals: {
    shop: 'Dükan',
    items: 'Harytlar',
    comment: 'Satyjynyň teswiri',
    complete: 'Ýerine ýetir',
    reject: 'Ret et',
    completeTitle: '№{{id}} arzany ýerine ýetirmelimi?',
    completeText:
      'Haryt satyja berildi: ol Postshop ammarlaryndan aýrylar. Harydyň bir bölegi sargytlar bilen eýelenen bolsa, serwer ret eder.',
    rejectTitle: '№{{id}} arzany ret etmelimi?',
    rejectText: 'Sebäbi satyjy görer.',
    rejectPlaceholder: 'Ret etmegiň sebäbi',
    status: {
      pending: 'Garaşýar',
      completed: 'Ýerine ýetirildi',
      rejected: 'Ret edildi',
      cancelled: 'Yzyna alyndy',
    },
  },
  goodsReceiving: {
    cancel: 'Kabul etmegi ýatyr',
    cancelTitle: 'Kabul etmegi ýatyrmalymy?',
    cancelText: 'Resminama ammara girizilmezden ýapylar. Ýatyrylandan soň ony tassyklap bolmaz.',
    editQuantity: 'Üýtget',
    confirm: 'Kabul edildi diý',
    confirmTitle: 'Harydyň kabul edilenini tassyklamalymy?',
    confirmText:
      'Tassyklamak harydyň hakykatdan ammara kabul edilenini aňladýar: ol dükanyň galyndysyna geçer. Muny yzyna gaýtaryp bolmaýar.',
    searchPlaceholderList: 'Hereketleri gözlemek...',
    productsCount: 'Haryt sany',
    totalQuantity: 'Umumy mukdary',
    status: {
      cancelled: 'Ýatyryldy',
      draft: 'Garalama',
      confirmed: 'Tassyklandy',
    },
    measureUnit: 'Ölçeg birligi',
    warehouse: 'Ammar',
    selectWarehouse: 'Ammar saýlaň',
    store: 'Dükan',
    searchStorePlaceholder: 'Dükan gözlemek...',
    onlyFbo:
      'FBO dükanlary tapylmady. Kabul ediş diňe olar üçin: olaryň harytlaryny platforma saklaýar.',
    detailTitle: 'Kabul №{{id}}',
    productsList: 'Harytlar',
    productsTotal: 'Jemi: {{count}}',
    searchProducts: 'Haryt gözlemek',
    searchPlaceholder: 'Harytyň adyny giriziň...',
    noProducts: 'Haryt tapylmady',
    emptyTable: 'Ammara kabul etmek üçin haryt goşuň',
    productName: 'Ady',
    price: 'Bahasy',
    quantity: 'Mukdary',
    operations: 'Amallar',
    reset: 'Arassalamak',
    accept: 'Kabul etmek',
  },
  pickupPoints: {
    searchPlaceholder: 'Eltip berme nokatlaryny gözlemek...',
    name: 'Ady',
    namePlaceholder: 'Eltip berme nokadynyň adyny giriziň',
    address: 'Salgysy',
    addressPlaceholder: 'Salgysy giriziň',
    city: 'Şäher',
    selectCity: 'Şäher saýlaň',
    latitude: 'Giňişlik',
    latitudePlaceholder: 'Giňişligi giriziň',
    longitude: 'Uzynlyk',
    longitudePlaceholder: 'Uzynlygy giriziň',
    location: 'Kartada ýerleşişi',
    latitudeRequired: 'Giňişligi görkeziň — san bilen ýa-da kartada basyp',
    longitudeRequired: 'Uzynlygy görkeziň — san bilen ýa-da kartada basyp',
    latitudeInvalid: 'Giňişlik −90-dan 90-a çenli san bolmaly',
    longitudeInvalid: 'Uzynlyk −180-den 180-e çenli san bolmaly',
    latitudeHint: '−90-dan 90-a çenli, meselem 37.960100',
    longitudeHint: '−180-den 180-e çenli, meselem 58.326100',
    mapUnavailable:
      'Karta elýeterli däl: karta serweri sazlanmadyk (VITE_MAP_TILES_URL). Giňişligi we uzynlygy ýokardaky meýdanlara giriziň.',
  },
  products: {
    sale: {
      title: 'Satuw',
      active: 'Satuwda',
      blockedByStaff: 'Platforma aýyrdy',
      hiddenByOwner: 'Satyjy aýyrdy',
      block: 'Satuwdan aýyr',
      unblock: 'Satuwa gaýtar',
      blockTitle: 'Harydy satuwdan aýyrmalymy?',
      blockText: 'Haryt katalogdan aýrylar. Satyja habar gider we ol harydy özi gaýtaryp bilmez.',
    },
  },
  stores: {
    activity: 'Sargytlar we gaýtarmalar',
    activityTab: {
      orders: 'Sargytlar',
      returns: 'Gaýtarmalar',
    },
    partTotal: 'Dükanyň möçberi',
    searchPlaceholder: 'Dükanlary gözlemek...',
    logo: 'Logotip',
    warehouseType: 'Ammar görnüşi',
    addresses: 'Salgylar',
    phoneNumbers: 'Telefon belgileri',
    block: 'Bloklamak',
    unblock: 'Blokdan aýyrmak',
    products: 'Dükanyň harytlary',
    noProducts: 'Dükanda haryt ýok',
    changeWarehouseType: 'Üýtgetmek',
    changeWarehouseTypeTitle: 'Dükany {{type}}-e geçirmelimi?',
    toFbsText:
      'Dükan harytlaryny özi saklar we galyndylary özi alyp barar. Görnüşi diňe dükanda galyndy (öz ýa-da platformanyň ammarynda), açyk sargyt we kabul edişiň garalamasy ýok wagtynda üýtgedip bolýar: ilki harydy ammardan alyň we sargytlaryň tamamlanmagyna garaşyň.',
    toFboText:
      'Dükanyň harytlary platformanyň ammarlarynda saklanar we olary diňe kabul ediş tassyklanandan soň satyn alyp bolar. Görnüşi diňe dükanda galyndy, açyk sargyt we kabul edişiň garalamasy ýok wagtynda üýtgedip bolýar: ilki dükanyň özi alyp baran galyndylaryny nollaň we sargytlaryň tamamlanmagyna garaşyň.',
    fboDisabledHint: 'Platformanyň ammary öçürildi — FBO-e geçirip bolmaýar',
    warehouseTypeChanged: 'Ammar görnüşi üýtgedildi',
    warehouseTypeBlocked:
      'Ammar görnüşini häzir üýtgedip bolmaýar: dükanda galyndy, açyk sargyt we kabul edişiň garalamasy bolmaly däl',
    warehouseTypeBlockers: {
      openOrders: 'açyk sargytlar: {{count}}',
      draftReceipts: 'kabul edişiň garalamalary: {{count}}',
      fbsStock: 'dükanda galyndysy bar harytlar (FBS): {{count}}',
      fboStock: 'platformanyň ammaryndaky harytlar (FBO): {{count}}',
    },
  },
  warehouseType: {
    fbs: 'FBS',
    fbo: 'FBO',
    none: 'Saýlanmadyk',
    fulfilment: {
      fbs: 'FBS — satyjy ýygnaýar',
      fbo: 'FBO — Postshop ammary ýygnaýar',
    },
  },
  documentKind: {
    individual_registration: 'Şahsy telekeçini hasaba alyş şahadatnamasy',
    individual_patent: 'Patent (hereket edýän)',
    individual_certificate: 'Hasaba alyş şahadatnamasy',
    individual_passport: 'Pasportyň nusgasy',
    legal_charter: 'Kärhananyň düzgünnamasy',
    legal_extract: 'ÝGÝHR-dan göçürme',
    legal_certificate: 'Hasaba alyş şahadatnamasy',
    legal_statistics: 'Statistika baradaky kepilnama (OKED kodlary)',
    legal_power_of_attorney: 'Ynanç haty ýa-da direktor bellemek barada buýruk',
    unknown: 'Resminama (görnüşi görkezilmedik)',
    missing: 'Ýüklenmedi:',
  },
  documentScan: {
    clean: 'Antiwirus bilen barlandy',
    notScanned: 'Antiwirus bilen barlanmady',
  },
  becomeStoreRequests: {
    rejectReasonPlaceholder: 'Näme düzeltmelidigini ýazyň',
    rejectReason: 'Ret ediliş sebäbi',
    shopId: 'Dükanyň ID-si',
    ownerId: 'Eýesiniň ID-si',
    surname: 'Familiýasy',
    legalEntityType: 'Hukuk görnüşi',
    documents: 'Resminamalar',
    registrationStatus: 'Arzanyň ýagdaýy',
    updatedAt: 'Täzelenen senesi',
    accept: 'Kabul etmek',
    reject: 'Ret etmek',
    pending: 'Garaşylýar',
  },
  registrationStatus: {
    pending: 'Garaşylýar',
    approved: 'Tassyklanyldy',
    rejected: 'Ret edildi',
    suspended: 'Togtadyldy',
  },

  deliveryMessage: {
    textRu: 'Tekst (RU)',
    textTk: 'Tekst (TK)',
    textEn: 'Tekst (EN)',
    textTr: 'Tekst (TR)',
    saved: 'Eltip bermek habary ýatda saklandy',
  },

  orders: {
    searchPlaceholder: 'Sargyt belgisi ýa-da alyjynyň telefony boýunça gözlemek...',
    filter: {
      unpaid: 'Tölenmedik',
      all: 'Hemmesi',
      fbo: 'Postshop ammaryna garaşýar',
    },
    rejectCommentPlaceholder: 'Ret etmegiň sebäbi — ony alyjy we dükanlar görer',
    customerComment: 'Alyjynyň teswiri',
    statusComment: 'Platformanyň karary',
    userId: 'Ulanyjy',
    userIdLabel: 'ID {{id}}',
    status: 'Ýagdaýy',
    deliveryType: 'Eltip beriş / Öz alma',
    items: 'Haryt sany',
    orderNumber: 'Sargyt №{{id}}',
    actions: 'Hereketler',
    approve: 'Kabul etmek',
    reject: 'Ret etmek',
    customer: 'Müşderi',
    itemsTitle: 'Harytlar',
    total: 'Jemi',
    grandTotal: 'Tölemeli',
    shopsTitle: 'Dükanlar',
    notAllShopsReady: 'Ähli dükanlar sargydyň öz bölegini ýygnamady',
    fboPartWaitsApproval:
      'Bu bölegiň ýagdaýyny Postshop ammary alyp barýar — sargyt kabul edilenden soň',
    rejectPartTitle: '«{{shop}}» dükanynyň sargyt bölegini ret etmelimi?',
    rejectPartText:
      'Bu dükanyň harytlary berilmez, alyja ret edilendigi barada habar gider. Beýleki dükanlar öz böleklerini ýygnamagy dowam eder.',
    rejectPartCommentPlaceholder: 'Ret etmegiň sebäbi (hökman däl)',
    paymentType: 'Töleg görnüşi',
    pickupPoint: 'Eltip berme nokady',
    deliveryAddress: 'Eltip beriş salgysy',
    deliveryPrice: 'Eltip beriş bahasy',
    deliveryPriceRequired:
      'Eltip beriş bahasyny giriziň — onsuz eltip berilýän sargydy kabul edip bolmaýar',
    deliveryPriceInvalid: 'Eltip beriş bahasy noldan pes bolmadyk san bolmaly',
    deliveryPriceHint: 'Bir gezek bellenýär — sargyt kabul edilende',
    comment: 'Teswir',
    updatedAt: 'Täzelenen senesi',
    payment: {
      title: 'Töleg',
      paid: 'Tölendi',
      unpaid: 'Tölenmedi',
      paidAt: 'Tölendi {{date}}',
      mark: 'Tölegi belle',
      unmark: 'Belligi aýyr',
      requiredToComplete: 'Diňe tölenen sargydy tamamlap bolýar',
      cash: 'Nagt',
      card: 'Bank karty',
      cashAndCard: 'Nagt we kart',
    },
    statusLabel: {
      pending: 'Tassyklanmagyna garaşýar',
      approved: 'Kabul edildi',
      rejected: 'Ret edildi',
      ready_to_take: 'Ýygnaldy',
      ready_to_deliver: 'Bermek nokadynda ýa-da eltip berilýär',
      completed: 'Tamamlandy',
    },
    statusLabelBy: {
      pickup: {
        ready_to_deliver: 'Bermek nokadynda garaşýar',
        completed: 'Alyja berildi',
      },
      delivery: {
        ready_to_deliver: 'Eltip bermäge berildi',
        completed: 'Eltip berildi',
      },
    },
    action: {
      approved: 'Kabul etmek',
      rejected: 'Ret etmek',
      ready_to_take: 'Ýygnaldy',
      ready_to_deliver: 'Bermek nokadyna ýa-da eltip bermäge berildi',
      completed: 'Tamamlamak',
    },
    actionBy: {
      pickup: {
        ready_to_deliver: 'Bermek nokadyna berildi',
        completed: 'Alyja berildi',
      },
      delivery: {
        ready_to_deliver: 'Eltip bermäge berildi',
        completed: 'Eltip berildi',
      },
    },
  },

  // general
  account: {
    logOut: 'Çykmak',
  },

  // others
  moderation: {
    shopId: 'Dükan',
    price: 'Bahasy',
    approve: 'Tassyklamak',
    decline: 'Ret etmek',
    declineReasonPlaceholder: 'Ret etmegiň sebäbi — ony satyjy görer',
    discount: 'Arzanladyş',
    measureUnit: 'Ölçeg birligi',
    brand: 'Brend',
    hashtag: 'Heşteg',
    barcode: 'Postshop ştrihkody',
    vendorBarcode: 'Öndürijiniň ştrihkody',
    alreadyApproved: 'Haryt eýýäm tassyklanan — belki, başga moderator tarapyndan',
    alreadyDeclined: 'Haryt eýýäm ret edilen — belki, başga moderator tarapyndan',
    moderationComment: 'Moderatoryň teswiri',
    updatedAt: 'Täzelenen senesi',
    images: 'Suratlar',
    translations: 'Terjimeler',
    description: 'Beýany',
  },

  contactUs: {
    new: 'Täze',
    handled: 'Işlenildi',
    markHandled: 'Işlenildi diý',
    markNew: 'Işe gaýtar',
  },

  returnStatus: {
    pending: 'Seredilýär',
    approved: 'Tassyklandy',
    rejected: 'Kabul edilmedi',
  },

  returnRequests: {
    amount: 'Möçber',
    buyer: 'Alyjy',
    order: 'Sargyt',
    product: 'Haryt',
    quantity: 'Sany',
    reason: 'Alyjynyň sebäbi',
    approveTitle: 'Gaýtarmagy tassyklamalymy?',
    approveText:
      'Alyjy gaýtarmagyň kabul edilendigini biler we harydy getirer. Galyndy entek üýtgemeýär: haryt alnyp barlanandan soň satuwa gaýdyp geler — FBO üçin Postshop ammary, FBS üçin satyjy.',
    approvePlaceholder: 'Alyja teswir (hökmany däl)',
    rejectTitle: 'Gaýtarmakdan boýun gaçyrmalymy?',
    rejectText: 'Sebäbi alyjy görer — ony aýtmasaň, arza dymyp ýapylýar.',
    rejectPlaceholder: 'Gaýtarmak näme üçin mümkin däl',
    receipt: 'Kabul edilişi',
    receiveRestock: 'Ammara alyndy — satuwa',
    receiveDefective: 'Alyndy — kemçilikli',
    sellerReceives: 'Satyjy kabul edýär',
    receiveForSeller: 'Satyjynyň ýerine bellemek',
    receivedRestocked: 'Alyndy, satuwa',
    receivedDefective: 'Alyndy, kemçilikli',
    receiveTitle: 'Gaýtarylan haryt alyndy diýip bellemelimi?',
    receiveRestockText:
      'Haryt bitewi we dükanyň galyndysyna gaýdyp geler — ony ýene satyn alyp bolar. Muny yzyna gaýtaryp bolmaz.',
    receiveDefectiveText:
      'Haryt kemçilikli diýlip ykrar edildi: galyndysyna gaýdyp gelmez. Muny yzyna gaýtaryp bolmaz.',
    receiveChooseText:
      'FBS gaýtarmasyny adatça satyjy kabul edýär. Haryt sizde bolsa ýa-da satyjy kabul edendigini tassyklasa, onuň ýerine belläň. Muny yzyna gaýtaryp bolmaz.',
    toStock: 'Satuwa',
    defective: 'Kemçilikli',
  },

  reviewStatus: {
    pending: 'Barlagda',
    approved: 'Ýerleşdirildi',
    rejected: 'Kabul edilmedi',
  },

  reviewModeration: {
    product: 'Haryt',
    rating: 'Baha',
    text: 'Tekst',
    author: 'Awtor',
    rejectTitle: 'Syny kabul etmelimi däl?',
    rejectText: 'Sebäbi awtor görer — ony aýtmasaň, syn ýöne ýitýär we düzedip bolmaýar.',
    rejectPlaceholder: 'Syn näme üçin laýyk däl',
  },

  productStatus: {
    pending: 'Moderasiýada',
    approved: 'Tassyklanyldy',
    declined: 'Ret edildi',
  },

  sidebar: {
    catalog: 'Katalog',
    geography: 'Geografiýa',
    management: 'Menejment',
    stores: 'Dükanlar we Sargytlar',
    settings: 'Sazlamalar',
    warehousesAndProducts: 'Ammarlar we harytlar',
    moderation: 'Moderasiýa',
  },
} as const
