export const tk = {
  header: {
    openMenu: 'Menýuny açmak',
    collapseSidebar: 'Gapdal menýuny ýygyrmak',
    expandSidebar: 'Gapdal menýuny açmak',
  },
  notFound: {
    title: 'Sahypa tapylmady',
    text: 'Beýle bölüm ýok. Salgy ýalňyş girizilen bolmagy mümkin.',
    home: 'Baş sahypa',
  },
  search: 'Gözleg...',
  actions: {
    delete: 'Pozmak',
  },
  pagination: {
    range: '{{total}} sanydan {{from}}–{{to}}',
    pageOf: '{{page}} / {{pages}}',
    prev: 'Yza',
    next: 'Öňe',
  },
  confirm: {
    cancel: 'Ýatyrmak',
    confirm: 'Tassyklamak',
    blockTitle: 'Öçürmelimi?',
    blockText: 'Bu ýazgy alyjylara görkezilmegini bes eder. Şu düwmeden gaýtadan açyp bilersiňiz.',
    blockConfirm: 'Öçürmek',
    blockShopTitle: 'Dükany blokirlemelimi?',
    blockShopText: 'Dükan we ähli harytlary katalogdan aýrylar. Öň edilen sargytlar galar.',
    blockUserTitle: 'Ulanyjyny blokirlemelimi?',
    blockUserText: 'Ulanyjy ulgama girip bilmez.',
    declineProductTitle: 'Haryt ret edilsinmi?',
    declineProductText: 'Haryt katalogda görkezilmez. Satyjy görkezilen sebäbi görer.',
    declineShopTitle: 'Arza ret edilsinmi?',
    declineShopText: 'Arza ret ediler. Bu bölümden yzyna gaýtarmak bolmaýar.',
    rejectOrderTitle: 'Sargyt ret edilsinmi?',
    rejectOrderText: 'Sargyt ýatyrylar, alyjy ret edilenini görer.',
    resetReceiptTitle: 'Resminama arassalanylsynmy?',
    resetReceiptText: 'Girizilen ähli setirler pozular.',
    deleteBannerTitle: 'Banneri pozmalymy?',
    deleteBannerText: '«{{name}}» we onuň suratlary hemişelik pozular.',
    deleteCollectionTitle: 'Ýygyndyny pozmalymy?',
    deleteCollectionText: '«{{name}}» pozular. Harytlaryň özi ýerinde galar.',
  },
  errors: {
    network: 'Serwer bilen aragatnaşyk ýok. Birikmäni barlaň we gaýtadan synanyşyň',
    server: 'Serwerde ýalňyşlyk. Soňra synanyşyň',
    badRequest: 'Ýerine ýetirmek başartmady',
    unauthorized: 'Täzeden girmeli',
    forbidden: 'Ygtyýar ýeterlik däl',
    notFound: 'Tapylmady',
    conflict: 'Eýýäm bar',
    tooLarge: 'Faýl gaty uly',
    validation: 'Doldurylan meýdanlary barlaň',
    tooManyRequests: 'Örän köp synanyşyk. Biraz garaşyň',
    unknown: 'Bir zat ýalňyş gitdi',
  },
  // reusable
  create: 'Döretmek',
  noResults: 'Hiç zat tapylmady.',
  back: 'Yza',
  cancel: 'Ýatyr',
  save: 'Ýatda sakla',
  active: 'Işjeň',
  blocked: 'Bloklanan',
  individual_entrepreneur: 'Hususy telekeçi',
  legal_entity: 'Ýuridik şahslar',
  fields: {
    firstName: 'Ady',
    username: 'Ulanyjy ady',
    password: 'Açar söz',
    confirmPassword: 'Açar sözi tassyklaň',
    name: 'Ady',
    nameRu: 'Ady (RU)',
    nameTk: 'Ady (TK)',
    nameEn: 'Ady (EN)',
    nameTr: 'Ady (TR)',
    fullName: 'Doly ady',
    surname: 'Familiýasy',
    email: 'Email',
    phone: 'Telefon',
    createdAt: 'Döredilen senesi',
    status: 'Ýagdaýy',
    image: 'Surat',
    message: 'Habar',
  },
  placeholders: {
    username: 'Ulanyjy adyny giriziň',
    password: 'Açar sözi giriziň',
    confirmPassword: 'Açar sözi gaýtalaň',
    name: 'Adyny giriziň',
  },

  // pages
  pages: {
    dashboard: 'Baş sahypa',
    brands: 'Brendler',
    categories: 'Kategoriýalar',
    createCategory: 'Kategoriýa döretmek',
    editCategory: 'Kategoriýany redaktirlemek',
    createBrand: 'Brend döretmek',
    editBrand: 'Brendy redaktirlemek',
    countries: 'Ýurtlar',
    createCountry: 'Ýurt döretmek',
    editCountry: 'Ýurdy redaktirlemek',
    regions: 'Welaýatlar',
    createRegion: 'Welaýat döretmek',
    editRegion: 'Welaýaty redaktirlemek',
    cities: 'Şäherler',
    createCity: 'Şäher döretmek',
    editCity: 'Şäheri redaktirlemek',
    currencies: 'Walýutalar',
    createCurrency: 'Walýuta döretmek',
    editCurrency: 'Walýutany redaktirlemek',
    measureUnits: 'Ölçeg birlikleri',
    createMeasureUnit: 'Ölçeg birligini döretmek',
    editMeasureUnit: 'Ölçeg birligini redaktirlemek',
    users: 'Ulanyjylar',
    createUser: 'Ulanyjy döretmek',
    editUser: 'Ulanyjyny redaktirlemek',
    stores: 'Dükanlar',
    storeDetail: 'Dükanyň jikme-jigi',
    becomeStoreRequests: 'Dükan arzalary',
    becomeStoreRequestDetail: 'Arzanyň jikme-jigi',
    banners: 'Bannerler',
    createBanner: 'Banner döretmek',
    editBanner: 'Banneri redaktirlemek',
    collections: 'Kolleksiýalar',
    createCollection: 'Kolleksiýa döretmek',
    editCollection: 'Kolleksiýany redaktirlemek',
    deliveryMessage: 'Eltip bermek habary',
    contactUs: 'Ýüzlenmeler',
    warehouses: 'Ammarlar',
    warehouseDetail: 'Ammaryň jikme-jigi',
    createWarehouse: 'Ammar döretmek',
    editWarehouse: 'Ammary redaktirlemek',
    pickupPoints: 'Eltip berme nokatlary',
    createPickupPoint: 'Eltip berme nokadyny döretmek',
    editPickupPoint: 'Eltip berme nokadyny redaktirlemek',
    goodsReceiving: 'Haryt kabul etmek',
    createGoodsReceiving: 'Ammara haryt kabul etmek',
    goodsReceivingDetail: 'Kabul etmegiň jikme-jigi',
    profile: 'Profil',
    accountSettings: 'Hasap sazlamalary',
    orders: 'Sargytlar',
    orderDetail: 'Sargytyň jikme-jigi',
    productModeration: 'Haryt moderasiýasy',
    reviewModeration: 'Syn moderasiýasy',
    returnRequests: 'Gaýtarmak arzalary',
    productModerationDetail: 'Harytyň jikme-jigi',
  },

  dashboard: {
    shopsTitle: 'Dükanlar',
    clientsTitle: 'Müşderiler',
    ordersTitle: 'Sargytlar',
    registeredClients: 'Hasaba alnan müşderiler',
  },

  // page specific translations
  login: {
    welcomeBack: 'Hoş geldiňiz',
    subtitle: 'Dolandyryş paneline giriň',
    signIn: 'Giriş',
    error: 'Nädogry ulanyjy ady ýa-da açar söz',
    allRightsReserved: 'Ähli hukuklar goralan.',
  },
  brands: {
    searchPlaceholder: 'Brendleri gözlemek...',
    namePlaceholder: 'Brendiň adyny giriziň',
    image: 'Surat',
    uploadImage: 'Ýüklemek',
  },
  measureUnits: {
    searchPlaceholder: 'Ölçeg birliklerini gözlemek...',
    code: 'Kody',
    codePlaceholder: 'sany',
  },
  currencies: {
    searchPlaceholder: 'Walýutalary gözlemek...',
    code: 'Walýuta kody',
    codePlaceholder: 'TMT',
  },
  countries: {
    searchPlaceholder: 'Ýurtlary gözlemek...',
    isoCode: 'ISO kody',
    isoCodePlaceholder: 'TM',
  },
  regions: {
    searchPlaceholder: 'Welaýatlary gözlemek...',
    country: 'Ýurt',
    selectCountry: 'Ýurt saýlaň',
  },
  cities: {
    searchPlaceholder: 'Şäherleri gözlemek...',
    region: 'Welaýat',
    selectRegion: 'Welaýat saýlaň',
  },
  users: {
    searchPlaceholder: 'Ulanyjylary gözlemek...',
    namePlaceholder: 'Adyny giriziň',
    surnamePlaceholder: 'Familiýasyny giriziň',
    usernamePlaceholder: 'Ulanyjy adyny giriziň',
    phonePlaceholder: 'Telefon belgisini giriziň',
    passwordPlaceholder: 'Açar sözi giriziň',
    confirmPasswordPlaceholder: 'Açar sözi gaýtalaň',
    passwordMismatch: 'Açar sözler gabat gelmeýär',
    permissions: 'Rugsat hukuklary',
    selectAllPermissions: 'Hemmesini saýla',
    deselectAllPermissions: 'Hemmesini aýyr',
    savePermissions: 'Hukuklary ýatda sakla',
  },
  categories: {
    searchPlaceholder: 'Kategoriýalary gözlemek...',
    namePlaceholder: 'Kategoriýanyň adyny giriziň',
    created: 'Kategoriýa döredildi',
    parent: 'Esasy kategoriýa',
    selectParent: 'Kategoriýa saýlaň',
    noParent: 'Esasy kategoriýasyz',
    uploadImage: 'Surat ýüklemek',
  },
  banners: {
    deleted: 'Banner pozuldy',
    searchPlaceholder: 'Bannerleri gözlemek...',
    namePlaceholder: 'Banneriň adyny giriziň',
    position: 'Pozisiýa',
    positionPlaceholder: 'Pozisiýany saýlaň',
    positions: {
      home_top: 'Baş sahypa — ýokary',
      home_middle: 'Baş sahypa — orta',
      home_bottom: 'Baş sahypa — aşaky',
    },
    link: 'Baglanyşyk',
    linkPlaceholder: 'Baglanyşygy giriziň',
    priority: 'Ileri tutma',
    startDate: 'Başlangyç senesi',
    endDate: 'Gutarýan senesi',
    uploadImage: 'Surat ýüklemek',
    imageTk: 'Surat (TK)',
    imageRu: 'Surat (RU)',
    imageEn: 'Surat (EN)',
    imageTr: 'Surat (TR)',
  },
  collections: {
    deleted: 'Ýygyndy pozuldy',
    searchPlaceholder: 'Kolleksiýalary gözlemek...',
    namePlaceholder: 'Kolleksiýanyň adyny giriziň',
    products: 'Önümler',
    searchProducts: 'Önümleri gözlemek...',
    noProducts: 'Önüm ýok',
    selectedCount: 'Saýlanan: {{count}}',
  },
  warehouses: {
    searchPlaceholder: 'Ammarlary gözlemek...',
    name: 'Ammaryň ady',
    namePlaceholder: 'Ammaryň adyny giriziň',
    address: 'Salgysy',
    addressPlaceholder: 'Ammaryň salgysyny giriziň',
    phones: 'Telefon belgileri',
    phonesPlaceholder: 'Telefon belgisini giriziň',
    addPhone: 'Belgi goşmak',
    actions: 'Hereketler',
    edit: 'Redaktirlemek',
    products: 'Ammardaky harytlar',
    totalProducts: 'Jemi: {{count}}',
    searchProducts: 'Harytlary gözlemek...',
    productName: 'Ady',
    productPrice: 'Bahasy',
    productQuantity: 'Galyndy',
    noProducts: 'Ammarda haryt ýok',
  },
  goodsReceiving: {
    confirm: 'Kabul edildi diý',
    confirmTitle: 'Harydyň kabul edilenini tassyklamalymy?',
    confirmText:
      'Tassyklamak harydyň hakykatdan ammara kabul edilenini aňladýar: ol dükanyň galyndysyna geçer. Muny yzyna gaýtaryp bolmaýar.',
    searchPlaceholderList: 'Hereketleri gözlemek...',
    productsCount: 'Haryt sany',
    totalQuantity: 'Umumy mukdary',
    status: {
      draft: 'Garalama',
      confirmed: 'Tassyklandy',
    },
    measureUnit: 'Ölçeg birligi',
    warehouse: 'Ammar',
    selectWarehouse: 'Ammar saýlaň',
    store: 'Dükan',
    searchStorePlaceholder: 'Dükan gözlemek...',
    onlyFbo:
      'FBO dükanlary tapylmady. Kabul ediş diňe olar üçin: olaryň harytlaryny platforma saklaýar.',
    detailTitle: 'Kabul №{{id}}',
    productsList: 'Harytlar',
    productsTotal: 'Jemi: {{count}}',
    searchProducts: 'Haryt gözlemek',
    searchPlaceholder: 'Harytyň adyny giriziň...',
    noProducts: 'Haryt tapylmady',
    emptyTable: 'Ammara kabul etmek üçin haryt goşuň',
    productName: 'Ady',
    price: 'Bahasy',
    quantity: 'Mukdary',
    operations: 'Amallar',
    reset: 'Arassalamak',
    accept: 'Kabul etmek',
  },
  pickupPoints: {
    searchPlaceholder: 'Eltip berme nokatlaryny gözlemek...',
    name: 'Ady',
    namePlaceholder: 'Eltip berme nokadynyň adyny giriziň',
    address: 'Salgysy',
    addressPlaceholder: 'Salgysy giriziň',
    city: 'Şäher',
    selectCity: 'Şäher saýlaň',
    latitude: 'Giňişlik',
    latitudePlaceholder: 'Giňişligi giriziň',
    longitude: 'Uzynlyk',
    longitudePlaceholder: 'Uzynlygy giriziň',
    location: 'Kartada ýerleşişi',
    locationRequired: 'Kartada ýerleşişi belläň',
  },
  stores: {
    searchPlaceholder: 'Dükanlary gözlemek...',
    logo: 'Logotip',
    warehouseType: 'Ammar görnüşi',
    addresses: 'Salgylar',
    phoneNumbers: 'Telefon belgileri',
    block: 'Bloklamak',
    unblock: 'Blokdan aýyrmak',
    products: 'Dükanyň harytlary',
    noProducts: 'Dükanda haryt ýok',
    changeWarehouseType: 'Üýtgetmek',
    changeWarehouseTypeTitle: 'Dükany {{type}}-e geçirmelimi?',
    toFbsText:
      'Dükan harytlaryny özi saklar we galyndylary özi alyp barar. Platformanyň ammaryndaky galyndy sargytlarda hasaba alynmaz — harydy ammardan alyň. Eýýäm resmileşdirilen sargytlar öňki görnüşde tamamlanar.',
    toFboText:
      'Dükanyň harytlary platformanyň ammarlarynda saklanar. Dükanyň özi alyp baran galyndylary hasaba alynmaz: kabul ediş tassyklanýança harytlaryny satyn alyp bolmaz. Eýýäm resmileşdirilen sargytlar öňki görnüşde tamamlanar.',
    fboDisabledHint: 'Platformanyň ammary öçürildi — FBO-e geçirip bolmaýar',
    warehouseTypeChanged: 'Ammar görnüşi üýtgedildi',
  },
  warehouseType: {
    fbs: 'FBS',
    fbo: 'FBO',
  },
  documentKind: {
    individual_registration: 'Şahsy telekeçini hasaba alyş şahadatnamasy',
    individual_patent: 'Patent (hereket edýän)',
    individual_certificate: 'Hasaba alyş şahadatnamasy',
    individual_passport: 'Pasportyň nusgasy',
    legal_charter: 'Kärhananyň düzgünnamasy',
    legal_extract: 'ÝGÝHR-dan göçürme',
    legal_certificate: 'Hasaba alyş şahadatnamasy',
    legal_statistics: 'Statistika baradaky kepilnama (OKED kodlary)',
    legal_power_of_attorney: 'Ynanç haty ýa-da direktor bellemek barada buýruk',
    unknown: 'Resminama (görnüşi görkezilmedik)',
    missing: 'Ýüklenmedi:',
  },
  documentScan: {
    clean: 'Antiwirus bilen barlandy',
    notScanned: 'Antiwirus bilen barlanmady',
  },
  becomeStoreRequests: {
    rejectReasonPlaceholder: 'Näme düzeltmelidigini ýazyň',
    rejectReason: 'Ret ediliş sebäbi',
    shopId: 'Dükanyň ID-si',
    ownerId: 'Eýesiniň ID-si',
    surname: 'Familiýasy',
    legalEntityType: 'Hukuk görnüşi',
    documents: 'Resminamalar',
    registrationStatus: 'Arzanyň ýagdaýy',
    updatedAt: 'Täzelenen senesi',
    accept: 'Kabul etmek',
    reject: 'Ret etmek',
    pending: 'Garaşylýar',
  },
  registrationStatus: {
    pending: 'Garaşylýar',
    approved: 'Tassyklanyldy',
    rejected: 'Ret edildi',
    suspended: 'Togtadyldy',
  },

  deliveryMessage: {
    textRu: 'Tekst (RU)',
    textTk: 'Tekst (TK)',
    textEn: 'Tekst (EN)',
    textTr: 'Tekst (TR)',
    saved: 'Eltip bermek habary ýatda saklandy',
  },

  orders: {
    searchPlaceholder: 'Sargyt ID ýa-da ulanyjy ID boýunça gözlemek...',
    userId: 'Ulanyjy',
    userIdLabel: 'ID {{id}}',
    status: 'Ýagdaýy',
    deliveryType: 'Eltip beriş / Öz alma',
    items: 'Haryt sany',
    orderNumber: 'Sargyt №{{id}}',
    actions: 'Hereketler',
    approve: 'Kabul etmek',
    reject: 'Ret etmek',
    readyToPickup: 'Almaga taýyn',
    readyToDeliver: 'Eltip bermäge taýyn',
    complete: 'Tamamlamak',
    customer: 'Müşderi',
    itemsTitle: 'Harytlar',
    total: 'Jemi',
    grandTotal: 'Tölemeli',
    shopsTitle: 'Dükanlar',
    notAllShopsReady: 'Ähli dükanlar almaga taýyn däl',
    paymentType: 'Töleg görnüşi',
    pickupPoint: 'Eltip berme nokady',
    deliveryAddress: 'Eltip beriş salgysy',
    deliveryPrice: 'Eltip beriş bahasy',
    deliveryPriceRequired:
      'Eltip beriş bahasyny giriziň — onsuz eltip berilýän sargydy kabul edip bolmaýar',
    deliveryPriceInvalid: 'Eltip beriş bahasy noldan pes bolmadyk san bolmaly',
    deliveryPriceHint: 'Bir gezek bellenýär — sargyt kabul edilende',
    comment: 'Teswir',
    updatedAt: 'Täzelenen senesi',
    payment: {
      cash: 'Nagt',
      card: 'Bank karty',
      cashAndCard: 'Nagt we kart',
    },
    statusLabel: {
      pending: 'Garaşylýar',
      approved: 'Tassyklanyldy',
      rejected: 'Ret edildi',
      ready_to_take: 'Almaga taýyn',
      ready_to_deliver: 'Eltip bermäge taýyn',
      completed: 'Tamamlandy',
    },
  },

  // general
  account: {
    logOut: 'Çykmak',
  },

  // others
  moderation: {
    shopId: 'Dükan',
    price: 'Bahasy',
    approve: 'Tassyklamak',
    decline: 'Ret etmek',
    discount: 'Arzanladyş',
    measureUnit: 'Ölçeg birligi',
    brand: 'Brend',
    hashtag: 'Heşteg',
    moderationComment: 'Moderatoryň teswiri',
    updatedAt: 'Täzelenen senesi',
    images: 'Suratlar',
    translations: 'Terjimeler',
    description: 'Beýany',
  },

  contactUs: {
    new: 'Täze',
    handled: 'Işlenildi',
    markHandled: 'Işlenildi diý',
    markNew: 'Işe gaýtar',
  },

  returnStatus: {
    pending: 'Seredilýär',
    approved: 'Tassyklandy',
    rejected: 'Kabul edilmedi',
  },

  returnRequests: {
    buyer: 'Alyjy',
    order: 'Sargyt',
    product: 'Haryt',
    quantity: 'Sany',
    reason: 'Alyjynyň sebäbi',
    approveTitle: 'Gaýtarmagy tassyklamalymy?',
    approveText:
      'Tassyklamak harydyň platformada bolşuny aňladýar: ol dükanyň ammaryna gaýdyp geler.',
    approvePlaceholder: 'Alyja teswir (hökmany däl)',
    rejectTitle: 'Gaýtarmakdan boýun gaçyrmalymy?',
    rejectText: 'Sebäbi alyjy görer — ony aýtmasaň, arza dymyp ýapylýar.',
    rejectPlaceholder: 'Gaýtarmak näme üçin mümkin däl',
  },

  reviewStatus: {
    pending: 'Barlagda',
    approved: 'Ýerleşdirildi',
    rejected: 'Kabul edilmedi',
  },

  reviewModeration: {
    product: 'Haryt',
    rating: 'Baha',
    text: 'Tekst',
    author: 'Awtor',
    rejectTitle: 'Syny kabul etmelimi däl?',
    rejectText: 'Sebäbi awtor görer — ony aýtmasaň, syn ýöne ýitýär we düzedip bolmaýar.',
    rejectPlaceholder: 'Syn näme üçin laýyk däl',
  },

  productStatus: {
    pending: 'Moderasiýada',
    approved: 'Tassyklanyldy',
    declined: 'Ret edildi',
  },

  sidebar: {
    catalog: 'Katalog',
    geography: 'Geografiýa',
    management: 'Menejment',
    stores: 'Dükanlar we Sargytlar',
    settings: 'Sazlamalar',
    warehousesAndProducts: 'Ammarlar we harytlar',
    moderation: 'Moderasiýa',
  },
} as const
